### ISSUE TITLE
matchRegexp

### ISSUE THREAD

**Issue by aesopwolf** [christianalfoni/formsy-react#101]
```matchRegexp``` doesn't work with react 0.12.2 and formsy 0.11.2. The page doesn't even load for me, I have to kill it from Chrome Task Manager, so it's kind of hard to debug :/

**Comment by Semigradsky** [comment]
Maybe you can give more information? Have you checked that after the removal of the `matchRegexp` rule all worked fine?
Can you give your `regexp`?

**Comment by christianalfoni** [comment]
@aesopwolf Are you not able to update to React 0.13.x? If so, that would be great, or we have to look more into it with more information.

**Comment by aesopwolf** [comment]
Unfortunately, I'm not able to update to React 0.13.x (at least at the moment).

In the mean time I've added my own ```addValidationRule``` that takes care of my use case. I'm okay with this solution. So if you want to close this feel free! Thanks

**Comment by christianalfoni** [comment]
Okay, glad you found a solution.  I say we just close this as people will be moving on to React 0.13 and especially React 0.14 with its new "parent-child" context which will help a lot of libraries out there.
