### ISSUE TITLE
Error 'Formsy does not have the validation rule: minLength'

### ISSUE THREAD

**Issue by frost555** [christianalfoni/formsy-react#102]
<MyInput validations='minLength:6' />

gives error "Formsy does not have the validation rule: minLength"

**Comment by frost555** [comment]
I can see it was removed from the source code. Just didn't notice the change.

**Comment by frost555** [comment]
Need to update readme

**Comment by Semigradsky** [comment]
Which version are you using?
`minLength` validation will be added in 0.11.0 version. And it is still present.

**Comment by frost555** [comment]
Sorry, it was some old cache issue on my side. Please close.
