### ISSUE TITLE
TypeError when running with Jest

### ISSUE THREAD

**Issue by worklez** [christianalfoni/formsy-react#107]
I'm getting `TypeError: Cannot read property '_currentElement' of null` ([full stacktrace](https://raw.githubusercontent.com/worklez/jest-react-formsy/master/stacktrace.txt)) when running a Jest test with component having Formsy.Mixin.
I've put a small [repo](https://github.com/worklez/jest-react-formsy) to reproduce the issue, running `npm install && npm run test` should be enough to reproduce.

I see that problem originates from the `Mixin` trying to eventually call `setState` from `componentWillMount`.
Using `componentDidMount` instead of `componentWillMount` in https://github.com/christianalfoni/formsy-react/blob/b18b4e8c799bbc47d7ecc512b7606cdd2d85c2fa/src/Mixin.js#L49 solves this particular error, but not sure if it is correct to do so.

**Comment by worklez** [comment]
I've verified that all "Rules" tests fail when changing `componentWillMount` to `componentDidMount`, so apparently this is not an option.

**Comment by pnuzhdin** [comment]
+1 it affects me too!

**Comment by christianalfoni** [comment]
Hi there! Thanks for checking this out and creating a great test case. I
will look into this tomorrow morning :-)

**Comment by christianalfoni** [comment]
Hi there,

When testing React and Formsy in Node you need to load up JSDOM. At least currently. This is also required by other libraries so please do something like this in your test setup:

```js
var jsdom = require("jsdom").jsdom;
global.document = jsdom();
global.window = document.defaultView;
global.navigator = global.window.navigator;
```

I am releasing a new test suite with Formsy today that uses this setup. You can check that out for more inspiration :-)

**Comment by worklez** [comment]
Hi Christian,

Thank you for the suggestion and looking into this! Jest already includes
jsdom, and other UI tests (also React-based, but without Formsy.Mixin) pass
fine.

2015-04-24 11:59 GMT+06:00 Christian Alfoni <notifications@github.com>:

**Comment by christianalfoni** [comment]
Hi again,

Hm, thats weird. The Formsy tests runs fine, though using jasmine-node and jsdom. Let me complete the test setup here as there might be a code change in Formsy since I last run that setup.

If I get the same error I will fix it or I will check out the repo with tests to dive into as it must be jest related.

**Comment by christianalfoni** [comment]
Okay, I can verify that all Formsy tests runs fine with jasmine-node and jsdom. Looking into jest now

**Comment by christianalfoni** [comment]
@worklez 

What verison of Node are you running? Seems that Jest does not support 0.12? Trying version 0.10.25, but getting an error there too.

**Comment by worklez** [comment]
I am running node 0.10.35.

2015-04-24 12:49 GMT+06:00 Christian Alfoni <notifications@github.com>:

**Comment by christianalfoni** [comment]
Okay,

I figured it out. Not quite sure why this happens. It might be a JSDOM thing. But you can not require the component inside the test, you have to do this:

```js
jest.autoMockOff();
var React = require('react/addons');
var TestUtils = React.addons.TestUtils;
var LoginPage = require('./../LoginPage.js');

describe('LoginPage', function () {
    it('has submit button disabled', function () {
        var loginPage = TestUtils.renderIntoDocument(React.createElement(LoginPage));
    });
});
```

**Comment by worklez** [comment]
Thank you for the investigation. Will try moving the require out in the full testcase.

**Comment by christianalfoni** [comment]
Great, let me know how it works out! I keep pondering on why this causes an issue, it should not matter where you require. But I definitely think it is an environment thing and not a Formsy thing. Anyways, it is better to require them at the top because you probable have multiple tests using the same component :-)

**Comment by worklez** [comment]
@christianalfoni Thanks! I've refactored tests and they pass now. I wanted to keep things local requiring needed deps and setting mocks up in `it` blocks, but having common `require`s works for me too.
Still interesting what is the cause of the issue though.

**Comment by christianalfoni** [comment]
Great! I will close the issue then. Yeah, it is a really weird problem. It would be worth checking out if this works:

```js
jest.autoMockOff();
var React = require('react/addons');
var TestUtils = React.addons.TestUtils;

describe('LoginPage', function () {
    it('has submit button disabled', function () {
        var LoginPage = require('./../LoginPage.js');
        var loginPage = TestUtils.renderIntoDocument(LoginPage());
    });
});
```

The error itself is related to how the component is wrapped. You have `createElement` and also `createFactory` which needs to be used as wrappers on plain components. JSX syntax does this for you. Maybe the components gets wrapped automatically when required inside the tests?

**Comment by worklez** [comment]
I do actually use JSX in tests, just wanted to keep the example small without transpiler configuration.
Requiring inside `it` and calling `LoginPage()` directly gives React warning about factories and an exception:

```
  - TypeError: Cannot read property '__reactAutoBindMap' of undefined
        at Constructor (node_modules/react/lib/ReactClass.js:842:15)
        at Spec.<anonymous> (__tests__/LoginPage-test.js:8:54)
        at jasmine.Block.execute (node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:1065:17)
        at jasmine.Queue.next_ (node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2098:31)
        at null._onTimeout (node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2088:18)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by christianalfoni** [comment]
Ah, hm, okay thanks for reporting that back. I am out of theories, at least right now. Let you know if I figure it out ;-)
