### ISSUE TITLE
Set type=email on inputs for emails

### ISSUE THREAD

**Issue by binarykitchen** [christianalfoni/formsy-react#109]
That neat HTML5 feature is already out there so why not use it?

**Comment by christianalfoni** [comment]
Hi @binarykitchen ,

If that native feature is enough you should definitely use it. But Formsy is a form element builder and validator that takes the concept of form validation a lot further than native functionality. Formsy gives you any type of validation you desire and form handlers that triggers whenever the form elements you build change, becomes valid, invalid. External errors can be injected, cross input validation is not a problem etc.

Please let me know if you have any more questions to Formsy :-)

**Comment by binarykitchen** [comment]
sure, fair enough, all that is very nice ... but using type='email' can save you some code

**Comment by frost555** [comment]
You can pass desired type as prop.
Then you just set it in your input component. I do it this way with password. I think email type also won't be an issue.

**Comment by christianalfoni** [comment]
@binarykitchen using native validation would not conform with the validation possibilities you have with Formsy. So even though it would be one less validation rule packed into Formsy, setting type="email" would not give you the possibility to check if input is pristine, it is required, disable the form when it is invalid etc. Btw, native invalid inputs looks different in all browsers, it is not very nice ;-)

**Comment by morenoh149** [comment]
I want mobile browsers to not suggest a leading uppercase character. I believe passing `type="email"` avoids this.
