### ISSUE TITLE
default value

### ISSUE THREAD

**Issue by srconklin** [christianalfoni/formsy-react#11]
I can't seem to figure out the best way to pass in a default value as a prop to my formsy form elements when i want to use the form for edit instead of input..

I have a parent component like so
&lt;AgencyEditor agency={this.state.agency} />

that contains a formsy form like so

 &lt;div className="form-group">
  &lt;label for="agency_id">Agency ID:</label>
 &lt;TextBox name="agency_id"  defaultValue={this.props.agency} validations="isLength:3" validationError="ID must be at least 3 characters" required />
    </div>

Where <TextBox> wraps an input box like so:

 &lt;input  ref={this.props.name} defaultValue={this.props.defaultValue} onFocus={this.props.onFocus} id={this.props.name} name={this.props.name} type={this.props.type} value={this.getValue()} onChange={this.changeValue} className="form-control" placeholder={this.props.placeHolder} />

it would appear that the call to value={this.getValue()}  is overwriting the default data.. 
so i tried the following inside of my <Textbox>  component

 componentWillReceiveProps   {
 if (nextProps.defaultValue) {
      this.setValue(nextProps.defaultValue);
    };
}
but i got caught up in an endless loop calling the render method over and over and had to kill the browser.

What i have is a parent component that owns the AgencyEditor  and an AgencySelector components.. the AgencyEditor has a selectbox that passes it's selected value (onChange) up to the parent component then the parent component passes the value back down to AgencyEditor   component where i am trying to show it the input box as indicated above.

Does this makes sense?  do you know how best to accomplish what I want or what I am doing wrong?

Thanks

**Comment by christianalfoni** [comment]
Hi Scott!

You know what, we seem to have forgotten to document the "value" attribute.

```javascript
<MyElement value="whatever"/>
´´´

That should set the default value :-) Will update the readme now!

**Comment by srconklin** [comment]
Hi Christian-

Thanks for the quick response. 

well, it seems to work if I pass a hardcoded value as you have done in the example:

<code><pre>&lt;TextBox name="agency_id"  value='hello' validations="isLength:3" validationError="ID must be at least 3 characters" required /></pre><code>

which then sets it until some user input overwrites it which is fine.
but i need to be like this:

<code><pre>&lt;TextBox name="agency_id"  value={this.props.agency} validations="isLength:3" validationError="ID must be at least 3 characters" required /></pre><code>

so that the onchange of my select box (in another sibling component) will pass its value (via the prop agency) to it and i can see it update on every change in the option selection.

That does not seem to be working....Seems like i can only set it once with  the value attribute.. then i can never get a new value to overwrite it.. must be something in the way my components are structured?  see screenshot... thanks for your help..

http://www.evernote.com/shard/s349/sh/32d2f31c-3b19-436c-b325-9950cee769f1/5ecdb65e62000af079d97e35541fdf1c

**Comment by christianalfoni** [comment]
I am having a look at this tomorrow, thanks for the feedback :-)

**Comment by christianalfoni** [comment]
Hi again,

This is now fixed :-)

Will be part of the release later today.

**Comment by christianalfoni** [comment]
Hm, it is not fixed, broke all the tests.

It creates a circular reaction where the change of that value requires a new validation which again sets the value and again validates and so on.

Actually I think you have to structure this a bit differently. Instead of using the "defaultValue" on the input I would do this:

```javascript
  componentWillReceiveProps: function (nextProps) {

   // Only change to the new default value if it is currently showing the old one
    if (this.getValue() === this.props.defaultValue && nextProps.defaultValue !== this.props.defaultValue) {
      this.setValue(nextProps.defaultValue);
    }
  },
```
And if you want an empty input to change into the default input:

```javascript
  changeValue: function (event) {
    this.setValue(event.target.value || this.props.defaultValue);
  }
```

I think this will solve your problem :-)

**Comment by srconklin** [comment]
Thanks. I will give this a try later today.. thanks for looking into the issue

**Comment by aesopwolf** [comment]
This almost works. The problem is that the defaultValue (value?) doesn't get loaded on first page load. For example, this code block:

```jsx
'use strict';

var React = require('react');
var Formsy = require('formsy-react');

var Input = React.createClass({
	mixins: [Formsy.Mixin],
	changeValue: function(event) {
		this.setValue(event.currentTarget.value || this.props.defaultValue);
	},
	componentWillReceiveProps: function (nextProps) {
		// Only change to the new default value if it is currently showing the old one
		if (this.getValue() === this.props.defaultValue && nextProps.defaultValue !== this.props.defaultValue) {
			this.setValue(nextProps.defaultValue);
		}
	},
	render: function() {
		var className = this.showRequired() ? 'required' : this.showError() ? 'error' : null;
		var errorMessage = this.getErrorMessage();

		return (
			<div className={className}>
				<input type="text" value={this.getValue()} onChange={this.changeValue} />
			</div>
		);
	}
});

module.exports = Input;

```
and this component...

```jsx
<Formsy.Form url="/users" onSuccess={this.changeUrl} onValid={this.enableButton} onInvalid={this.disableButton}>
  <Form.Input name="firstName" required defaultValue={this.state.profile.first}/>
  <button type="submit" disabled={!this.state.canSubmit}>Submit</button>
</Formsy.Form>
````

Will load an input element with an empty value. However, by entering value AND THEN deleting it will the defaultValue appear in the input. Here's a .gif:

![out](https://cloud.githubusercontent.com/assets/6847633/5991027/0871470a-a987-11e4-833f-993719aab4fb.gif)

I think the reason for this behavior might be because ```nextProps.defaultValue``` is undefined on the first  load. I guess it's because ```componentWillReceiveProps``` is not called on the initial render. Any suggestions on what to do here?

**Comment by christianalfoni** [comment]
Let me know if I misunderstand, but you want the input to show "John" instantly?

I think the easiest way to achieve this is by also passing it as a value:

```javascript
<Formsy.Form url="/users" onSuccess={this.changeUrl} onValid={this.enableButton} onInvalid={this.disableButton}>
  <Form.Input name="firstName" required value={this.state.profile.first} defaultValue={this.state.profile.first}/>
  <button type="submit" disabled={!this.state.canSubmit}>Submit</button>
</Formsy.Form>
```

So you handle the "initial value" using the normal "value" attribute, and your custom "defaultValue" attribute as the fallback value. You could consider also using the "componentWillMount" method to grab the "defaultValue" prop and set the value of the input:

```javascript
var Input = React.createClass({
    mixins: [Formsy.Mixin],
    componentWillMount: function () {
      this.setValue(this.props.defaultValue);
    },
    changeValue: function(event) {
        this.setValue(event.currentTarget.value || this.props.defaultValue);
    },
    componentWillReceiveProps: function (nextProps) {
        // Only change to the new default value if it is currently showing the old one
        if (this.getValue() === this.props.defaultValue && nextProps.defaultValue !== this.props.defaultValue) {
            this.setValue(nextProps.defaultValue);
        }
    },
    render: function() {
        var className = this.showRequired() ? 'required' : this.showError() ? 'error' : null;
        var errorMessage = this.getErrorMessage();

        return (
            <div className={className}>
                <input type="text" value={this.getValue()} onChange={this.changeValue} />
            </div>
        );
    }
});
```

Hopefully I understood the problem :-)

**Comment by aesopwolf** [comment]
Thanks for the quick reply! You indeed understood the problem correctly :)

I tried both methods you suggested, but ran into the same problem as @srconklin, which is that these methods only seem to work with hardcoded strings, and not from the react state ```{this.state.profile.first}```

**Comment by aesopwolf** [comment]
Actually, on second hand... My problem might not be related to formsy, and instead an issue of the way ```{this.state.profile.first}``` is being set. It's an async api call to a server that's happening in a mixin. So that's why it's ```undefined``` here:

```jsx
componentWillMount: function() {
	console.log(this.props.defaultValue); // undefined?
	this.setValue(this.props.defaultValue);
},
```

Do you think that sounds right?

**Comment by christianalfoni** [comment]
Hi yeah, that sounds right :-)

Maybe you should consider not rendering the form until the async mixin is done?

**Comment by aesopwolf** [comment]
@christianalfoni sorry for my amateur hour from before... I got it figured it out! But I'm back to the endless loop.

@srconklin did you figure out how to avoid the endless loop? 

I'm thinking a new method ```setValueNoValidate``` might be needed for the ```componentWillReceiveProps``` method that does just as it says, it sets the value but doesn't validate it. Thus preventing an endless loop, maybe? 

Obviously this wouldn't be good for data that needs to be validated as soon as it loaded, but if it's coming from the server you can probably safely assume it's already validated. 

What do you guys think?

**Comment by christianalfoni** [comment]
Hi there,

Could you try updating to the latest version of the lib? It now supports dynamically inserted form elements, which I think might fix your problem too. Let me know if not and we will dive into this a bit more :-)

**Comment by aesopwolf** [comment]
Oh! That's good news. I tried it out, and I don't get the endless loop anymore! However, I still have one more problem.

This code will work fine: 
```jsx
<Formsy.Form url="/users" onSuccess={this.changeUrl} onValid={this.enableButton} onInvalid={this.disableButton}>
  <MyOwnInput name="email" value={this.state.profile.email} />
  <button type="submit" disabled={!this.state.canSubmit}>Submit</button>
</Formsy.Form>
```

But as soon as I put any validations on it:

```jsx
<Formsy.Form url="/users" onSuccess={this.changeUrl} onValid={this.enableButton} onInvalid={this.disableButton}>
  <MyOwnInput name="email" value={this.state.profile.email} validations="isEmail" validationError="This is not a valid email" required/>
  <button type="submit" disabled={!this.state.canSubmit}>Submit</button>
</Formsy.Form>
```

Then it will throw the error ```Uncaught TypeError: Cannot read property 'match' of undefined``` in the console. This could probably be fixed in the validationRules with a check to make sure the ```value``` argument is defined. 

```jsx
'isEmail': function (value) {
  // do a check for `value` first, otherwise the next line throws an error since `value` is sometimes undefined (like on first page load)
  return value.match(/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]...
}
```
--

Also, to double check. When building my form element, should ```componentWillRecieveProps``` be as simple as this?:

```jsx
componentWillReceiveProps: function (nextProps) {
	this.setValue(nextProps.value);
},
```

**Comment by christianalfoni** [comment]
Hi there,

Good to hear that it works! Hm, yeah, it could handle undefined as an empty string. But again:

```javascript
<Formsy.Form url="/users" onSuccess={this.changeUrl} onValid={this.enableButton} onInvalid={this.disableButton}>
  <MyOwnInput name="email" value={this.state.profile.email || ''} />
  <button type="submit" disabled={!this.state.canSubmit}>Submit</button>
</Formsy.Form>
```
Would also work. It should at least throw an error. Have to think about that :-)

The issue with `componentWillReceiveProps` is that a `setValue` call will trigger a new form validation, which again triggers `componentWillReceiveProps`. So you should get a loop. You could of course just do:

```javascript
componentWillReceiveProps: function (nextProps) {
  if (nextProps.value !== this.getValue()) {
    this.setValue(nextProps.value);
  }    
},
```
I think :-)

**Comment by ppiekarczyk** [comment]
```
componentWillReceiveProps: function (nextProps) {
  if (nextProps.value !== this.getValue()) {
    this.setValue(nextProps.value);
  } 
``` FWIW, this solution works. I solved this on my own, a little bit ago. On the quest of `default values`, however..

**Comment by christianalfoni** [comment]
Thanks for input @ppiekarczyk. This should be handled by Formsy now. About the pristine vs default value. Would you set up a new issue on the problem, if it still exists? Loosing my overview powers on this issue ;-)
