### ISSUE TITLE
A non-required text input

### ISSUE THREAD

**Issue by sanemat** [christianalfoni/formsy-react#113]
I want to set a non-required text input.
A text which has 10 characters OR empty.
But I don't have this rule yet.
Is this expected behavior?

```jsx
// my code
<FormInput
   name="accessToken"
   validations={{
     matchRegexp: /^(?:[0-9a-zA-Z]{10})?$/
   }}
   validationError={{
     matchRegexp: "Just 10 characters"
   }} />

let FormInput = React.createClass({
  mixins: [Formsy.Mixin],
  changeValue(event) {
    this.setValue(event.currentTarget.value);
  },
  let errorMessage = this.getErrorMessage();
  render () {
    return (
      <div>
        <input
          type={this.props.type || 'text'}
          name={this.props.name}
          onChange={this.changeValue}
          value={this.getValue()} />
        <span>{errorMessage}</span>
      </div>
    );
  }
});

// Expected
'1234567890';//=> valid
'';//=> valid

// Actual
'1234567890';//=> valid
'';//=> invalid

// Another validations do same behavior
validations={{
  minLength: 10,
  maxLength: 10
}}
validationError={{
  minLength: "Just 10 characters",
  maxLength: "Just 10 characters"
}}

// Another validation brings another error (wrong api document?)
validations="isLength:10:10"
//=> Error: Formsy does not support multiple args on string validations. Use object format of validations instead.
```

formsy-react v0.13.0
react v0.13.2

Related:

[Default validation rules return false value when input value is empty · Issue #90 · christianalfoni/formsy-react](https://github.com/christianalfoni/formsy-react/issues/90)

My understanding:

`isDefaultRequiredValue`, `isEmail` and `isSpecialWords` support non-required text.
`matchRegexp`, `isAlpha`, `isWords`, `isLength`, `maxLength` and `minLength` don't support non-required text.
https://github.com/christianalfoni/formsy-react/blob/a7ac20ba41c7327aa5ca50abcf597ae09807e62f/src/validationRules.js

**Comment by Semigradsky** [comment]
Yeah, that looks as a bug.

```js
// Another validation brings another error (wrong api document?)
validations="isLength:10:10"
//=> Error: Formsy does not support multiple args on string validations. Use object format of validations instead.
```
Yes, it is not updated api. Now you should use `minLength` and `maxLength` validators.
I corrected it.

**Comment by christianalfoni** [comment]
@sanemat ,

Just want to make sure things are working for you after the latest release?

**Comment by sanemat** [comment]
@christianalfoni @Semigradsky `v0.13.1` works fine :smile:
Thanks!
