### ISSUE TITLE
Remove 'required' check from validations

### ISSUE THREAD

**Issue by Semigradsky** [christianalfoni/formsy-react#114]
Now many validations rules [required non-empty value](https://github.com/christianalfoni/formsy-react/blob/master/src/validationRules.js). But this creating some problems: #113 

`matchRegexp`, `isLength`, `maxLength`, `minLength` - all these rules should support empty string
`isNumeric` - should support zero

As a solution, we can create `isExisty` function for check that value not null or undefined. And use this function instead boolean type casting.

**Comment by Semigradsky** [comment]
Some questions:

Formsy has `hasValue` validation. But that is not documented in API
  - should pass with empty string?
  - should pass with zero?

**Comment by christianalfoni** [comment]
Good question!

Maybe just remove it. Formsy adds complexity allowing for any kind of form element, not just traditional inputs, so I think that is too generic.

Maybe change it out with the new "isExisty" function instead? And call is: "isExisty"? :-)

**Comment by Semigradsky** [comment]
Good, I added `isExisty` and updated api

**Comment by christianalfoni** [comment]
@Semigradsky Cool, nice! Will release new version with changes. 

Btw, I think it is easier to control releases if changes are pull requests. NPM and bower uses the tags and the current tag does not have isExisty in it, but people can read about it on the repo :-)

No biggy, but seems like a good way to do it?

**Comment by Semigradsky** [comment]
:+1:

**Comment by Semigradsky** [comment]
@christianalfoni I'm not well understood.
Do you want me to add new tag (0.13.2) to repo?
Or move changes (f168b53, 7ef6c51) to pull request?

**Comment by christianalfoni** [comment]
Lets add a new tag, just have to review pull requests etc. do document a new release. Will do that tomorrow :-)
