### ISSUE TITLE
Component.isFormDisabled throws error (add form controls in runtime)

### ISSUE THREAD

**Issue by mloginov** [christianalfoni/formsy-react#116]
Hi,

Problems appear when I add controls to the form in runtime. 

something like that

```js
_generateControls() {
  if (this.state.flag) {
    return (
              <Control1
                name='name1'
                required
                />
       )
  } else {
    return (
              <Control2
                name='name2'
                required
                />
       )
  }
}

render() {
  return (
        <Form
          disabled={this.state.disabled}
          >
             {this._generateControls()}
            <button 
                onClick={() => {
                       this.setState({flag: !this.state.flag})
                  }}
            />
        </Form>    
  )
}

```
Components uses ```disabled={this.isFormDisabled()}```

So in this case on button click formsy componentWillUpdate calls but it calls registerInputs with timeout and component render method calls before registering. And error in ```this.isFormDisabled()``` as result.

**Comment by christianalfoni** [comment]
Hi @mloginov ,

Identified problem, working on fix now, will probably be released later today. Thanks for reporting!

**Comment by christianalfoni** [comment]
Okay, released new version, please try again :-)

**Comment by mloginov** [comment]
Thanks! Will try.
