### ISSUE TITLE
Internal _value gets out of sync too easy

### ISSUE THREAD

**Issue by crdeutsch** [christianalfoni/formsy-react#118]
I've been updating a bunch of existing forms to use formsy and I keep having to work around the actual value of the input getting out of sync with the internal state value.

I don't like using the onChange event to run validation every time a key is pressed. I think that is too aggressive and a poor UX, so I'm opting to use onBlur instead like Issue #1 mentions.

But if you press "Enter" to submit the form the wrong value is validated because onBlur doesn't execute.

I worked around that by detecting Enter and calling setValue
```js
  _onKeyDown: function (event) {
    // if enter is pressed we need to set the value.
    if (event.keyCode === 13) {
      this.setValue(event.currentTarget.value);
    }
  }
```

Now I'm working around having a default value (similar to issue #11). I could add `componentWillReceiveProps` and `componentWillMount` but it seems like the code is really adding up just to support the internal `_value`.

I'm also worried, there will be more edge cases like screen readers or browser extensions (password managers) that will also get out of sync.

**Is there a reason why there even is an internal value other then being able to change the `isPristine` flag?**

I'm debating forking what you have and switching to using `getDOMNode().value` wherever value is referenced, but would value feedback before doing so.

**Comment by christianalfoni** [comment]
Hi @crdeutsch and so sorry for the late reply. I have been deep into a different project and have just been in loss of time.

It might seem a bit aggressive to do the validation on each key press, though as I understand it you mean that from a user experience perspective, not a technical perspective?

I would suggest that you add your own state to your form element. Something like, `showValidation`. That way you can choose with onBlur or Enter to set that state to true and combine it with the internal methods of Formsy. Like:

```js
var MyInput = React.createClass({
  mixins: [Formsy.Mixin],
  getInitialState: function () {
    return {
      showValidation: false
    },
    onInputChange: function (event) {
      this.setValue(event.target.value);
    },
    onInputBlur: function () {
      this.setState({
        showValidation: true
      });
    },
    onInputFocus: function () {
      this.setState({
        showValidation: false
      });
    },
    render: function () {
      return (
        <div>
          <input onChange={this.onInputChange} value={this.getValue()}/>
          <div>{this.showError() && this.state.showValidation ? this.getErrorMessage() : null}</div>
        </div>
      );
    }
  }
});
```
Would that make sense?

I do not think it is a good idea to grab value from DOM node as it breaks with the principles of React. The state of the component defines what is in the UI, not the other way around. I am sure we can find a solution for this :-)

Let me know if I misunderstood any needs and we can keep working towards a solution!

**Comment by crdeutsch** [comment]
No worries. 

Yes, I meant aggressive from a UX perspective.

I ended up forking it for my use case (didn't finish re-doing the tests yes, FYI, for anybody who finds it).
https://github.com/crdeutsch/formsy-react/commits/f9c1d418cea488e65b19a97e1ee6cc6c6d188193

I leave it up to the Component to implement a `getValue` function so you can chose whether using the Input's actual value as the "state" makes sense to you or not.

A simple example:
```
var TestInput = React.createClass({
  mixins: [Formsy.Mixin],
  render: function () {
    return <input {...this.props}/>
  },
  getValue: function() {
    return this.isMounted() ? this.getDOMNode().value : '';
  }
});
```

The addon class I use (defaults to Bootstrap styling):
https://gist.github.com/crdeutsch/f953400daae0a739659a

For my use case using the DOM node as the "source of truth" is the only option. I tried it the other way for over a day in a real world app and there were too many edge cases where the inputs would get out of sync or the error message is displayed at the wrong time.

Ideally I need a clean way to validate "on submit".  I went back and tried your example but it doesn't show the message if you submit a clean form with required fields. If I update it to handle that case, the error won't go away when I use "enter" to submit the form because the input doesn't blur. So I'd have to add more logic to check for keypresses and at that point it's just seems like way too much effort to duplicate the experience of validating "on submit".

As for it breaking the principles of React, the React team recognizes Input components are unique, which is why there is a `defaultValue` and not just a `value`
https://facebook.github.io/react/docs/forms.html#uncontrolled-components

Here's the Component I was trying to use:
https://gist.github.com/crdeutsch/490103d3610a5ce9f42d

The amount of logic vs my fork just keeps growing.

```
<Formsy.Form key="linkForm" onValidSubmit={self._onSubmit}>
  <Formsy.Input className="form-control"
                ref="url"
                name="url"
                type="text"
                placeholder="Enter Issue Url"
                validationErrors={{isRequired: "Url is required.", isUrl: "Url is not valid."}}
                validations="isRequired,isUrl" 
                />
  <div className="btn-groups">
    <button type="submit" className="btn btn-primary" ref="linkBtn">Create</button>
  </div>
</Formsy.Form>
```

**Comment by christianalfoni** [comment]
Hi again!

Hm, I am very certain that the DOM should not be the "source of truth". The component state should be the "source of truth". I can not quite wrap my head around how you get the inputs to go out of sync with the state of the component.

To solve this I think we need to set up a small project I can run locally to see the problem in context. I am sure there is a "component state way" to solve this :-)

I will close this for now since you solved it with a fork and I have not gotten feedback on this from anyone else, but please keep commenting if you want this put into Formsy. Thanks for contributing with the feedback and examples :-)
