### ISSUE TITLE
Validating on Component Mount

### ISSUE THREAD

**Issue by ppiekarczyk** [christianalfoni/formsy-react#122]
It would be great if I could directly access the `validate` method. I'm having an issue where I'm grabbing an email from a query string, but since validate is called `onChange` I'm not able to submit the form otherwise.

**Comment by Semigradsky** [comment]
You want check valid email or not?
You can use [`isValidValue` method](../blob/master/API.md#isvalidvalue) for this.

**Comment by christianalfoni** [comment]
I suppose this is solved?
