### ISSUE TITLE
What is your favorite react form implementation? 

### ISSUE THREAD

**Issue by luqin** [christianalfoni/formsy-react#123]
* [tcomb-form - UI library for developing forms writing less code](https://gcanti.github.io/tcomb-form)
[![NPM](https://nodei.co/npm/tcomb-form.png?downloads=true&stars=true)](https://nodei.co/npm/tcomb-form/)

* [react-forms - Forms library for React](https://github.com/prometheusresearch/react-forms)
[![NPM](https://nodei.co/npm/react-forms.png?downloads=true&stars=true)](https://nodei.co/npm/react-forms/)

* [newforms - Isomorphic form-handling for React](https://github.com/insin/newforms)
[![NPM](https://nodei.co/npm/newforms.png?downloads=true&stars=true)](https://nodei.co/npm/newforms/)

* [wingspan-forms - A dynamic form library for Facebook React](https://github.com/wingspan/wingspan-forms)

* [formjs - A form generator for Reactjs](https://github.com/zackify/formjs)
[![NPM](https://nodei.co/npm/formjs.png?downloads=true&stars=true)](https://nodei.co/npm/formjs/)

* [react-form-builder - A Form Builder for React.js](https://github.com/quri/react-form-builder)
[![NPM](https://nodei.co/npm/react-form-builder.png?downloads=true&stars=true)](https://nodei.co/npm/react-form-builder/)

* [plexus-form - A dynamic form component for react using JSON-Schema](https://github.com/AppliedMathematicsANU/plexus-form)
[![NPM](https://nodei.co/npm/plexus-form.png?downloads=true&stars=true)](https://nodei.co/npm/plexus-form/)

* [formsy-react - A form input builder and validator for React JS](https://github.com/christianalfoni/formsy-react)
[![NPM](https://nodei.co/npm/formsy-react.png?downloads=true&stars=true)](https://nodei.co/npm/formsy-react/)

* [rc-form-validation](https://github.com/react-component/form-validation)
[![rc-form-validation](https://nodei.co/npm/rc-form-validation.png?downloads=true)](https://npmjs.org/package/rc-form-validation)

[react-form-comparison](https://github.com/luqin/react-form-comparison)

**Comment by christianalfoni** [comment]
Thanks for including Formsy, great project btw :-)
