### ISSUE TITLE
Passing autocomplete attribute

### ISSUE THREAD

**Issue by joelmoss** [christianalfoni/formsy-react#124]
So it is not possible to pass `autocomplete` as a prop of `Form`, which I need. How can I do that?

**Comment by janmyler** [comment]
+1 for this. We should be able to pass props to `form` element, thinking of `autocomplete` and `novalidate` for example.

**Comment by christianalfoni** [comment]
Totally agree, will fix this for next release tomorrow.

**Comment by janmyler** [comment]
Thank you! :+1:
