### ISSUE TITLE
Running examples fails with jsx-loader error

### ISSUE THREAD

**Issue by iandanforth** [christianalfoni/formsy-react#127]
After following the install instructions you get this error.

ERROR in Entry module not found: Error: Cannot resolve module 'jsx-loader' in /home/idanforth/formsy-react

After running npm install jsx-loader

things appear to work without error

**Comment by Semigradsky** [comment]
Yeah dependency was be removed. I have changed it to babel-loader. https://github.com/christianalfoni/formsy-react/commit/cca4973382a6c85be4f4e1f844c656d67bc8ffa8 Now all should be fine.
