### ISSUE TITLE
isUrl not a valid validation rule?

### ISSUE THREAD

**Issue by arjunmehta** [christianalfoni/formsy-react#129]
Hi there! Using `formsy-react 0.13.1`. Awesome! Except a certain validation rule doesn't seem to work. (Maybe there are others?)

When I try to use the `"isUrl"` validation rule I get:
`Formsy does not have the validation rule: isUrl`

But I found your regex and used that with matchRegexp and it worked.

**Comment by Semigradsky** [comment]
This is not exist in this version. @christianalfoni can you bump version? Or add me as collaborator to npm and I will do it.

**Comment by arjunmehta** [comment]
Ah I see. That makes sense. I just assumed that since its in the docs it should be in the latest published package. :) it's good practice to move into a working branch and merge to master only when you publish to npm.

**Comment by christianalfoni** [comment]
Hi guys, version will be bumped tomorrow morning :-)
