### ISSUE TITLE
Wrong Component isValid state

### ISSUE THREAD

**Issue by mloginov** [christianalfoni/formsy-react#130]
Component did not update state if required field was changed in runtime.

Like that

```js
getInitialState() {
  return {isRequired: false}
}

onChange(val) {
  this.setState({isRequired: val})  //val === true
}

render() {
...
<MyComponent name='myC' required={this.state.isRequired}>
<Tooge onChange={this.onChange} value={this.state.isRequired} />
...
}
```

**Comment by christianalfoni** [comment]
This is not taken into account, but should. Might get into tomorrows release or most certainly the next after that :-)

**Comment by christianalfoni** [comment]
Okay, this is now fixed for next release. Both validations and required can be changed at runtime and instantly a new validation check will be run. Thanks for the tip!
