### ISSUE TITLE
Multiple errors per input

### ISSUE THREAD

**Issue by alexjg** [christianalfoni/formsy-react#131]
There can be more than one error for a given input, is there any way to represent this in formsy-react?

**Comment by christianalfoni** [comment]
Hi @alexjg,

Jup, from the API documentation:

```js
<MyInputComponent 
  name="email" 
  validations={{
    isEmail: true,
    maxLength: 50
  }} 
  validationErrors={{
    isEmail: 'You have to type valid email',
    maxLength: 'You can not type in more than 50 characters'
  }}
/>
```
That solved it?

**Comment by alexjg** [comment]
I probably wasn't very clear there, what I mean is that you can have multiple errors at the same time. For example if an input is both too long and not a valid email address, currently the getErrorMessages method returns a string, which makes it impossible to do something like rendering a list of errors under the input. 

Ideally I would like to be able to do something like this:

```coffee
render: ->
    <input type="text" ...>
    <ul>
            {@getErrorMessages().map(error -> <li>{message}</li>)}
    </ul>
```

My use case for this is actually when returning errors from server side validation so I would also need a way to set multiple errors on an input, so something like 

```coffee
updateInputsWithErrors(fieldname: ["error1", "error2"])
```

I'm happy to have a shot at implementing this if it's something you think would be worth having.

**Comment by christianalfoni** [comment]
Ah, sorry @alexjg , now I understand.

Yes, this should absolutely be in there. It would be great if you created a pull. I am releasing a new version today, but this would indeed be welcomed in the next release!

**Comment by christianalfoni** [comment]
Okay, this is now in for next release. Thanks for contributing!

**Comment by arismarko** [comment]
Hi Cristian,

Is it possible to have two custom validations in the same field


    let validations = {
      customValidation1: true,
      customValidation2: true
    };

    let errors = {
      customValidation1: 'Message for first custom',
      customValidation2: 'Message for second custom'
    };
