### ISSUE TITLE
Sometimes getting a SyntheticEvent as currentValues in formChange

### ISSUE THREAD

**Issue by ntucker** [christianalfoni/formsy-react#132]
Just started trying version 0.14, and formChange handler is not functioning properly. It sometimes takes normal events instead of the model. Maybe you are passing the onChange prop to the children?

**Comment by christianalfoni** [comment]
Ah, I know whats wrong. Its the passing of props to to the form element. It seems that a native form also has an onChange. Will revert back to strict control of props passed. Will release fix now :-)

**Comment by christianalfoni** [comment]
Try now

**Comment by ntucker** [comment]
Yup, that's fixed now, thx :)
