### ISSUE TITLE
PureRenderMixin does not work on Formsy managed components

### ISSUE THREAD

**Issue by davidtinker** [christianalfoni/formsy-react#134]
The shouldComponentUpdate method always finds a difference between this.props and nextProps on the '_isValidValue' key. This is a function that changes whenever Formsy.Form renders which happens whenever any Formsy managed component on the form updates. The net result is that all components on the form re-render every time a key is typed in an input field (for example).

If the form includes some expensive components then this is slow. The workaround is to extract the expensive stuff out into subcomponents (not managed by Formsy) and use PureRenderMixin there. But all Formsy forms would perform better if this was fixed.

**Comment by davidtinker** [comment]
Tx for making this excellent library available to everyone.

**Comment by davidtinker** [comment]
Alternate workaround is to use a PureRenderMixin that ignores _isValidValue in props:

```javascript
/**
 * Same as React's PureRenderMixin but excludes _isValidValue from the props comparison to workaround this issue:
 * https://github.com/christianalfoni/formsy-react/issues/134
 */
var PureRenderMixin = {
    shouldComponentUpdate: function(nextProps, nextState) {
        return !shallowEqual(this.props, nextProps, '_isValidValue') ||
            !shallowEqual(this.state, nextState);
    }
};

module.exports = PureRenderMixin;

function shallowEqual(objA, objB, ignoreKey) {
    if (objA === objB) {
        return true;
    }
    var key;
    // Test for A's keys different from B.
    for (key in objA) {
        if (objA.hasOwnProperty(key) && (!objB.hasOwnProperty(key) || objA[key] !== objB[key])) {
            if (!ignoreKey || ignoreKey != key) return false;
        }
    }
    // Test for B's keys missing from A.
    for (key in objB) {
        if (objB.hasOwnProperty(key) && !objA.hasOwnProperty(key)) {
            if (!ignoreKey || ignoreKey != key) return false;
        }
    }
    return true;
}
```

**Comment by christianalfoni** [comment]
Hi @davidtinker and thanks for looking into this :-)

I think the best solution is to make the function referenced, instead of creating it each time (inside formsy source code). That way the diff check will not see them as different values and you do not have to do anything about it :-)

I have changed this now, so it should be okay. Let me know if you see something I do not see!

**Comment by Zephir77167** [comment]
Hello, how is one supposed to display error and required messages using showError() and showRequired() (using the HOC) when also using the pure-render-mixin ? Those functions depend on context therefore the components don't update. Thanks in advance for the insight.
