### ISSUE TITLE
how not validate fields that are empty and not required ?

### ISSUE THREAD

**Issue by Nicolab** [christianalfoni/formsy-react#135]
Hello,

how not validate fields that are empty and not required ?

Expected behavior:

```js
// valid
<MyInput
  type="some"
  name="some"
  value=""
  validations="minLength:4"
  validationError="Min length error message"
/>
```

```js
// invalid
<MyInput
  type="some"
  name="some"
  value="ab" // <= value is invalid
  validations="minLength:4"
  validationError="Min length error message"
/>
```

```js
// valid
<MyInput
  type="some"
  name="some"
  value="abcd" // <= value is valid
  validations="minLength:4"
  validationError="Min length error message"
/>
```

```js
// invalid
<MyInput
  type="some"
  name="some"
  required // <= is required
  value="" // <= and empty
  validations="minLength:4"
  validationError="Min length error message"
/>
```

Thanks for Formsy, it is nice to use :)

**Comment by Semigradsky** [comment]
It seems the best solution is to [create your own rule for this](../blob/master/API.md#formsyaddvalidationrulename-rulefunc).

**Comment by Nicolab** [comment]
Thank you for your reply.
If I do it this way, I lose the interest of generic validators :(

There must be another way, a hook or other ?

**Comment by Semigradsky** [comment]
@Nicolab You want something like this?
```js
var rules = Formsy.validators();

Formsy.addValidationRule('minLengthOrEmpty', function (values, value) {
  return rules.isEmptyString(values, value) || rules.minLength(values, value);
});
```

**Comment by ppiekarczyk** [comment]
:+1: where I can ignore validating inputs that are not required until the user engages the input.

**Comment by Nicolab** [comment]
@Semigradsky it's a solution :) 
The ideal would be to avoid creating duplicate rules for the same thing.

If a field is not required and empty, needless to validate given that the field is optional (so, is a valid value).

**Comment by renak** [comment]
It looks like this issue was addressed before and implemented into the module: https://github.com/christianalfoni/formsy-react/issues/90

Maybe there's a bug preventing it from working again now?

I'm using the Form's onValid/onInvalid to enable/disable the submit button. Unfortunately, the button gets disabled when a non-required input is empty because it triggers invalid. I'm hoping we can get a fix for this soon.

**Comment by Semigradsky** [comment]
> If a field is not required and empty, needless to validate given that the field is optional (so, is a valid value).

Now I understand, that is really problem.

**Comment by Nicolab** [comment]
Excellent, thanks !

**Comment by renak** [comment]
Will this change be released soon? Or is there another stable version that had this working before that I could use for now?
