### ISSUE TITLE
Check form validity on componentWillReceiveProps

### ISSUE THREAD

**Issue by iandeherdt** [christianalfoni/formsy-react#136]
Hello

I've created a component that has a dynamic list of items. You can add or remove items via a dispatch action which in turn goes to a form store and delivers the new state to the component that contains a formsy form with the dynamic list. The value of the dynamic list is set via the newly received state of the form store. The value of the list is updated correcty, but the validation is never triggered because i don't use the setValue function. Is there a way i can force the form to validate on componentWillReceiveProps or any alternative?

Thanks in advance

Ian

**Comment by mindcruzer** [comment]
I'm also in need of this. If you try to force re-validation in `componentWillReceiveProps` with `this.props._validate(this);` it causes an infinite loop.

**Comment by christianalfoni** [comment]
Hi guys,

Hm, do you have a small code example? Currently the mixin for elements checks if the value of the element has changed, and if so, it will run "setValue"... also running the validation. I am a bit unsure where this list state is being used?

**Comment by christianalfoni** [comment]
Closing old issue
