### ISSUE TITLE
Shouldn't the form be valid in this case?

### ISSUE THREAD

**Issue by jswxwxf** [christianalfoni/formsy-react#137]
Hi Christian,

How are you doing? I'm using your excellent validate framework in my project. Great Job. :)
Here's my question.
If I have a input field which is not required in a form and keep it empty.
And I've filled in all of other required input fields.
What is the form's valid value in this case?
I've tried, it's false and hence the submit button is disabled.
Shouldn't the form be valid at this moment? Since the empty form field is not required.

Thanks,
Jeffrey

**Comment by jswxwxf** [comment]
I'm thinking that maybe we should check the isRequired when validateForm.

// We need a callback as we are validating all inputs again. This will
    // run when the last component has set its state
    var onValidationComplete = function () {
      inputKeys.forEach(function (name) {
        if (!inputs[name].state._isValid) {    // **should check isRequired also.**
          allIsValid = false;
        }
      }.bind(this));

      this.setState({
        isValid: allIsValid
      });

      if (allIsValid) {
        this.props.onValid();
      } else {
        this.props.onInvalid();
      }

      // Tell the form that it can start to trigger change events
      this.setState({
        canChange: true
      });

    }.bind(this);

**Comment by Semigradsky** [comment]
@jswxwxf I tried to get your result, but I did not succeed.
I changed a little [login example](../blob/master/examples/login/app.js). I removed `required` rule from password field. And submit button is shown when filling correct value to email field.

Could you give more details?

**Comment by jswxwxf** [comment]
You're right.
Sorry my bad. I just tried and it works as expected. :)
