### ISSUE TITLE
Validate email after blur

### ISSUE THREAD

**Issue by poluyanov** [christianalfoni/formsy-react#139]
Hi!
Is there best way to run validate input after blur in some cases?
Or validation runs strictly after onChange?

**Comment by Semigradsky** [comment]
You can [pre-verify value](../blob/master/API.md#isvalidvalue) or trigger validation (`this.setValue(this.getValue());`) in your `onBlur` handler.

**Comment by christianalfoni** [comment]
Yup, would suggest setting the value on the blur event, instead of the change event. 

```js
var Comp = React.createClass({
  mixins: [Formsy.Mixin],
  onInputBlur: function (event) {
    this.setValue(event.target,value);
  },
  render: function () {
    return <input onBlur={this.onInputBlur}/>
  }
});
```
Closing this as it seems to be solved?

**Comment by salayev** [comment]
What if originally i have a value for the input how would i add it to the input and keep it editable without change event with setValue()?

**Comment by silvenon** [comment]
The tricky thing here is that you can no longer modify the field after the blur. You have to also `setState` `onChange`.

**Comment by horikx** [comment]
I just inserted an initialBlur flag which was set to true on first blur then checked if initialBlur was true before executing this.getErrorMessage() in render.

**Comment by christianalfoni** [comment]
Got this example from someone too: https://github.com/christianalfoni/formsy-react/wiki/validate-on-blur

When next release is out we should start the work on some "default elements", where this validate on blur input could be one of them :-)
