### ISSUE TITLE
Combined input support

### ISSUE THREAD

**Issue by endragor** [christianalfoni/formsy-react#140]
I'm implementing `DateTimeInput` component. Logically and visually it's a combination of `DateInput` and 
`TimeInput` components. So, naturally, I was going to do something like this:
```jsx
render() {
  return (
    <div>
      <DateInput name={this.props.name + '-date'} ref="date"/>
      <TimeInput name={this.props.name + '-time'} ref="time"/>
    </div>
  );
}
```
(plus there is logic to update value of the parent input whenever nested inputs change)

However, currently such use case is not supported, because `traverseChildrenAndRegisterInputs` in `Mixin.js` stops recursion whenever it meets a component with `name` property set.
Perhaps fixing it to continue further would be enough, but I'm not sure if it might bring other side effects.

**Comment by christianalfoni** [comment]
Hi @endragor ,

There are two ways to fix this. Either you make pure versions of DateInput and TimeInput, which is not Formsy related. Then you create a small wrapper for DateInput and TimeInput, which uses the mixin. That leaves you open to create a DateTimeInput, using the pure DateInput and TimeInput and exposing its name: "dateAndTime" or whatever... does that make sense?

In the next version of Formsy the `traverseChildrenAndRegisterInputs` will not be used. It will use context instead, which means that this should probably work.

Keep an eye out for the preview and we can try it out :-)

**Comment by christianalfoni** [comment]
Closing old issue
