### ISSUE TITLE
The logic around validations on optional fields seems counter-intuitive to me. Is it right?

### ISSUE THREAD

**Issue by anavarro9731** [christianalfoni/formsy-react#141]
this line in the runValidation function (currently 285)
     isValid: isRequired ? false : isValid,
seems to me to make more sense if it were
      isValid: isRequired ? isValid : true,
so that we only run validations on fields that are required and the user has entered something.
Any reason it is the way it is?
There would likely require changes to the error message function as well if this logic were to change.

**Comment by anavarro9731** [comment]
Right now I am having to create loads of custom validations to support both the required and optional scenario. Take for example the maxLength validation. I can't use that when the field is optional. I am creating a maxLengthOnOptionalField validator. I'd much rather do " required validations="maxLength:50" "and have that run only when the users has put something in the field. And while maxLength works fine for required fields it kind of makes the required attribute redundant since maxLength implicitly requires a value

**Comment by Semigradsky** [comment]
> Take for example the maxLength validation. I can't use that when the field is optional.

That was fixed in #138 
But the new version is not yet published

**Comment by anavarro9731** [comment]
Yeah great, I found the logic up above doesn't actually work anyway.
