### ISSUE TITLE
Way to access all Formsy enabled children?

### ISSUE THREAD

**Issue by eventhough** [christianalfoni/formsy-react#143]
I'm trying to build a re-usable form component that looks something like this:
```javascript
// MyForm:
<Formsy.Form>
  { this.props.children }
  <button>Save</button>
</Formsy.Form>
```
Then I can essentially re-use this form container over and over:
```javascript
// SomeRandomForm:
<MyForm>
  <MyInput type='text' name='name' />
  <div className='foobar'>
      <MyInput type='text' name='pet' />
  </div>
</MyForm>

// it would be nice if we could access all the children form inputs from the parent container
```
I want to be able to re-use control elements like Save/Cancel buttons which show up for every single form.

Is there a way to access Formsy enabled children from a container form?

**Comment by ericdfields** [comment]
I think [refs](https://facebook.github.io/react/docs/more-about-refs.html) will help you out.

**Comment by christianalfoni** [comment]
Hi there,

The next version should allow you to do this as it uses context instead of props. I will soon give some information on how to try out the new version which requires React 0.14. Stay tuned :-)

**Comment by eventhough** [comment]
Awesome! Being able to iterate across all the form inputs would be really useful if we want to build a re-usable form container. There's no way right now for us to iterate across all the child inputs without knowing exactly which refs to use.

**Comment by christianalfoni** [comment]
Check out this issue: https://github.com/christianalfoni/formsy-react/issues/158 :-)
