### ISSUE TITLE
Multiple Submit Buttons?

### ISSUE THREAD

**Issue by aphillipo** [christianalfoni/formsy-react#145]
Hello Formsy React/Christian,

Can we do the following:
```js
<button type="submit" name="save" value="save-and-continue" className="btn btn-default save-and-continue" disabled={!this.state.canSubmit}>
    {loadingIcon}
    Save &amp; Continue
</button>

<button type="submit" name="save" value="save-and-add" className="btn btn-default save-and-add" disabled={!this.state.canSubmit}>
     {loadingIcon}
     Save &amp; Add Another
</button>

 <button type="submit" name="save" value="save-and-return" className="btn btn-primary save-and-return" disabled={!this.state.canSubmit}>
    {loadingIcon}
    Save &amp; Return to List
</button>
```

Only the value that was clicked would be passed through in the model onSubmit so if the second button above was clicked we'd get {save: 'save-and-add'} in our form data?

What do you think?  Useful?

**Comment by Semigradsky** [comment]
I think it makes sense

**Comment by christianalfoni** [comment]
Hi there!

You can solve this by manually submitting the form :-)

Quick example:

```js
onSubmit: function (model) {
  if (this.state.typeOfSubmit === 'oneOfThem') {
    // doe something
  }
},
submit1: function () {
  this.setState({
    typeOfSubmit: 'oneOfThem'
  }, this.refs.form.submit);
},
submit2: function () {
  this.setState({
    typeOfSubmit: 'theOther'
  }, this.refs.form.submit);
},
render: function () {
  return (
    <Formsy.Form onSubmit={this.onSubmit} ref="form">
      <button onClick={this.submit1}>Submit1</button>
      <button onClick={this.submit2}>Submit2</button>
    </Formsy.Form>
  );
}

```

**Comment by aphillipo** [comment]
Yeah it's okay.  Would be nicer, obviously, if this was automatic.  What I do now is set an onClick event to update a temporary value on the class (i.e. onClick: function(e) { this.saveButton = e.currentTarget.innerText; }).

I then test for and reset this.saveButton in my submit method.

Thanks for Formsy it's excellent; probably one of the best and most stable react components/libraries.

**Comment by christianalfoni** [comment]
@aphillipo Yeah, I see your point on it being automatic :-) But I think the stability of Formsy is due to all these "special scenarios" not being implemented, rather have good enough hooks to solve anything. There are so many suggestions and if all of them were implemented it would be very hard to document it all and keeping it stable :-)

Thanks for the feedback!

**Comment by nye** [comment]
@christianalfoni  But now you don't have a submit button, so you can't submit on press enter key?
