### ISSUE TITLE
server-side exception handling

### ISSUE THREAD

**Issue by mschipperheyn** [christianalfoni/formsy-react#15]
When I submit a form to the server and it generates an exception, I would like to map the errors array that comes back to visual feedback on the form with the appriopriate error message that is passed also in the returned exception array.

I would like to do this through a generic mixin so I don't have to hand code anything at the form level.

Any suggestions on this?

**Comment by cmwelsh** [comment]
Rails uses a hard-coded key `base` as the attribute to use for form-level (many fields involved or non-field-specific) errors. That way the client knows to place the error at the top of the form, not associated with a specific field. Is that sort of what you mean?

**Comment by christianalfoni** [comment]
Hi guys,

We have this practice now:

```javascript
var Comp = React.createClass({
  render: function () {
    return <form onSubmit={this.onSubmit}/>
  }
});
```

**Comment by christianalfoni** [comment]
Hi guys,

We have this API now:

```javascript
var Comp = React.createClass({
  onSubmit: function (data, resetForm, invalidateForm) {
     myAjaxService('/url', data)
      .error(function (errors) {
        errors // { test: "Not valid input says the server" }
        invalidateForm(errors);
      }); 
  }, 
  render: function () {
    return (
      <Formsy.Form onSubmit={this.onSubmit}>
        <MyInput name="test"/>
      </Formsy.Form>
    );
  }
});
```

You could basically do whatever you want when server responds, but to map to inputs you use the "invalidateForm" callback.

Does that solve it? Maybe the documentation is lacking a bit here?

**Comment by drewhamlett** [comment]
Is it possible to do ajax validation with the Formsy.addValidationRule API?

**Comment by christianalfoni** [comment]
Hi @drewhamlett !

Do you want to validate the form values before they are passed to the server? Or do you want to validate values passed from server before they are put into the form?

Well... basically, do you want something like: `Formsy.validate(myValue, 'isEmail')` ? :-)

**Comment by drewhamlett** [comment]
Something like.  Thanks for your help!

```js
Formsy.addValidationRule('isValidUPC', function (value) {

  $.post('/api/validate/upc.json', {
    value: value
  }, function (data) {
    if (!data.isValid) {
      return Promise.resolve(true);
    }

    return Promise.reject();
  });
});

```

**Comment by christianalfoni** [comment]
Hi again :-)

That is good to hear!

Aha, of course, now I understand. In theory this should work just fine, just have to implement promises support. The only restriction I see is that you might get into trouble if you run it a lot. You could add a debounce thingy around it though. Hm hm...

Let me think about it and try it out, I think it should be good. It is a good idea :-)

**Comment by drewhamlett** [comment]
Ok cool thanks.  That would be awesome.

**Comment by christianalfoni** [comment]
Okay, so I thought about it some more. It adds a lot of complexity and it is an edge case. Is is even valid to ask the question if this really is the responsibility of Formsy.

I would suggest using a "required" on this form element and to the ajax stuff inside it. Only if you get a valid value back from your ajax request you actually set the value, `setValue()`, which will fulfill the "required" and make the form element valid.

Does that make sense?

**Comment by christianalfoni** [comment]
Just closing this as it is getting old
