### ISSUE TITLE
Formsy causing other buttons to submit?

### ISSUE THREAD

**Issue by e-monson** [christianalfoni/formsy-react#150]
I don't know if this is really Formsy's fault, but I was hoping someone could point me in the right direction. I have a Formsy form that includes [react-md-editor](https://github.com/JedWatson/react-md-editor) as one of its fields. The problem is that, if all the required fields are filled out and the submit button is enabled, the editing buttons on the Markdown editor also act as submit buttons, ruining the functionality of the editor.  Any ideas as to what could be causing this?

**Comment by Semigradsky** [comment]
How about run stopPropagation submit event in your field?

**Comment by e-monson** [comment]
Unfortunately, I just tried that, and it didn't work. Not even nativeEvent.stopImmediatePropagation works. I wonder if it's related to https://github.com/facebook/react/issues/1691.

**Comment by e-monson** [comment]
I was able to solve the problem by drilling down to the buttons themselves with document.getElementsByClassName and adding a click event listener calling e.preventDefault. Whew!

**Comment by wingleungchoi** [comment]
button without type-attributes; Formsy.Form will treat those buttons as submit buttons
adding  type='button'  can prevent this issue happen
```
 e.g. <button type='button' onClick={this.foo)}>foo</button>
```
