### ISSUE TITLE
Slow performance with lot of inputs

### ISSUE THREAD

**Issue by Ezekiah** [christianalfoni/formsy-react#154]
Hello,

I made a form with 50 inputs and I can see latency when I write inside the inputs/ On the computer it becomes slow and on mobile really slow, should I divide the form, because I don't think there is a solution to reduce the latency ? I didn't add extra function which could increase latency.

Thanks

**Comment by Semigradsky** [comment]
Thanks for the issue. We will check the performance.

**Comment by Semigradsky** [comment]
Are you trying use [`pure-render-mixin`](https://facebook.github.io/react/docs/pure-render-mixin.html) in your inputs?

**Comment by Ezekiah** [comment]
Thank you, I just tested with pure-render-mixin as you proposed and the speed is better, but still slow on mobile.

**Comment by Semigradsky** [comment]
Could you provide some of your code? So we might better understand where the bottleneck :snail:

**Comment by Ezekiah** [comment]
Here this is my input classe : 


        import React from "react/addons";
	import AppFormsMixin from "./app_form_mixin";
	import Formsy from "formsy-react";
	
	import {Alert, Col, Row} from "react-bootstrap";
	import {Button} from "react-bootstrap";
	import {Input} from "react-bootstrap";
	import {Glyphicon} from "react-bootstrap";
	import {OverlayTrigger} from "react-bootstrap";
	import {Popover} from "react-bootstrap";
	var PureRenderMixin = require('react/addons').addons.PureRenderMixin;
	
	
	var CsInput = React.createClass({
	
		// Add the Formsy Mixin
		mixins: [Formsy.Mixin, PureRenderMixin],
		
		getInitialState() {
			return {
				bsStyle:'default', 
	
			};
		},
		
		triggerErrorInput() {
			this.setState({
				bsStyle:'error'
			});
		},
		
		setErrorMessage(error) {
			this.setState({
				serverError:error
			});
		},
	
		// setValue() will set the value of the component, which in 
		// turn will validate it and the rest of the form
		changeValue(event) {
			this.setValue(event.currentTarget.value);
			
			if( this.props.onChange2 )
				this.props.onChange2();
			
			if(this.isValidValue(event.target.value))  {
				this.setState({
					bsStyle: "success",
					serverError:''
				});
				
			} else {
				this.setState({
					bsStyle: "error",
					serverError:''
				});
			}
			
		},
	
		getDataId() {
	
			return $(React.findDOMNode(this.refs.input)).find('input').dataset;
	
		},
	
		render() {
	
			
			var cx = React.addons.classSet;
			var className = cx({
				'form-group':true,
				'required': this.showRequired(),
				'has-error': this.showError(),
			});
	
			// Set a specific className based on the validation
			// state of this component. showRequired() is true 
			// when the value is empty and the required prop is 
			// passed to the input. showError() is true when the 
			// value typed is invalid
			//var className = this.showRequired() ? 'required' : this.showError() ? 'error' : null;
	
			// An error message is returned ONLY if the component is invalid
			// or the server has returned an error message
			var errorMessage = this.getErrorMessage();
	
			var inputId='input'+this.props.id;
			
				
			return (
					
					<div className={className}>
						
						
						<Input {...this.props}
							ref="input" 
							data-id={this.props.dataId} 
							id={inputId}
							label={this.props.label} 
							onChange={this.changeValue}
							value={this.getValue()}
							bsStyle={this.state.bsStyle}
							groupClassName='group-class'
						    labelClassName='label-class'
							hasFeedback
							help={this.props.popoverContent}
							>
							
							
							<span className="text-danger"><b>{this.state.serverError}{errorMessage}</b></span>
							
						</Input>
						
				
						
	
							
				
						
					</div>
	
	
	
			);
		}
	});
	
	
	export default CsInput;
	
	
	
	

And here I call the class :


    var config_params = this.props.config[0].params.map(function(param,index) {
				var id = param.label+param.id



				return (

						<div>
							<CsInput type='text' label={param.label}
								id={id} value={param.value} name={param.label}
						
								dataId={param.id} data-label={param.label} data-value={param.value}
								required
								validations={{matchRegexp: /^([A-Za-z0-9]{1,30})$/}}
								validationError='Les caractères spéciaux ne sont pas autorisés'

							/>


						</div>
				);

				i = i+1;
			});


I notice that each time i write something in an input, all cs_inputs are re rendered, but I think it's normal, thanks to pureRenderMixin ProductConfigForm doesn't update when I change an input.

**Comment by Ezekiah** [comment]
Hmm I think my cs_input class is a mess, I should optimize it.

**Comment by Ezekiah** [comment]
I made a test by commenting this.validateForm  [here]  (https://github.com/christianalfoni/formsy-react/blob/4279dd59a20fd0b27690e0dd38569f63ee775914/src/main.js#L261) and it became perfectly fast but that's not surprising, maybe launching regex validations on 50 inputs eat performance.

**Comment by charosez** [comment]
Purerendermixin currently doesn't work with Formsy as discussed here: 
https://github.com/christianalfoni/formsy-react/issues/134
(The solution is also provided in the discussion) 

I've created a patch with the solution proposed by christianalfoni: 
https://www.npmjs.com/package/formsy-react-patch

**Comment by christianalfoni** [comment]
Hi guys,

Yes, the fix is not part of the current release, but the next one. It is right around the corner :-)

**Comment by vikasrohit** [comment]
Thanks @charles-tai for the patch.
@christianalfoni I am not able to see the changes yet in latest release. Are you planning to have it in latest one?
