### ISSUE TITLE
Move from mixin to higher-order-component

### ISSUE THREAD

**Issue by benjamindulau** [christianalfoni/formsy-react#157]
Do you have some plan for getting rid of the mixin since mixins are likely to disappear in the future or React?

You could implement the higher-order-component pattern instead: https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750

**Comment by Semigradsky** [comment]
Yeah, higher-order-component and decorator should be implemented.
Example of realizing: https://github.com/Yomguithereal/baobab-react/tree/master/src

**Comment by christianalfoni** [comment]
Hi, yeah, I agree... lets make this part of next release.

**Comment by christianalfoni** [comment]
Here is a code snippet from a different project, it supports both decorator and HOC: 

```js
  "use strict";

var mixin = require('./mixin.js');
var utils = require('./utils.js');
var React = require('react');

module.exports = function() {

  var createWrapper = function(Component, state) {
    var DecoratorWrapper = React.createClass({
      mixins: [mixin],
      getCerebralState: function() {
        return state;
      },
      componentWillMount: function() {
        Component.prototype.signals = this.signals;
        Component.prototype.recorder = this.recorder;
      },
      render: function() {
        return React.createElement(Component, utils.extend({}, this.props, this.state));
      }
    });
    return DecoratorWrapper;
  };

  if (arguments.length === 2 && typeof arguments[0] === 'function') {
    return createWrapper(arguments[0], arguments[1]);
  } else {
    var state = arguments[0] || {};
    return function(Component) {
      return createWrapper(Component, state);
    };
  }
};
```

**Comment by Semigradsky** [comment]
It is necessary to check, perhaps you can just use https://github.com/brigand/react-mixin?

**Comment by christianalfoni** [comment]
Okay, got Mixin, HOC and Decorator in the new branch now. Using a traditional approach from other projects.
