### ISSUE TITLE
Formsy.Mixin: props name="objectA.keyB" does not produce { ObjectA: {keyB:"value"} }

### ISSUE THREAD

**Issue by ajaykurien** [christianalfoni/formsy-react#159]
The documentation at https://github.com/christianalfoni/formsy-react/blob/master/API.md#name suggests that 

```html
<MyInputComponent name="email"/>
<MyInputComponent name="address.street"/>
```
should generate a "form model" with a nested object. `{email: 'value', address: {street: 'value'}}`.

But when using formsy-react 0.14.1 and react 0.13.3:
```html
<Input
  name="textA.A"
  value=""
  label="Text"
  type="text"
  placeholder="Here is a text input."
  help="This is a required text input."
  required
/>
<Input
  name="TextB.B"
  value=""
  label="Text"
  type="text"
  placeholder="Here is a text input."
  help="This is a required text input."
  required
/>
```
produces the following in the console:

![screen shot 2015-07-09 at 17 21 37](https://cloud.githubusercontent.com/assets/10114803/8600666/fd5eb226-265e-11e5-86a9-1f5376d093fa.png)

i.e. values for individual ```A``` and ```B``` (zero-length string in this example) but not ```textA.A``` or ```TextB.B```.

I'd appreciate some guidance. A workaround seems to be to use mapping, but that will get unwieldy quickly.

Thanks!

**Comment by adamalbrecht** [comment]
+1 just ran into this

**Comment by Semigradsky** [comment]
Hi, that is fixed in new version #158

**Comment by ajaykurien** [comment]
Thanks @Semigradsky, and to @christianalfoni for a superb library.

@adamalbrecht, a short term workaround courtesy of @garbin, detailed at https://github.com/christianalfoni/formsy-react/pull/153/files

**src/main.js**:

```js
mapModel: function () {
    if (this.props.mapping) {
      return this.props.mapping(this.model)
    } else {
      return Object.keys(this.model).reduce(function (mappedModel, key) {
        
        var keyArray = key.split('.');
        var base = mappedModel;
        while (keyArray.length) {
          var currentKey = keyArray.shift();
          base = (base[currentKey] = keyArray.length ? base[currentKey] || {} : this.model[key]);
        }

        return mappedModel;

      }.bind(this), {});
    }
  },
```

**Comment by christianalfoni** [comment]
Will close this as it is fixed in new version coming soon, thanks for the feedback @ajaykurien :-)

**Comment by jaraquistain** [comment]
@christianalfoni Any idea when the next version containing this fix will be released?

**Comment by christianalfoni** [comment]
Release Candidate out now on React, right around the corner :-) Took a bit longer than I thought, but now it is really close!
