### ISSUE TITLE
How to clean/preprocess input before validating?

### ISSUE THREAD

**Issue by sloria** [christianalfoni/formsy-react#161]
I would like to preprocess user input before it gets validated. For example, I have a text field that must be a URL, but I want to allow the user to omit `http://` or `https://` at the beginning of their input. If the HTTP scheme is omitted, `http://` should automatically be prepended (on blur) before the field gets validated.

How can I achieve this with formsy-react?

**Comment by idream3** [comment]
Here is one solution:

Add your own URL validation rule and sanitize your input there.
https://github.com/christianalfoni/formsy-react/blob/master/API.md#formsyaddvalidationrule

There might be a way to run the bundled URL validator within your new validator but not sure if you can access it in the current API.  Composing validators would be an interesting concept.

**Comment by sloria** [comment]
Thanks for the response @idream3 . That could work, but I'd like to display the sanitized value on blur. I'm not sure that there is a way to modify the value within a validator.

**Comment by twisty** [comment]
You could just modify the user input before passing it to `setValue`. Presumably you're calling `setValue` in an `onBlur` callback? Something like:

```javascript
var Url = React.createClass({

    mixins: [Formsy.Mixin],

    onChange(e) {
        this.setState({displayValue: e.currentTarget.value});
    },

    onBlur(e) {
        var value = e.currentTarget.value;
        if (value.indexOf('http://') !== 0) {
            value = 'http://' + value;
        }
        this.setState({displayValue: value});
        this.setValue(value);
    },

    render() {
        return (
            <div>
                <input
                    type="text"
                    value={this.state.displayValue}
                    onChange={this.onChange}
                    onBlur={this.onBlur}
                />
            </div>
        );
    }

});
```

**Comment by christianalfoni** [comment]
It seems that this is solved? Closing it, thanks for suggestions and hope you got it fixed @sloria!
