### ISSUE TITLE
required="true" / required="false" ?

### ISSUE THREAD

**Issue by Nicolab** [christianalfoni/formsy-react#163]
Hello,

It's possible to make a field required or not, depending of its value. 

Example: 

The field is required, so the validations are executed:
```
required="true"
```

The field is not required, so the validations are executed only if the field is not empty:
```
required="false"
```

**Comment by silvenon** [comment]
I was wondering about this as well. When I don't use `required`, the validations are executed immediately.

**Comment by benjamindulau** [comment]
This seems to be fixed in mater by https://github.com/christianalfoni/formsy-react/pull/138
Can we expect a new version to be published soon? ;-)

**Comment by Nicolab** [comment]
The fix #138 does not provide this behavior. If `required="false"` is used then an error is thrown (because false validator doesn't exist)

**Comment by christianalfoni** [comment]
Hi there,

The `required` prop can take a validation value, just like `validations`. This is to define what validation rule should define the input as required. By default that is `required="isDefaultRequiredValue"`, which checks if the value is undefined or an empty string. But you can change this to `required="isFalse"`. If the value now becomes `false` it will be indicated as required.

Does that make sense? validations and required is hard to express in a good way :-/

**Comment by silvenon** [comment]
> The fix #138 does not provide this behavior. If `required="false"` is used then an error is thrown (because false validator doesn't exist)

I'm using `required="false"` and it works as expected. Maybe it got fixed since you tried it.

**Comment by christianalfoni** [comment]
Closing this as it does work, reopen if still having problems

**Comment by Nicolab** [comment]
Hello,

thanks for the replies and explanation (sorry for my late response).

> I'm using required="false" and it works as expected. Maybe it got fixed since you tried it.

```
required="false"
validations="minLength:2"
```

Thrown `Error: Formsy does not have the validation rule: false`

And
```
required={false}
validations="minLength:2"
```

`minLength` is called

**Comment by silvenon** [comment]
JSFiddle?

**Comment by varzock** [comment]
I'm reporting the same issue (v. 0.14.1) as Nicolab. It's very irritating. Hope it gets fixed soon.

**Comment by silvenon** [comment]
Oh, I see the issue. In case it's not clear to @christianalfoni, they're looking for a way to do this:

```jsx
const App = React.createClass({
  getInitialState() {
    return { isRequired: false }
  },
  someMethod() {
    this.setState({isRequired: true});
  },
  render() {
    return (
      <MyInput name="some_field" type="text" required={this.state.isRequired}>
    );
  }
});
```

So when `isRequired` is `false`, the field is not required, and when it's `true`, the field is required. `isFalse` is not what they're looking for, because that **requires** the field to be `false`.

**Comment by C3PablO** [comment]
I have the same problem, but just on my own environment. It works properly on the "login example" but copy-pasting on my project the validation is fired when there is no rerquired attribute

**Comment by silvenon** [comment]
Hm, strange, that didn't happen to me on a very recent project :confused:

**Comment by C3PablO** [comment]
Here is a jsfiddle with the "login example" showing this problem: https://jsfiddle.net/reactjs/69z2wepo/

**Comment by C3PablO** [comment]
Here is a jsfiddle running the problem with the "login": https://jsfiddle.net/69z2wepo/15413/
It's works with the repository configuration but not in different environments.

**Comment by mythfish** [comment]
+1

**Comment by wkerswell** [comment]
I also have this issue. Not too sure its being explained correctly though. I have an input that is not required but if the user does fill it in I need to make sure its valid. For example. 

```
required={false}
validations={{
    minLength:2,
    maxLength:50
}}
 validationErrors={{
    minLength: 'Your Address must be at least 2 characters.',
    maxLength: 'Your Address can not be longer than 50 characters.'
}}
```

When I try to submit the form the validation errors will pop up even when the user has entered any input into the field. 
 
Is this possible if so what am I missing? I have read through the docs and cannot see a way of doing this. 

I did find a way of doing it by adding a custom rule but I don't really want to write custom rules for all fields that are required. 

Thanks.

**Comment by christianalfoni** [comment]
Hi guys,

There has been a bit confusion on how required is being used and it will be cleaned up after next release of Formsy.

The prop `validations` uses validation rules to set errors. The prop `required` can also use validation rules to indicate when an input should be required.

So:

```js
// When the value of the input is `false`, showRequired() will give true
<MyInput name="some_field" type="text" required="isFalse">

// When the value of the input is falsy (empty string etc), showRequired() will give true
<MyInput name="some_field" type="text" required>

// showRequired() will always be false 
<MyInput name="some_field" type="text">
```

So what we need to clean up here is maybe use a new property. Just throwing it out there:

```js
<MyInput name="some_field" type="text" required={true/false} requiredRule="isFalse">
```

But yeah, I hope this explained how it works now.

**Comment by Nicolab** [comment]
Thanks for the explanation @christianalfoni 

```js
<MyInput name="some_field" type="text" required={true/false} requiredRule="isFalse">
```

:+1:  Would be very useful
