### ISSUE TITLE
Should pristine values be set to new prop values?

### ISSUE THREAD

**Issue by eventhough** [christianalfoni/formsy-react#164]
I have a question about this test: [https://github.com/christianalfoni/formsy-react/blob/master/specs/Formsy-spec.jsx#L605-L614](https://github.com/christianalfoni/formsy-react/blob/master/specs/Formsy-spec.jsx#L605-L614)

When props change, should we be setting `_pristineValue` to the new prop value? In my situation I am using formsy to display a row of data in my db. The user clicks "edit" which allows him to edit the form. Then the user hits "save" this updates the row in my db. Afterwards I pull the data from the db and I update the props for all my formsy inputs to show new values.

Now let's say the user were to click "edit" again but instead of saving, clicks "cancel" (which resets the form). The values are reset to `_pristineValue` which was the **old value** before the db update. Is this what we want?

If the prop value changes, shouldn't we be using the new value as the pristine value? In Mixin.js I would like to do something like this:

```javascript
// We have to make the validate method is kept when new props are added
  componentWillReceiveProps: function (nextProps) {
    this.setValidations(nextProps.validations, nextProps.required);
    if (nextProps.value !== this.state._pristineValue) {
      this.setState({
        _pristineValue: nextProps
      });
    }
  },
```

We would have to change the last line of the test I referenced above to expect the value to be false after we call `setProps`. Thoughts?

**Comment by christianalfoni** [comment]
Hi @eventhough, yeah, I think you might be right about this. Just to summarize with my own words here.

<MyInput value={someValue}/>

Whenever "someValue" changes that should become the new pristine value of "MyInput". Whenever "MyInput" uses "setValue" that will of course not become the new pristine value.

Would love some comments on this, @Semigradsky, @idream3?

**Comment by idream3** [comment]
@christianalfoni @eventhough @Semigradsky 

+1 for this behaviour :)

This is actually a situation in our app - we display form fields all the time and are available to edit and save with no explicity 'edit' state or modal popup.

Although we don't implement a reset function, if we did, I would want the pristine value to be the latest that is passed in via props and not the original value.

**Comment by christianalfoni** [comment]
Hm, I have been thinking a bit more on this. Like a plain input you want to pass the changes through your application state store. Typically `onChange` on an input and `value={this.state.value}`. With Formsy, in combination with f.eks. Cerebral:

```js
@Cerebral({
  form: ['form']
})
class MyForm extends React.Component {
  onFormChange(data) {
    this.props.signals.formChanged({form: data});
  }
  render() {
    return (
      <Formsy.Form onChange={(data) => this.onFormChange(data)}>
        <MyInput name="foo" value={this.props.form.foo}/>
      </Formsy.Form>
    );
  }
}
``` 
This is a typical setup for creating "application state". The problem with implementing what is suggested here is that the value prop will change on every change of the form. So it will always get a pristine value.

This is the difficult balance of internal/external state handling. I think it is important to let developers control the form from some external state store, without messing up the pristine stuff. Maybe we should rather have a `pristineValue` or `defaultValue`? That way you can control it however you like?

**Comment by aphillipo** [comment]
+1 for defaultValue - it would make it explicit what is happening - defaultValue always replaces pristine form data and value is always the latest edited version?  

I also really need this as soon as possible.  Can I call setPristine in the mean time if I know that to be the case?

**Comment by christianalfoni** [comment]
Will add `defaultValue` in next release, it just gives a lot more control. Let me know if this is a problem
