### ISSUE TITLE
Possible to collect errors from all inputs?

### ISSUE THREAD

**Issue by mguterl** [christianalfoni/formsy-react#165]
We want to display a list of errors on the top of the form instead of next to each input. Is there an easy way to do this that I'm missing?

I was thinking about wrapping our Formsy.Form with our own form component and have each input register errors with the wrapped component.

Anyone else doing anything similar or have any suggestions?

**Comment by christianalfoni** [comment]
You actually have access to all the elements of the form through the formsy.form component. You could go through those instead of wrapping. So:

```js
var MyForm = React.createClass({
  mixins: [Formsy.Mixin],
  showErrors: function () {
    this.refs.form.inputs // All components registered to form. Check their state prop etc.
  },
  render: function () {
    <Formsy.Form ref="form" onInvalidSubmit={this.showErrors}/>
  }
});
```

Though it would be good to get this info directly. So maybe "onInvalidSubmit" and "onInvalid" hooks should pass an object with elements and their error messages. What do you think?

**Comment by mguterl** [comment]
Thanks @christianalfoni this solved my problem!

I agree that onInvalidSubmit and onInvalid should probably pass some type of object. It seems like you could either pass a collection of errors or pass the form component and add a function that provides easier access to the errors.

**Comment by christianalfoni** [comment]
Will make part of next release :-)

**Comment by martindederer** [comment]
Did this feature make it into a release yet?

**Comment by martindederer** [comment]
I did some digging and apparently it is still missing.

@christianalfoni: Do you have any preference on the method signature of the onSubmit/onInvalidSubmit methods? Would supplying the "this.inputs" member of Formsy.Form in fourth position of the said methods be ok?
