### ISSUE TITLE
Validate on blur or submit

### ISSUE THREAD

**Issue by silvenon** [christianalfoni/formsy-react#166]
I always found it annoying when a field is validating as I type :sweat_smile: Is there a way to configure it to validate on other events, on blur or on submit?

**Comment by israelidanny** [comment]
+1 
I think this is a great idea. Validating on the fly can be incredibly annoying.

**Comment by twisty** [comment]
Hi, validating after blur is possible, delaying validation until submit isn't possible at the moment.

* Validate email after blur: #139
* Add optional prop 'validateOnSubmit' to Form component: #147

Maybe you could work around this by suppressing the rendering the validation warnings? For example, you could set a property on the form components that dictates whether to render the validation errors, and change this property on `onValidSubmit` and `onInvalidSubmit` callback.

**Comment by silvenon** [comment]
Validating on blur is enough for me, I didn't know it was solved already, might be a good addition to the docs :+1:

**Comment by christianalfoni** [comment]
@Semigradsky I was thinking about adding a "ELEMENT EXAMPLES" next to "HOW TO USE". Just lots of different examples of how to write different kinds of elements. You up for starting on that? :-)

**Comment by Semigradsky** [comment]
A good idea! I'll do it when I have enough time.

**Comment by CrisLi** [comment]
I think I posted a similar request. After did that I found this thread. It will be very nice if formsy-react has this feature.
