### ISSUE TITLE
Immutable.js support

### ISSUE THREAD

**Issue by charosez** [christianalfoni/formsy-react#167]
Formsy uses length, which breaks when used with immutable objects. (uses size)

Is there going to be support for immutable objects in the future?

**Comment by charosez** [comment]
You can set Immutable.Iterable.noLengthWarning = true;

**Comment by charosez** [comment]
Even without the warning it still immutable.js st

**Comment by christianalfoni** [comment]
Hm, could you give a code example that breaks? Just have to understand exactly where the problem is :-)

**Comment by christianalfoni** [comment]
Old issue
