### ISSUE TITLE
Does formsy-react support ES6 ?

### ISSUE THREAD

**Issue by sijo-vijayan** [christianalfoni/formsy-react#169]
Hi,

I am a newcomer in React.js with ES6 codding pattern, I would like to use `formsy-react`, is it support ES6 ? If possible, Can you include a sample code in ES6 pattern.

Thanks
Sijo Vijayan

**Comment by silvenon** [comment]
I suggest reading [this post](http://babeljs.io/blog/2015/06/07/react-on-es6-plus/). React supports ES6+, therefore formsy-react supports it as well. I'm not sure how you do mixins with ES6 classes, though, the post doesn't mention it…

**Comment by christianalfoni** [comment]
Formsy is just a normal element, `<Formsy.Form/>`, Higher Order Components and Decorator version of the elements you build for the form will arrive in next version :-)

**Comment by oscar-g** [comment]
I got it to work by using React.createClass in MyInput (or wherever you want to use mixins).  I use the `extends React.Component` syntax everywhere else in my app.

Straight from the docs:
````
export const Input = React.createClass({
    mixins: [Formsy.Mixin],

    // setValue() will set the value of the component, which in 
    // turn will validate it and the rest of the form
    changeValue: function (event) {
        this.setValue(event.currentTarget.value);
    },
    render: function () {

        var className = this.showRequired() ? 'required' : this.showError() ? 'error' : null;
        var errorMessage = this.getErrorMessage();

        return (
        <div className={className}>
            <input type="text" onChange={this.changeValue} value={this.getValue()} placeholder={this.props.placeholder}/>
            <span>{errorMessage}</span>
        </div>
        );
    }
});
````

I hope that helps someone :)

**Comment by diessica** [comment]
See https://github.com/christianalfoni/formsy-react/blob/master/API.md#formsyhoc

**Comment by oscar-g** [comment]
@diessica Yes, that is the way to go now! +1

**Comment by alexfqc** [comment]
@oscar-g I think the same! +1!
