### ISSUE TITLE
Override input name requirement?

### ISSUE THREAD

**Issue by burtyish** [christianalfoni/formsy-react#17]
I'm putting together a Stripe form that's supposed to collect credit card info.
[Stripe documentation](https://stripe.com/docs/tutorials/forms) states that the inputs shouldn't have a `name` attribute for security reasons.
So unless I can disable the requirement for `name`, I can't use formsy here.
Any suggestions?

**Comment by burtyish** [comment]
I see that the name is used to register the input to the form so maybe an optional property could be used to specify that inputs are registered using `id` instead of `name`.

**Comment by christianalfoni** [comment]
Hi @burtyish,

Actually, the input itself does not need a name attribute. Create your own credit card info formsy element, something like:

```javascript
var CreditCardInfoInput = React.createClass({
  mixins: [Formsy.Mixin],
  updateValue: function (event) {
    this.setValue(event.target.value);
  },
  render: function () {
    return <input value={this.getValue()} onChange={this.updateValue}/>
  }
});
```
This wraps your plain input, without a name attribute, into a formsy element. You can now use it like this:

```javascript
<Formsy.Form>
  <CreditCardInfoInput name="creditcardinfo"/>
</Formsy.Form>
```
The name attribute used here has nothing to do with the input inside. It is just a property on the **CreditCardInfoInput** component that Formsy will use to identify the property name for the value. So you are following the guidelines with this solution.

Hope this was an okay explanation, but please let me know if you have more questions :-)

**Comment by burtyish** [comment]
Thanks for the quick response. I'll try it and update.

**Comment by burtyish** [comment]
Works like a charm, thanks!

**Comment by christianalfoni** [comment]
Sweet :-)

**Comment by amartracxn** [comment]
If I push some input element dynamically in to the Form (after rendering of form) then is it going to be a registered element for that form. Or the consequence is expected as "NO"
