### ISSUE TITLE
Nesting components deeper than one level

### ISSUE THREAD

**Issue by silvenon** [christianalfoni/formsy-react#171]
Is this possible? I have a component which is nested deeper into a `Formsy.Form`, but I get:

```
Uncaught Error: Form Mixin requires component to be nested in a Form
```

**Comment by silvenon** [comment]
To give more info, some parts of my form are a collection of inputs which affect each other, so I extracted them as separate components.

**Comment by twisty** [comment]
It's not possible with the currently released version, but will be coming in a future release.

See https://github.com/christianalfoni/formsy-react/issues/158.

**Comment by silvenon** [comment]
Great! Closing this then…
