### ISSUE TITLE
Async validation

### ISSUE THREAD

**Issue by vkrol** [christianalfoni/formsy-react#175]
Hello!
Please tell me is formsy-react supports async validation?

Thanks.

**Comment by Semigradsky** [comment]
Hello!
Now it is not supported. In what form would you like to see it?

Something like that?
```js
Formsy.addValidationRule('myAsyncRule', function (values, value, done) {
  done(true);
});
```

**Comment by christianalfoni** [comment]
You can do async validation if you run your own validation. If you use the following hooks, as an example:

```js
var validate = function (values, reset, invalidate) {
 // Check the values of the form and do your async validation, then
// run the invalidate function to invalidate the form
};

<Formsy.Form onSubmit={validate}>
// Your elements
</Formsy.Form>
```
I am very unsure how Formsy would handle this internally, as those validations run as values change. Not good user experience. I suppose you want to run it on submit? So yeah, I would solve it with the code above :-)

Let us know if that does not work for you, but it would be nice with a use case to assist you better

**Comment by wwsun** [comment]
can u provide a example with more detail, I also want to check the username existence via Ajax call @christianalfoni

**Comment by wwsun** [comment]
can u provide an example with more detail, I also want to check the username existence via Ajax call @christianalfoni

**Comment by kibs** [comment]
A use case could be, lets say an email or username field, when typing in the field, a validator could call an API to check if the email/username is already taken by another user. This could happen onBlur, or maybe using a debounce function.

**Comment by christianalfoni** [comment]
This still has to be done using existing hooks. Async validation is way too complex for Formsy to handle internally I believe. There are just so many ways to handle it, so it is better to have some hooks that manages it exactly like you want. Added example here to wiki. 

Let me know if there are specific scenarios and we can take a look at them?

**Comment by pjanik** [comment]
Hm, any good examples for async validation performed onChange (with some debounce) or onBlur?
I've been trying to design something nice using Formsy API, but each time I hit the wall.

**Comment by lfbn** [comment]
Interesting question.

What I ended up doing was having a reference to the input, and after the validation response from the server called setValue with it's getValue. Not pretty.

In my case this was a situation where I needed to do a server-side validation on each key press.

Anyone has better ideas?

**Comment by logemann** [comment]
I tried async custom validation via addValidationRule and handled the promise inside the function via then/catch but that doesnt work at all. Always came back as invalid even the pormise was successful. Of course i also have the use case with "username already taken".
