### ISSUE TITLE
Optional but pristine still set form to invalid

### ISSUE THREAD

**Issue by jaraquistain** [christianalfoni/formsy-react#177]
I'm not sure if this an issue so much as I'm not sure what the correct way to handle this case would be.

I've got a form with 3 fields: `email`, `password` and `adminPassword`.

The idea is that if you're an admin you can change a user's email and/or password, but must provide your admin password to verify. It is likely that you would want to change one and not the other so I've made `email` and `password` optional but `adminPassword` required.

I've also got the `isEmail` validator on the `email` field.

My problem is that as it stands if I enter in a value for `password` and `adminPassword` and submit the form, the `submitInvalid` method is invoked because `isEmail` says that a null email is invalid, despite being optional and pristine.

This seems incorrect behavior to me. Typically with any validators I've written previously a null value is always valid as its absence should be caught by a `required` validator, if it is in fact required.

Of course I'm aware that I could write my own validation function that tests whether or not the value is a valid email or an empty string and returns true if it is, but that seems a waste to have to do that every time I want validation on an optional field.

Thoughts?

**Comment by jaraquistain** [comment]
Anyone?

**Comment by Nicolab** [comment]
Hi,

see #163

**Comment by christianalfoni** [comment]
Hi there @jaraquistain,

Are you passing `null` as the value to the input? You have some snippets, just to make sure I understand this correctly

**Comment by Semigradsky** [comment]
This issue resolved in #138
