### ISSUE TITLE
Public method to get all values from controls

### ISSUE THREAD

**Issue by rodryquintero** [christianalfoni/formsy-react#178]
It would be usefull to expose a method that allows you access to all the values of the form controls contained inside Formsy. I need this to be able to compare the current state of the form with the last saved state in order to determine if there are any unsaved changes.

What do you think?

**Comment by neopeak** [comment]
Depending on your use case, the onChange event will receive all the currentValues of the form, so you can track the values this way.

**Comment by rodryquintero** [comment]
I tried the onChange event on the form, but it can make the component a
little jerky at times.

This is why I think it is very convenient to just have access to the form's
state at any time.

On Wed, Aug 5, 2015 at 10:49 AM, Cedric Veilleux <notifications@github.com>
wrote:

> Depending on your use case, the onChange event will receive all the
> currentValues of the form, so you can track the values this way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christianalfoni/formsy-react/issues/178#issuecomment-128046644>
> .
>



-- 
**** Ivan Quintero

**Comment by christianalfoni** [comment]
Hi @rodryquintero, in what way is it jerky? :-) I think it would be better to fix that as it is more "future proof" in regards of accessing child components in React.

**Comment by rodryquintero** [comment]
It feels jerky everytime you start typing text into the child components. It stopped when I removed the callback. If the forms form values (state) is accesible/public to parent components at all times we would not need to populate an object with the values everytime there is a change event on children.

**Comment by christianalfoni** [comment]
Hi again,

Hm, what did you put inside the onChange handler? diffing two shallow objects should not cause jerkyness. I have this feeling there is something special happening inside the `onChange` handler in this specific scenario. Calling a function vs accessing an object should not have any noticeable performance issues

**Comment by rodryquintero** [comment]
I don't remember what I was doing exactly on the callback, but it is very probable that I was updating an object to keep track of the form changes. Every keystroke on the form would trigger this callback.

Since I  know that Formsy, somewhere, keeps track of these changes, I thought it would be more efficient to simply look at the variable holding this information.

**Comment by Semigradsky** [comment]
@rodryquintero Hi! Use [`getModel()`](https://github.com/christianalfoni/formsy-react/blob/master/API.md#getmodel) for taking values from attached inputs.
