### ISSUE TITLE
Formsy Validations on form content changes.

### ISSUE THREAD

**Issue by aphillipo** [christianalfoni/formsy-react#179]
So I had a form that has a select dropdown and other parts of the form are replaced by an action being created, store changing and things in render() updating, standard React/Flux stuff.

This is fine, however, if you have the fields that are named the same in these subforms the replacement causes formsy to validate the fields (in this case as empty required values).  I have found a solution is to give these fields a unique key value so maybe this is an internal issue with React, I don't know.

I'm more putting this here as a note for anyone doing dynamic forms who have things validating early!

Feel free to close if you can't see an easy fix.

**Comment by christianalfoni** [comment]
Ah, yes, its important to give key values so that React can identify them "as the same component". Please elaborate if you think I misunderstand something, but yeah, my interpretation is that this is a React issue :)
