### ISSUE TITLE
Handle validation outside of the form

### ISSUE THREAD

**Issue by AlexeyFrolov** [christianalfoni/formsy-react#18]
I think that it's will be more react-way to handle validation outside of Form and make Form fully controlled by data that comes in. Say, we could have onSubmit handler and make the owner be responsible for validations, generate errors for fields, update state with errors and send errors to the form by props. Why? Because IMO validation should be applied to the data which form generates, not form itself.

**Comment by christianalfoni** [comment]
Hi @AlexeyFrolov and thanks for the input!

I do see your point with doing the validation outside of the form and use props to tell which inputs has errors etc., but how would you handle validation done when the input itself is changing? How would you handle indicating required fields? How would you handle pristine state? 

With a simple form that only changes state when it is submitted I totally agree with your argument, but the increase of complexity when validating the form "as you type" requires this tight coupling I think. Also looking at normal HTML5 attributes with the pattern-attribute and even just using a type-attribute (email, phonenumber) gives you validation on the form, much like Formsy validations-attribute (http://www.the-art-of-web.com/html/html5-form-validation/).

But you are very welcome to just use the onSubmit method and do the validation there, passing updated error props to the inputs in your form. But then you probably would be better of just using a normal form I think :-)

Please correct me if I misunderstood your input!

**Comment by AlexeyFrolov** [comment]
Any way, if you have business logic, you should consider to store this logic in a single layer. This logic could be distributed to other layers (forms for example) in different ways, but you should have that single layer which consist validation as well, as part of business logic.

> With a simple form that only changes state when it is submitted I totally agree with your argument, but the increase of complexity when validating the form "as you type" requires this tight coupling I think
It doesn't matter what kind of event you're using to trigger validation, I guess

**Comment by AlexeyFrolov** [comment]
And because of that I think you need to think of convenient way how user of your library could distribute his validation logic in your implementation

**Comment by christianalfoni** [comment]
Hi again @AlexeyFrolov,

How would you feel about something like this:

```html
<Formsy.Form onSubmit={this.validate} errors={this.state.errors}>
  <MyInput name="myInputName" validationError="Something wrong here"/>
</Formsy.Form>
```

So the errors object you pass in will be in the format of: { myInputName: true }. That way you can control all validation from outside the form. Would that make sense?

If not, please give me an example of how you would expand the API to cover the need discussed here :-)

**Comment by christianalfoni** [comment]
This will soon be released as `validationErrors` property on the form. You can use `onChange` or `onSubmit` to set any errors manually by updating the object on the validationErrors prop.
