### ISSUE TITLE
Is there any way to change the validation happened time?

### ISSUE THREAD

**Issue by CrisLi** [christianalfoni/formsy-react#182]
Right now, it seems like the Form component will be validated once the `this.setValue()`  [Formsy.Mixin] method is called. Can I change to when the form has been submitted, validate all inputs.

**Comment by ColeTownsend** [comment]
+1 on this. In most cases people won't be simply copying and pasting a valid email into the form, instantly. I'd love to have a setTimeout option on the onError or validation function.

**Comment by camerow** [comment]
Another +1 here. Any way we can get something like an `onBlur` validation check. Or perhaps you have a Formsy way for doing such a thing already?

**Comment by christianalfoni** [comment]
Hi guys!

Yes, this is something that has been requested before too. 

Adding it to list for next release: https://github.com/christianalfoni/formsy-react/issues/206
