### ISSUE TITLE
Add a Formsy.values prop to set all initial values of the form

### ISSUE THREAD

**Issue by neopeak** [christianalfoni/formsy-react#183]
Let's say I am Editing an object. The object already exists and I want to provide a form to modify its values.

It would be nice if I could simply inject all the values at once using a value or values prop on the parent form.

Right now I think I would have to set the value of each individual fields. This could still be possible, but if value props is not provided on a field, a default one from the parent form's 'values' prop would be used.

**Comment by devlll** [comment]
+1 this will be nice.

**Comment by ppiekarczyk** [comment]
+1

**Comment by christianalfoni** [comment]
Makes sense, let me add it to next release, https://github.com/christianalfoni/formsy-react/issues/206
