### ISSUE TITLE
custom validator cannot work when using ajax

### ISSUE THREAD

**Issue by wwsun** [christianalfoni/formsy-react#185]
Hi, I want to use custom validator to validate if the username is in database, however, when I use callback in validate functions, it cannot work, and always return `false`

	<MyInput name='name' title='name' validations={{
		nameExistenceCheck: function (value) {
		  if (value.name === undefined || value.name.length < 5) {
		    return false;
		  } else {
		    // ajax
		    DataSource.isNameExisted(value.name, function (response) {
		      if (response.data.msg === 'available') {
		        return true;
		      }
		    })
		  }
		}
		}}  validationError='Length less than 5 or the name is already existed!'/>

**Comment by christianalfoni** [comment]
Hi @wwsun Yes, it is because you validate asynchronously, which does not work. It will not be part of the API as it is a very complex operation that devs want to handle very differently. You have to move this logic outside the form.

```js
var nameBeingValidated = null;
var onChange = function (data, reset, invalidate) {
  if (data.name && nameBeingValidated !== data.name) {
    // Validate name on server
    // If not valid
   invalidate({name: 'That name is not valid');
  }
};
<Formsy.Form onChange={onChange}>
  <MyInput>
</Formsy.Form>
```

Simple example, I hope it makes sense

**Comment by wwsun** [comment]
thx

**Comment by scotro** [comment]
The example would work for `onSubmit`, however `onChange` doesn't provide an `invalidate` in the [args it passes to the handler](https://github.com/christianalfoni/formsy-react/blob/master/API.md#onchange).

It is possible to set [validation errors](https://github.com/christianalfoni/formsy-react/blob/master/API.md#validationerrors) on the form component as an alternative to calling invalidate. Unfortunately, doing so appears to override the built-in validation at the component level.

**Comment by christianalfoni** [comment]
Hi guys,

So sorry for my wrong example. Yes, you would do this on the submit.

**Comment by christianalfoni** [comment]
Let me know if is needed to discuss this more!
