### ISSUE TITLE
 this.isValid is not a function

### ISSUE THREAD

**Issue by emeeks** [christianalfoni/formsy-react#187]
I'm trying to make an update during an `onChange` event but I noticed the validation doesn't fire until after the `onChange` event, so I thought I'd check to see if the current value was valid by using `this.isValid()`:
```js
changeValue: function () {
      if (this.isValid() === true) {
        var newVal = model.value;
        Actions.receiveValue(newValu);
      }
}
```

But when I do that, I get:

> Uncaught TypeError: this.isValid is not a function

If there's another, better way to check for validity during an `onChange` event, that would be welcome.

**Comment by christianalfoni** [comment]
I believe you are calling the method incorrectly. Using `class` syntax? Make sure you bind the method to the component :-)

**Comment by Semigradsky** [comment]
@emeeks The issue resolved?
