### ISSUE TITLE
How to access values of child Formsy components in parent component

### ISSUE THREAD

**Issue by EthanML** [christianalfoni/formsy-react#189]
In my top-level form component, which contains various custom components that implement the Formsy mixin, is it possible to access the current state / value of those child components? 
The only way I've found to do this so far is within the `Formsy.Form`'s submit / change handlers since they have access to the 'model' param. Is there a way to access these elsewhere in the component? Or am I just trying to do this the wrong way?

**Comment by christianalfoni** [comment]
@EthanML , you can access it by using "ref" on the form elements and dive into the component, but that is not really the way to go :-)

If you give some more context to the challenge I am sure we can figure out a good way to handle this!

**Comment by CharlieGreenman** [comment]
@EthanML did you ever find a viable solution for accessing child components? Thanks!

**Comment by EthanML** [comment]
@CharlieGreenman I'm afraid not, we ended up rolling our own solution in the end for this.

**Comment by CharlieGreenman** [comment]
@EthanML , thank you for responding, that really helped. Your own solution, did you manage to use a ref on components, with Formsy, or did you have to forgo Formsy altogether? Thanks again :)

**Comment by Semigradsky** [comment]
@EthanML @CharlieGreenman  Hi! Use [`getModel()`](https://github.com/christianalfoni/formsy-react/blob/master/API.md#getmodel) for taking values from attached inputs.

**Comment by vishesh774** [comment]
@Semigradsky I have a problem with using getModel(). I tried whats there in the documentation but end up getting "Uncaught TypeError: this.refs.form.getModel is not a function"

My Code is 
var VehicleFilters = React.createClass({
    filterVehicles : function(){
      alert(this.refs.form.getModel());
    },
    render: function () {
      return (
           <Formsy.Form ref="form">
          <NumberBox name="vehiclelength" labelval="L"/>        
           </Formsy.Form>
      );
    }
  });


NumberBox is a component which i require() from a different file.Any help on this is appreciated.

**Comment by vishesh774** [comment]
@Semigradsky I have a problem with using getModel(). I tried whats there in the documentation but end up getting "Uncaught TypeError: this.refs.form.getModel is not a function"

My Code is 
var VehicleFilters = React.createClass({
    filterVehicles : function(){
      alert(this.refs.form.getModel());
    },
    render: function () {
      return (
           <Formsy.Form ref="form">
           <NumberBox name="vehiclelength" labelval="L"/>        
           </Formsy.Form>
      );
    }
  });

NumberBox is a component which i require() from a different file.Any help on this is appreciated.

**Comment by Semigradsky** [comment]
The new version has not yet been released
