### ISSUE TITLE
Error when value is set to int

### ISSUE THREAD

**Issue by BrettThePark** [christianalfoni/formsy-react#19]
When using the mixin and setting a value based on an integer, the validation will crash while trying to do a .match (since the value is an int not a string).

Perhaps the value should be converted to a string upon set in the mixin.

```var data = {value:5};
< MyOwnInput name="failedTest" value={data.value} validations="isInteger" validationError="This is not a valid integer" required/>
```

**Comment by christianalfoni** [comment]
Hi Brett!

This is a difficult one :-)

Formsy allows for setting any value as the value of the form element, not just strings and booleans as you typically can with traditional form elements. If forcing everything to be a string I believe it will restrict too much, at least for now.

I suppose you created the isInteger validation rule yourself? Or are you referring to the isNumeric default validation rule?

If you created isInteger yourself I suggest you add a check to the validation rule, or convert it to string as that is what you want for your specific forms. If you are referring to the default isNumeric validation rule I think it should also be "true" when validating integers, so I can fix that.

Did I understand you correctly on this? :-)

**Comment by BrettThePark** [comment]
The issue was with the built in validation method isNumeric and it erroring for an integer (which I thought would work by default). 

Brett

P.S. I'm enjoying your library:-)

**Comment by christianalfoni** [comment]
Hehe, thanks for that note ;-)

I will add this as a bug and fix it. Thanks for the report!

**Comment by christianalfoni** [comment]
This should be fixed
