### ISSUE TITLE
multiple validations

### ISSUE THREAD

**Issue by rblakeley** [christianalfoni/formsy-react#190]
It looks like the `isAlphanumeric` validation rule was not included.  So what is the supported way to check more than one validation rule, e.x `isWords,isNumeric`?

**Comment by Semigradsky** [comment]
You can check more than one validation rule:
```js
<MyInputComponent name="number" validations="isNumeric,isLength:5"/>
<MyInputComponent name="number" validations={{
  isNumeric: true,
  isLength: 5
}}/>
```
However, the value must comply with all these rules.

You'd better add your rule: [`addValidationRule`](https://github.com/christianalfoni/formsy-react/blob/master/API.md#formsyaddvalidationrule)

**Comment by rblakeley** [comment]
Built-in validation is probably the most important selling point of using this form component. For the average user, writing a custom rule doesn't seem like an attractive option for something as common as an alphanumeric check (e.x. mailing address).

I think this should be patched. But should it be patched with an `isAlphanumeric` rule or some functionality for combining validation rules that works like an "or" statement?

**Comment by Semigradsky** [comment]
Add new `isAlphanumeric` rule to built-in validations will be easier =)

**Comment by christianalfoni** [comment]
Added to list: https://github.com/christianalfoni/formsy-react/issues/206

**Comment by rblakeley** [comment]
Awesome, thanks!
