### ISSUE TITLE
How can I reset radio and select input

### ISSUE THREAD

**Issue by Ezekiah** [christianalfoni/formsy-react#194]
Hello,

I am using your great built in reset method to reset the values of my text inputs, however the method doesn't seems to reset select or radio inputs, do you know why ? Maybe it should trigger pristine selected, or checked on these inputs.

On the formsy react component playground the reset button works well, but maybe you added extra code to make it work like you store the selected option somewhere, but I don't find the source code, there is only a bundle.

Can you guide me to achieve it ?

Thanks a lot for your work !

**Comment by Semigradsky** [comment]
Hi!
See `reset-values` example (https://github.com/christianalfoni/formsy-react/tree/react-0.14/examples)
