### ISSUE TITLE
Unmount an input

### ISSUE THREAD

**Issue by rblakeley** [christianalfoni/formsy-react#196]
Within my form, I have a type of field which has '+' and '-' buttons to dynamically alter the count of that input.

When I add a field, leave it blank, and then remove it, the form's validation state is the same as before it was added. But if I add a field, enter an invalid value, then remove that field, the form stays locked in an invalid state until the next `onChange` event.

**Comment by christianalfoni** [comment]
Hm, yes, this is interesting. The state should be reset with the ` this.updateModel();`, but have to test it more closely. I see you removed it on a commit to your fork? Any reason for that? I can not see how that could fix the issue... did it? :-)

Let me know and I will put this on the block

**Comment by MaxTrawinski** [comment]
I'm in a similar situation: model object with nested phones array, which I then translate into input fields. The user can customize the list of phone elements with + - buttons. The fields are named according to a pattern I found elsewhere: "phones[0][number]". 

I can get the data out of the form using submit and that translates pretty well, however the reset function does not seem to populate the input fields.
