### ISSUE TITLE
Empty form

### ISSUE THREAD

**Issue by aesopwolf** [christianalfoni/formsy-react#20]
I just pulled 0.6.0 and I'm pretty sure I'm following directions right but my forms are still empty.

Here's my .jsx file, the line ```console.log(inputs)``` returns an empty Object. Also, the Request Payload in the Chrome Network Inspector is empty. What gives? 

```jsx
'use strict';

var React = require('react');
var Formsy = require('formsy-react');

var Profile = React.createClass({
  onSubmitted: function (data) {
    console.log(data);
  },
  mapInputs: function (inputs) {
    console.log(inputs); // why is this an empty Object {}?
    return {
      'email': inputs.email,
      'first': inputs.first,
      'last': inputs.last
    };
  },
  render: function() {
    return (
      <div>
        <Formsy.Form url="/api/profile" onSubmitted={this.onSubmitted} mapping={this.mapInputs}>
          <input name="email"/><br/>
          <input name="first"/><br/>
          <input name="last"/><br/>
          <button type="submit">Submit</button>
        </Formsy.Form>
      </div>
    );
  }
});
```

Another thing maybe worth mentioning, is that the mapInputs method seems to run twice, since I get two empty Objects logged in my console.

**Comment by christianalfoni** [comment]
Hi there!

Formsy.Forms require Formsy elements, you are using a native input. If you wrap those inputs in components:

```javascript
var MyInput = React.createClass({
  changeValue: function (event) {
    this.setValue(event.target.value);
  },
  render: function () {
    return <input value={this.getValue()} onChange={this.changeValue}/>
  }
});

// In form component
<Formsy.Form>
  <MyInpuit name="email"/>
</Formsy.Form>

```

Maybe I should document this a bit better. The reason it works this way is that wrapping

**Comment by christianalfoni** [comment]
.M

**Comment by aesopwolf** [comment]
Gotcha. I had assumed that was just a second option, not the required way. Thanks for clearing it up!
