### ISSUE TITLE
Online demo

### ISSUE THREAD

**Issue by io3** [christianalfoni/formsy-react#204]

**Comment by Semigradsky** [comment]
How about CodePen? :-)
http://codepen.io/semigradsky/pen/dYYpwv/?editors=001

**Comment by christianalfoni** [comment]
Maybe add link to README? :-)

Just closing this...

**Comment by mbrookes** [comment]
http://formsy-mui-demo.meteor.com/ ?

**Comment by luqin** [comment]
:+1:
