### ISSUE TITLE
Next Release (React 0.14)

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/formsy-react#206]
- [x] `onInvalid` and `onInvalidSubmit` should pass a map of input names and their errors
- [x] Browserify friendly
- [x] add `defaultValue` prop to be checked with `isPristine()` rather than the initial value. It is more explicit and will allow for more easily handle external state control, change what is the pristine value etc.
- [x] `values` prop on the form itself which will be used as default values for the form elements
- [x] Decorators
- [ ] Add `validateOnSubmit` flag to form. To allow validation to only happen when submitting
- [x] Add `isAlphanumeric`, isInt` and `isFloat` rule to default validators
- [x] Change testing framework and go green!
- [x] Transpile files to normal JS for usage with Node
- [x] Fix output of `getCurrentValues`, should be mapped correctly

**Comment by christianalfoni** [comment]
Everything except validate on submit is now part of it. Validate on submit can still be used by having a className on the form that you flip on when submitting the first time. By default validations are just hidden

**Comment by CrisLi** [comment]
@christianalfoni 

Do you have any plans when ```validateOnSubmit ``` will be released? We are using ```formsy-react``` in our project, currently, we take your suggestion (by having a className on the form). But it is not efficient, each ```Input``` component will be rendered 4 times after user type some thing into it.

**Comment by yasserzubair** [comment]
Hey! I cannot see any examples or explanation about `values` prop.  Can anyone please explain about it? I tried but cannot seem to set the value. Thank you.
