### ISSUE TITLE
mapping nested input names

### ISSUE THREAD

**Issue by rblakeley** [christianalfoni/formsy-react#207]
#153 added support for naming inputs as nested objects. But it did not carry over to [mapping](https://github.com/christianalfoni/formsy-react/blob/master/API.md#mapping)'s `inputs` parameter.
```
// <input name='product.price'>
// <input name='product.sku'>

// `this.model`
{
  "product": {
    "price": ...,
    "sku": ...
  }
}

// `inputs` parameter for `mapping`
{
  "product.price": ...,
  "product.sku": ...
}
```
Should `inputs` be patched to look like `this.model`?

**Comment by broveloper** [comment]
@christianalfoni could we push a new tag of 0.14.2 for the current master?  I noticed that the updates for nested names are not in 0.14.1

**Comment by christianalfoni** [comment]
Hi guys,

I am bringing branch React 0.14 into master this weekend and releasing new version. There are so many people using new version of React RC so I do not see any reason to wait.

All fixes will be included in this new release.

**Comment by Semigradsky** [comment]
Nice! :+1:

**Comment by broveloper** [comment]
:+1:

**Comment by avnersorek** [comment]
This doesn't work for me with React 15.3.0
Covering for it using -
```
  mapInputs: function(input) {
    let mapped = {};
    // this is so we can use nested structure in our form attributes
    Object.keys(input).filter(key => input.hasOwnProperty(key)).forEach(key => _.set(mapped, key, input[key]));
    return mapped;
  },
```
