### ISSUE TITLE
Update value via props and validate inputs onBlur

### ISSUE THREAD

**Issue by salayev** [christianalfoni/formsy-react#215]
If I update the value of `this.state.zipCode` here:
```jsx
<FormsyInput 
   id="zip-code" 
   name="zip_code" 
   ref="ZipCode" 
   label={this.props.label} 
   placeholder={this.props.placeholder} 
   validations="isNumeric,isLength:5" 
   validationError={this.props.validation_message} 
   value={this.state.zipCode || ''} 
   required />
```

then inside the component `FormsyInput` it only updates if the value in `props` is different. I found this in your `Mixin.js` source code:
```jsx
componentDidUpdate: function (prevProps) {

    // If the value passed has changed, set it. If value is not passed it will
    // internally update, and this will never run
    if (!utils.isSame(this.props.value, prevProps.value)) {
      this.setValue(this.props.value);
    }
  },
```
Use case: 
if the value (`this.state.zipCode`) of the input was `10070` originally
then I erase and type something like `123`
then try to pass `this.state.zipCode` from parent component (with `Formsy.Form`) with same value `10070`
then it doesn't update because my fields are validated `onBlur`
therefore `onChange` I'm not using `this.setValue(event.currentTarget.value)`
(following this: https://github.com/christianalfoni/formsy-react/wiki/validate-on-blur)

So `utils.isSame(this.props.value, prevProps.value)` is same even though I typed `123`

**Comment by salayev** [comment]
Fixed this by adding:
```js
if (_.isFunction(this.props.onBlur)) {
    this.props.onBlur(value);
}
```
on input blur event. `this.props.onBlur` function updates the value with Actions (I'm using Flux) in the parent which then passes it back to the input component.

**Comment by christianalfoni** [comment]
Great it worked out @salayev .

When next version of Formsy is released it will have a review as there has been many changes since its release. The though it to build a suggested spec for 1.0 version where APIs and how the internal state of the component will be perfected.
