### ISSUE TITLE
Input that is not required but needs validation.

### ISSUE THREAD

**Issue by wkerswell** [christianalfoni/formsy-react#217]
I have looked through the issues and seen similar issue but with no real answers. I have an input that is not required but if the user does fill it in I need to make sure its valid. For example. 

```
required={false}
validations={{
    minLength:2,
    maxLength:50
}}
 validationErrors={{
    minLength: 'Your Address must be at least 2 characters.',
    maxLength: 'Your Address can not be longer than 50 characters.'
}}
```

When I try to submit the form the validation errors will pop up even when the user hasn't entered any input into the field. 
 
Is this possible if so what am I missing? I have read through the docs and cannot see a way of doing this.  

I did find a way of doing it by adding a custom rule but I don't really want to write custom rules for all fields that aren't required. 

Thanks.

**Comment by paali** [comment]
+1. I have exactly the same issue. Need validation to happen if the field is not empty but empty is fine.

**Comment by Semigradsky** [comment]
See #135
This has been fixed, but the stable new version is not released yet.
You can use `formsy-react@0.15.1` (beta version)

**Comment by wkerswell** [comment]
Ah ok thanks.

**Comment by paali** [comment]
Thanks! That version is not visible on npmjs or github so this information is really useful!
