### ISSUE TITLE
isNumeric validator fails on decimal

### ISSUE THREAD

**Issue by BrettThePark** [christianalfoni/formsy-react#22]
If a decimal is provided in isNumeric, the validation will fail.

The value.match(/^-?[0-9]+$/) does not allow for a .

**Comment by BrettThePark** [comment]
I might propose something like this for isNumeric. It fixes this issue and https://github.com/christianalfoni/formsy-react/issues/19

```
Formsy.addValidationRule('isNumeric', function(value) {
  var stringVal = value + '';
  return stringVal.match(/^\d+\.?\d*$/);
});
```

**Comment by christianalfoni** [comment]
Hi Brett,

Sorry for late response, this issue got totally lost on me!

This should be fixed for next version!

**Comment by christianalfoni** [comment]
Should be fixed
