### ISSUE TITLE
Requiring from Node

### ISSUE THREAD

**Issue by danpantry** [christianalfoni/formsy-react#220]
I'm working on an isomorphic/universal (Whatever you call it) App in React. I decided to check out Formsy and have come across a big problem: I cannot use your library from Node environments because the published files to npm are in their raw, jsx form.

It's common practice for libraries that use alternative flavours of javascript to run a transpilation step in `prepublish` script - any chance this could be done for formsy? Otherwise I have to install babel on my isomorphic run time and instruct it to transpile `node_modules` - the same would go for mocha testing - or I would have to run the isomorphic app through webpack before using it in a node environment **and** I would have to use `mocha-webpack` (which is a PITA).

Both of these are really unacceptable overheads and I would rather switch to another library - which is a shame, because I'm impressed with how expressive this library is - but I don't want to have to change my entire toolchain around it.

You'd just have to run `babel` against the `./src` folder and output it to `./lib` (or similar of choosing) and then point your `package.json` to `./lib/main.js` rather than `./src/main.js`.

Using `require('formsy-react/release/formsy-react.js')` shouldn't really be the way to do this IMO. Webpack craps itself if you hand it a pre-built file.

**Comment by christianalfoni** [comment]
Jup, agreed, https://github.com/christianalfoni/formsy-react/issues/206
