### ISSUE TITLE
confirmation message after submit?

### ISSUE THREAD

**Issue by paOol** [christianalfoni/formsy-react#222]
How are you guys handling a simple 

"Thanks for contacting us" message upon successful submit?

I tried replacing the innerHTML of the form element, but that removed react IDs and broke my app.
couldn't find any API methods that would work for this.

**Comment by Semigradsky** [comment]
```js
{this.state.validSubmit ? "Thanks for contacting us" : ""}
```
in render, and
```js
this.setState({ validSubmit: true });
```
in `onValidSubmit`

**Comment by jaraquistain** [comment]
You could wrap the form in a ternary like `{ this.state.validSubmit ? [Thanks markup] : [Form markup]}`
