### ISSUE TITLE
Is there a way to set one filed as a optional filed?

### ISSUE THREAD

**Issue by mythfish** [christianalfoni/formsy-react#223]
I want to add a filed which the empty value or a numeric is valid. It seems the prop "required" is used for marking the optional filed, but I don't know how to use it.

**Comment by Semigradsky** [comment]
Just add `isNumeric` validation:
```js
<MyInputComponent name="foo" validations="isNumeric"/>
```

**Comment by mythfish** [comment]
I want the empty is a valid value. The validation you mentioned can not match the requirement.

**Comment by Semigradsky** [comment]
See #135

**Comment by mythfish** [comment]
@Semigradsky , thanks.
