### ISSUE TITLE
Is it possible to use inline styles?

### ISSUE THREAD

**Issue by almasakchabayev** [christianalfoni/formsy-react#230]
Hello,

Could not find any information about how to use/pass inline styles to Formsy Forms

Thx

**Comment by Semigradsky** [comment]
What's your problem with `style`?
```js
return (
      <Formsy.Form style={{background: "black"}} ...>
```

**Comment by almasakchabayev** [comment]
Nice, what about mixin some inline style library, for example Radium, so that inline styles get prefixed?

**Comment by Semigradsky** [comment]
You can use any method. `Formsy` does not limit you in this. See source:
```js
    return (
      <form {...this.props} onSubmit={this.submit}>
        {this.props.children}
      </form>
    );
```

**Comment by almasakchabayev** [comment]
Thanks, made it work with Radium! awesome lib, guys!
