### ISSUE TITLE
Form.validationErrors disables input validation

### ISSUE THREAD

**Issue by joker-777** [christianalfoni/formsy-react#239]
Hi,

I have a validation for an input tag but also want to be able to apply errors on it from the outside manually. I'm trying to do this with `Form.validationErrors` but it completely disable the input validation when `Form.validationErrors = {}` is set. If I set `Form.validationErrors = {number: 'wrong number'}` It shows the error message and the input validation works. Unfortunately the error message displayed from `Form.validationErrors` doesn't get removed nor updated.

What do I do wrong? It would be great if you could help me to set it up. Thanks also for your awesome react plugin.

**Comment by easyrider** [comment]
Hi,
I had a similar issue and solved it that way: https://github.com/christianalfoni/formsy-react/pull/242
