### ISSUE TITLE
Trigger validation with onBlur

### ISSUE THREAD

**Issue by gilbarbara** [christianalfoni/formsy-react#24]
hey Christian! 

I've made a global Input component that sometimes I need to set the value but other times I won't.

```
<input
type={this.props.type}  
name={this.props.name}  
value={this.getValue()}  
/>
```

Since I want to validate fields using `onBlur` the value won't be set until I call `this.setValue()` which in turn will trigger the validation.
Is there any way to `setValue` without triggering the validations?

Cheers!

**Comment by christianalfoni** [comment]
Hi @gilbarbara, sorry for the late reply!

As I understand it you might get away with using an internal state:

```javascript
var MyInput = React.createClass({
  mixins: [Formsy.Mixin],
  getInitialState: function () {
    return {
      value: this.props.value
    };
  },
  updateValue: function (event) {
    this.setState({ value: event.target.value });
  },
  syncValue: function () {
    this.setValue(this.state.value);
  },
  render: function () {
    return (
      <input
        type={this.props.type}  
        name={this.props.name} 
        onChange={this.updateValue}
        onBlur={this.syncValue} 
        value={this.state.value}  
      />
    )
  }
});
```

You think that could work?

**Comment by gilbarbara** [comment]
Hey

Thanks, I'll try this way.

Another quick question: Is there anyway to check the validity of an input without triggering the error?
If the value pass the validation with `onChange` I will display the OK but I'll only display the error with `onBlur`

**Comment by christianalfoni** [comment]
Hi @gilbarbara,

So you basically just want freedom to run the validation rule on the current value, without actually triggering validation?

```javascript
  render: function () {
    var isValid = this.testValid();
  }
```

Something like that? The only thing it does is run the current value against the validator.

**Comment by gilbarbara** [comment]
Hey @christianalfoni,

Sorry about the delay!
Yeah, I needed something like this and I already implemented that in my fork (well, almost. I couldn't get que equalsField to work yet).
But I had to change setValue to skipValidation. I didn't want to set states in my child components.
https://github.com/gilbarbara/formsy-react/commits/master

[s]

**Comment by christianalfoni** [comment]
Will see if I can include this in next version :-)

**Comment by christianalfoni** [comment]
This got a bit more complex than first expected, have to wait for next release

**Comment by christianalfoni** [comment]
Okay, this will be part of next release :-)

**Comment by gilbarbara** [comment]
Awesome! :+1:
