### ISSUE TITLE
React 0.13.x support?

### ISSUE THREAD

**Issue by mbrookes** [christianalfoni/formsy-react#244]
Does formsy-react have a specific dependancy on React 0.14 features, or would it be possible to loosen this to allow formsy-react to be used with React 0.13 if the parent app calls for it?

There are quite a number of 3rd party libs / apps that haven't caught up yet, meaning this can't be used with them (or rather only at version 0.14.1).

**Comment by arush** [comment]
formsy-react v0.15 and up rely on React 0.14 parent context types. You can make 0.17 work on 0.13.x if you replace `{this.props.children}` in main.js `render()` with  `{this.traverseChildrenAndRegisterInputs(this.props.children)}`

then replace all references to `this.context.formsy.**methodname**` in Mixin.js with `this.props._**methodname**`

**Comment by mbrookes** [comment]
@arush - thanks. @christianalfoni - would you be happy to release 0.14.2 if I submit this as a PR against 0.14.1?
