### ISSUE TITLE
Populate form from object

### ISSUE THREAD

**Issue by mbrookes** [christianalfoni/formsy-react#245]
I may be missing the obvious here, but what is the preferred method to populate the form from an object on mount? I see `reset()` allows this, but how to achieve the same for an "edit" form, populating the form from a model? (Or is reset the correct way to achieve that?)

Thanks!

**Comment by ingro** [comment]
I've stumbled in the same issue too, the problem with reset is (unless I'm doing something wrong) didn't set the pristine value of the field, so it remains `undefined`, which is not a desired behaviour.

**Comment by mj12albert** [comment]
Could it be this? https://github.com/christianalfoni/formsy-react/blob/master/API.md#value

Also looking to do this for an edit form.

**Comment by mbrookes** [comment]
As an individual form component default value, yes; but we were asking about using an object to populate multiple fields.

**Comment by yasserzubair** [comment]
Any luck with this? I'm looking for the same functionality.

**Comment by mbrookes** [comment]
Apparently development has moved here: https://github.com/formsy/formsy-react Not sure why the repo was cloned instead of being transferred, but it means you'll need to reopen this issue there.
