### ISSUE TITLE
Handle undefined/null child in registerInputs

### ISSUE THREAD

**Issue by sdemjanenko** [christianalfoni/formsy-react#25]
I find myself often writing code like:
```javascript
render: function() {
  if (condition) {
    var heading = <h1>Heading</h1>;
  }

  return <div>
    { heading }
    <MyInput ... />
  </div>
}
```

Unfortunately I get the error message `Uncaught TypeError: Cannot read property 'props' of null` when the condition evaluates to false.

**Comment by jonaswindey** [comment]
Does the same happen when you declare your var outside the condition as an empty object?

**Comment by sdemjanenko** [comment]
No but a lot of the react examples have render functions which return `null`.  I just submitted a PR #26 for this issue.

**Comment by christianalfoni** [comment]
And it has been accepted, awesome stuff, thanks :-)
