### ISSUE TITLE
Formsy 0.17.0 required me to install babelify

### ISSUE THREAD

**Issue by eriklharper** [christianalfoni/formsy-react#255]
I have an existing project using Formsy 0.14.x and went to upgrade it today and noticed that when I built the project using 0.17.0 my browserify task errored saying it couldn't find the module 'babelify'.  I've been needing to get around to integrating babelify into my project anyway, but it would be good to let folks know that this is a required dependency.  I poked around and saw this commit: https://github.com/christianalfoni/formsy-react/commit/36b5dd1dabdc234cec90e6fc07f75b1cc4cc1ad1 so it looks like you just need to bump up the tag version to include that commit, am I right?

**Comment by sys13** [comment]
My workaround: I just added babelify to browserify as a dependency and it worked without having to add any babelify plugins.

**Comment by Semigradsky** [comment]
Fix in #251

**Comment by tobyredd** [comment]
@sys13 What do you mean by "it worked without having to add any babelify plugins"? What version of babelify did you add to browserify's dependencies? Either way it's still gonna add a bunch to your node_modules directory right?
