### ISSUE TITLE
Kind of a newb question

### ISSUE THREAD

**Issue by dsteinbach** [christianalfoni/formsy-react#264]
Sorry if there is a simple answer but I've been struggling with this for a few hours.  I have inputs that i want to have at least one character typed in (first name, last name) so I am trying to use minLength:1 but after typing and deleting the value showError is still false and getErrorMessage is null. I'd like it to show the error after the input is no longer pristine but is empty.  How do I do that?

Thanks and I love formsy so far!

**Comment by dsteinbach** [comment]
I guess this is a dupe of the many other similar issues others are having.

**Comment by tnrich** [comment]
@dsteinbach I'm looking for an answer to this one as well. Do you know if it got resolved? I couldn't find the other issues that you mentioned.

Thanks!

**Comment by dsteinbach** [comment]
I guess I was confused by the behavior of required fields (required is what I was looking for not no minlength:1). Required fields won't display their error until you try submitting the form which is fine. The only problem is if you disable the submit button until the form is valid, the user might not realize which form elements need to be filled out.
