### ISSUE TITLE
Reflect updateInputsWithError method in documentation

### ISSUE THREAD

**Issue by poluyanov** [christianalfoni/formsy-react#265]
Hi folks!
I suppose it could be very useful to reflect possibility of external call updateInputsWithError(third parameter in submit callback) in documentation.
It is a very useful method when you have to invalidate form outside onValidSubmit callback(eg flux applications)

**Comment by Semigradsky** [comment]
Done! 18467a94a1ea95fd4ffe168218a59a9c07781dbc
