### ISSUE TITLE
Why are some validation rules preceded with !isExisty(value) || isEmpty(value) ?

### ISSUE THREAD

**Issue by le0nik** [christianalfoni/formsy-react#266]
I don't get it.

For example, `matchRegexp`, called with an empty string or null or undefined as `value` and ANY `regexp` would return `true`. Why?

matchRegexp:

```
return !isExisty(value) || isEmpty(value) || regexp.test(value);
```

https://github.com/christianalfoni/formsy-react/blob/v0.17.0/src/validationRules.js#L17

**Comment by agroves333** [comment]
It's so that the field will not be considered invalid when empty. (On page load, clearing the field. etc.)

**Comment by Semigradsky** [comment]
Yeah! Use [`required`](https://github.com/christianalfoni/formsy-react/blob/master/API.md#required) if you want validate empty value.
