### ISSUE TITLE
onValidationComplete sometimes errors when inputs are removed

### ISSUE THREAD

**Issue by sdemjanenko** [christianalfoni/formsy-react#267]
The `inputKeys` points to keys that no longer exist in `this.inputs`.

**Comment by farisj** [comment]
Having this same problem.

**Comment by meikoudras** [comment]
+1

**Comment by josercruz01** [comment]
+1

**Comment by dsteinbach** [comment]
+1

Seems to be a race condition. I have the following (mock) setup:
```
<ul>
   {this.workExp.map(function(exp, index){
      <li>
         <Input name={"work_exp[" + index + "].title"} value={exp.title} />
         <button onClick={removeWorkExp.bind(self, index)}>X</button>
         {exp.skills.map(function(skill, subindex){
            <Input name={"work_exp[" + index + "].skills[" + subindex + "]"} value={skill} />
         })}
     </li>
   })}
</ul>
```

When the user clicks X to remove a work experience, work_exp[0].title is unmounted first and validateForm is run too soon and is trying to validate this.inputs["work_exp[0].skills[0]"] which also has been unmounted.

The error is on this line:

https://github.com/christianalfoni/formsy-react/blob/master/src/main.js#L373
"Uncaught TypeError: Cannot read property 'state' of undefined"

Perhaps we want that line to be more defensive?

**Comment by Semigradsky** [comment]
Hi! The problem arises from the fact that the library is heavily dependent on the input names.
Therefore, problems occur when changing the name of the input.

I tried to get rid of it. See #275

**Comment by Semigradsky** [comment]
@sdemjanenko @farisj @meikoudras @josercruz01 Hi! Could you test #275 on your code? If everything is fine, I will merge it.

**Comment by sdemjanenko** [comment]
@Semigradsky: test still pass on #258 so all good :smile:

**Comment by farisj** [comment]
@Semigradsky looks good!

**Comment by josercruz01** [comment]
All good on my side as well @Semigradsky, thanks a lot for the fast response on this.

**Comment by dsteinbach** [comment]
Worked for me, thanks!

**Comment by C3PablO** [comment]
Works nice! Thanks! When are you planning next release?
