### ISSUE TITLE
Uncaught Error: Form Input requires a name property when used

### ISSUE THREAD

**Issue by cornerolive** [christianalfoni/formsy-react#270]
Hi,

I'm trying to create custom input but always I'm getting this error. Anybody know why? Thank you!

    var React = require('react');
    var Dropzone = require('react-dropzone');
    var Formsy = require('formsy-react');

    var DropzoneUpload = React.createClass({
    mixins: [Formsy.Mixin],

    getInitialState: function() {
        return {
            files: null
        };
    },

    onDrop: function(files) {
        this.setState({
            files: files
        });
        this.props.getFile(files);
    },

    changeValue: function (event) {
      this.setValue(event.currentTarget.value);
    },

    render: function () {
        var className = this.showRequired() ? 'required' : this.showError() ? 'error' : null;
        var errorMessage = this.getErrorMessage();

        return (
            <div className={className}>
                <Dropzone value={this.state.files} className="filedrag" onDrop={this.onDrop} onChange={this.changeValue}>
                    <div>Seleziona la immagine o trascinala nel riquadro</div>
                </Dropzone>
                {this.state.files ? <div className="fileUploaded"></div> : null}
            </div>
        );
    }
    });

     module.exports = DropzoneUpload;

The form:

     <Formsy.Form onValid={this.enableButton} onInvalid={this.disableButton} id="userProfile" ref="user-profile" className="user-profile">
        <DropzoneUpload getFile={this.getUserFileDragged} />
    </Formsy.Form>

**Comment by fabiosussetto** [comment]
As the error message says, you need to give your custom input a `name` property, so that Formsy can use that to build its internal state and keep track of the data:

```<Formsy.Form name="myFile" onValid={this.enableButton} onInvalid={this.disableButton} id="userProfile" ref="user-profile" className="user-profile">
    <DropzoneUpload getFile={this.getUserFileDragged} />
</Formsy.Form>
```

**Comment by cornerolive** [comment]
Ok, I'll try. Thank you!

**Comment by twisty** [comment]
`Form Input requires a name property when used`

I think this message could be clearer. For example, you may have an formsy component called `Input` in the form, but the error could be triggered by any of the other formsy components in the form.

Maybe the following would be better?

`Formsy components require a name prop`

Can send a PR if you like.

**Comment by 574196906** [comment]
import React from 'react'
import '../css/InputText.css'
import $ from 'jquery'
import Formsy from "formsy-react";
const WebCreate = React.createClass({
    mixins: [Formsy.Mixin],
    submit(){
        console.log('submit')
    },
    inVaildSubmit(){
        console.log('inVaildsubmit')
    },
    vaild(){
        console.log('vaild')
    },
    inVaild(){
        console.log('Invalid');
    },

    change(event) {
        this.setValue(event.currentTarget.value);
    },

    render() {
        return (
            <Formsy.Form onValidSubmit={this.submit.bind(this)}
                         onValid={this.vaild.bind(this)}
                         onInvalid={this.inVaild.bind(this)}
                         onInvalidSubmit={this.inVaildSubmit.bind(this)}>
                <div className='inputDiv'>
                    <input
                        type = 'text'
                        onChange={this.change.bind(this)}
                        className='input'
                        ref="myInput"
                        name='appName'
                        value={this.getValue()}
                        validations={{
                                   myCustomIsFiveValidation: function (values, value) {
                                        console.log('myCustomIsFiveValidation value'+value)
                                        if (value=="" || value==0) {
                                            return "请选择应用类型"; // You can return an error
                                        }
                                        else {
                                            return true;
                                        }
                                    }
                                }}
                        />
                    <input type="submit" className='submit_btn' value="创建应用"/>
                </div>
            </Formsy.Form>
        )
    }
});
module.exports = WebCreate;

@twisty  I've had the same problem, please help me to see why this is so.

**Comment by 574196906** [comment]
@Semigradsky please help me

**Comment by Semigradsky** [comment]
@574196906 you should use [own form element](https://github.com/christianalfoni/formsy-react#building-a-form-element-required) not just `input`. You can see example here: https://github.com/christianalfoni/formsy-react/blob/master/examples/components/Input.js
