### ISSUE TITLE
Custom validation based on other values within the form

### ISSUE THREAD

**Issue by tnrich** [christianalfoni/formsy-react#273]
Hey there, I'm wondering how to take into account the values of other inputs within the form when doing validation:

```
<Input1 />
<Input2 validations={function that depends on the value of Input1 as well}/>
```

**Comment by tnrich** [comment]
I think this should solve my problem(!): 
https://github.com/christianalfoni/formsy-react/blob/master/API.md#formsyaddvalidationrule

**Comment by Semigradsky** [comment]
Right! :)
