### ISSUE TITLE
Access to model in 'onValid'

### ISSUE THREAD

**Issue by tnrich** [christianalfoni/formsy-react#278]
Hey there, I'd like to have access to the form model in the "onValid" function, instead of waiting for the user to hit the submit button (which wouldn't exist in my specific use case). 

Is there a way to do that? 

Here's an example of what I'd like to work:

```js
           onValid={ 
                (model) => {
                  this.props.signals.pageCompleted({
                              model: model
                          }) 
                 
              }
```

**Comment by tnrich** [comment]
I think I found my solution from this question: https://github.com/christianalfoni/formsy-react/issues/45

```
testSubmit() {
  this.refs.form.submit(); // Point directly to the form component
},

render() {
  return (
    <Formsy.Form ref="form">
      {/* some inputs */}
    </Formsy.Form
  );
}
```

I think I can just trigger a manual submit that way. I'm not quite sure why the model wouldn't be provided in the onValid, onInvalid methods as well though? It would definitely make the above use case a lot cleaner.

Thanks!

**Comment by Semigradsky** [comment]
@tnrich Hi! Use [`getModel()`](https://github.com/christianalfoni/formsy-react/blob/master/API.md#getmodel) for taking values from attached inputs.
