### ISSUE TITLE
Declarative server errors

### ISSUE THREAD

**Issue by defrex** [christianalfoni/formsy-react#284]
Currently it seems the only was to add server errors is using the `invalidateForm` callback on the `onSubmit` handler. This works well in a simple case where the submission XHR is located there.

However, when things get a little more fluxxy, this callback stops working well.

For example,
```JS
class Login extends Component {
  static propTypes {
    fieldErrors: PropTypes.object,
  }

  handleSubmit(data) {
    store.dispatch(login(data));
  }

  render() {
    const { fieldErrors } = this.props;

    // ???

    return (
      <Form onValidSubmit={::this.handleSubmit}>
        <Input label='Email' name='email' type='email' validations='isEmail' required/>
        <Input label='Password' name='password' type='password' required/>
        <Button>Login</Button>
      </Form>
      <div>
    );
  }
}
```

In this login form example, the submit handler simply dispatches a redux action. It has no knowledge (and shouldn't have knowledge) of what that action does. All it knows is that if fieldErrors come back via props it should display them.

Right now there doesn't seem to be a way to display these field errors.

**Comment by Semigradsky** [comment]
Use [`updateInputsWithError`](https://github.com/christianalfoni/formsy-react/blob/master/API.md#updateinputswitherrorerrors)
