### ISSUE TITLE
Cannot reset value unless truthy

### ISSUE THREAD

**Issue by dsteinbach** [christianalfoni/formsy-react#285]
I think this line should be:
https://github.com/christianalfoni/formsy-react/blob/master/src/main.js#L145

```
if (data && data.hasOwnProperty(name)) {
```

**Comment by Semigradsky** [comment]
Yes, that makes sense

**Comment by Semigradsky** [comment]
Fixed in 6767a6b9eba9c0a7c255c46ce2d6f84dc69eeeb4
