### ISSUE TITLE
Further development

### ISSUE THREAD

**Issue by Semigradsky** [christianalfoni/formsy-react#301]
Hi!

@christianalfoni has no more time for the development of this project. He spends all his free time on coding for [Cerebral](http://www.cerebraljs.com/).

I decided forking this project and continuing development.
I am thinking about the title formsy, but any suggestions are welcome.
If you think that the current api smell too bad, now is the best time to change it.

Any comments and suggestions are welcome!

**Comment by kirkov** [comment]
Instead of forking it, maybe you can get write access, so we can keep this repo going ?

**Comment by poluyanov** [comment]
Formzy :)

**Comment by kirkov** [comment]
Great your are stepping in and continuing the development!
Regarding the name - I think the name is just fine :)

**Comment by jrm2k6** [comment]
Would it be possible for the original contributor to give full access to this repo to some other contributors? That would avoid having to move the repo around. It can be confusing for new users?

**Comment by twisty** [comment]
I may be wrong, but I think @Semigradsky already has write access to this repo?

There is enough improvement to justify a new release, but only @christianalfoni has the power to push releases on npm, and he has no time for formsy-react right now. This looks like a source of frustration that could be eased by adding another owner to the npm project.

Of course, this is @christianalfoni's project and he is at liberty to do as he wishes! If he has no more interest or time for this, or is unwilling or unable to grant others to push releases on npm, then forking is a natural progression. I'd rather It didn't come to this, though.

As for the name, how about `formsky-react` ;-)

**Comment by jrm2k6** [comment]
@twisty Yes this is what I meant! npm rights to be able to publish.
I would be more than willing to contribute if needed also!

**Comment by mbrookes** [comment]
Thanks to @christianalfoni for creating this library with such passion in the first place! :+1: 

@Semigradsky you've done a fine job of maintaining the library so far, so it's great news that you're picking it up.

It's perfectly possible to have [multiple users able to update npm](https://docs.npmjs.com/cli/owner), however if forking/moving the repo is part of the plan, it might make sense to move it under its own org (formsy?), so: formsy/formsy-react. A complete rename might be too confusing.

I would be happy for [formsy-material-ul](https://github.com/mbrookes/formsy-material-ui) to live there to.

**Comment by tylercollier** [comment]
@Semigradsky Where is your fork? I assumed https://github.com/Semigradsky/formsy-react but it's not there.

**Comment by rawrmaan** [comment]
@Semigradsky Where is your fork? I assumed https://github.com/Semigradsky/formsy-react but it's not there.

**Comment by ffxsam** [comment]
I'd be interested in knowing where the new fork is, as well as contributing where I can. IMO, it would be nice to ditch the mixin and make it a high-order function instead.

**Comment by tomzmtl** [comment]
@Semigradsky Do you have any news on this? We are considering using formsy but its development state may be a key in our decision.

**Comment by jamedranoa** [comment]
+1

**Comment by ffxsam** [comment]
I personally went with [react-redux-form](https://github.com/davidkpiano/react-redux-form) and highly recommend it!

**Comment by mbrookes** [comment]
@Semigradsky - you're obviously under no obligation to continue development of formsy-react, but it would be good to know what your plans are one way or the other. :+1:

**Comment by aight8** [comment]
Is there any news related to the future fork of this project?

**Comment by Semigradsky** [comment]
Hi for all! @twisty @mbrookes @sdemjanenko and other
@christianalfoni has promised to give me rights in npm.
This means that soon there will be a new version :smile_cat:

**Comment by Semigradsky** [comment]
Sorry for the long pause. The new version is [here](https://github.com/christianalfoni/formsy-react/releases/tag/v0.18.0)!

**Comment by gilbarbara** [comment]
@Semigradsky 
Maybe it's time to change formsy versioning to follow React's 15.x? :)

**Comment by Semigradsky** [comment]
You mean `formsy-react 15.0.0`?
I don't think it's really necessary.

**Comment by jackyon** [comment]
@Semigradsky  

still waiting for the feature:

onInvalid and onInvalidSubmit should pass a map of input names and their errors

can you advise how or when this can be support? thx!

**Comment by eriklharper** [comment]
fwiw, I think this project is quite valuable, as its been versatile in many types of form scenarios that I've used it in.  Thanks @Semigradsky for picking up the baton on it.  I will continue to support the project any way I can :)
