### ISSUE TITLE
onInvalidSubmit is not called, when form is submitted with required field left empty

### ISSUE THREAD

**Issue by SaitejaP** [christianalfoni/formsy-react#306]
When I cleared an required input, it shows error. When I submit the form, onInvalidSubmit is not called. Errors are shown for browser's default validation. What should I do get `notifyFormError` called when invalid form is submitted?

`<Formsy.Form onValidSubmit={this.submitForm} onInvalidSubmit={this.notifyFormError}  onSubmit={this.onSubmit}></Formsy.Form>`

**Comment by jackyon** [comment]
+1

**Comment by cdroulers** [comment]
Have you tried adding the `noValidate` attribute to your `<Formsy.Form>` element? I think that's what fixed this for me.

**Comment by keul** [comment]
I've a similar issue with version 0.17.0: I use "required" attribute on formsy fields but I disabled the browser validation adding `noValidate` on form.

This prevents the browser to manage required data by default but at the same time required field are not checked at all by formsy.
As soon as I put data inside the field, other validations runs normally.

**Comment by aesopwolf** [comment]
@SaitejaP I would recommend trying @keul's solution. It's what I use myself.
