### ISSUE TITLE
How to retrieve ref to input when HOC used

### ISSUE THREAD

**Issue by miguel-guedes** [christianalfoni/formsy-react#308]
When defining an input class as lower order component of Formsy, how does one go about retrieving a ref to the underlying input component?

If an input class is simply:

``` javascript
class Input {
  render() {
    return (<div><label ...props>{this.props.caption}</label><input ...props/></div>);
}

export default Formsy.HOC(Input);
```

And the form:

``` javascript
class AForm {
  componentWillReceiveProps() {
    // How to access the input component? this.refs.input refers to the HOC of Input.
  }

  render() {
    return (
      <Form>
        <Input ref="input" ...props/>
      </Form>
    );
  }
}
```

Say I would like the Input class to allow for the focus to be set programmatically on its {input,textarea} element; how would I go about doing so? How would such an interface be exposed from `Input` above?

**Comment by clayne11** [comment]
The HOC passes all props through to the component it is wrapping, so you can simply use a callback ref to achieve your goal.

https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute

**Comment by tjcampbell** [comment]
A few months late but @clayne11 I think you are mistaken. AFAIK with Formsy there is no way to access an external component API through refs when using the HOC. #341 brings up the same issue. I've seen some libraries implement a `getInstance()` function on their HOCs to return the inner component's instance. @Semigradsky is there a workaround?

**Comment by aesopwolf** [comment]
Thanks @tjcampbell for suggesting the idea of implementing `getInstance()`. I just submitted a PR that does exactly that. Feel free to chime in / do a peer review on https://github.com/christianalfoni/formsy-react/pull/399

**Comment by ggd543** [comment]
use **callback** instead. here is example

```js
class Foo extends React.Component {
  componentDidMount() {
     this.props.onRef(this);
  }

  render() {
     return 
  }
}
export default Foo;
```
```js
import Foo from './foo';

class App extends React.Component {
   render() {
     <Foo onRef={foo => this.foo=foo} />
  } 
}
```

**Comment by eliassotodo** [comment]
> use callback instead. here is example

`Foo` and `App` are not HOC @ggd543

**Comment by wende60** [comment]
Thanks to @ggd543 for this solution. To show how it works with a HOC:
Create an object to store the references in the parent component...

`this.myRefs = {};`

... and add this to your wrapped component in your parent component:

`<MyComponentWithinHoc onRef={item => { this.myRefs[myKey] = item; }} />`

item will contain the reference you need. Now add this to the HOC

```
componentDidMount() {
    if (this.props.onRef) {
        this.props.onRef(this.ref);
    }
}
```
And this to it's render method:

```
return this.props.onRef
    ? <WrappedComponent ref={node => { this.ref = node; }} {...this.props} />
    : <WrappedComponent {...this.props} />;
```

enjoy, jo

**Comment by eightHundreds** [comment]
My solution:
```
const withXXXXX = (WrappedComponent) => {
  class HOC extends React.Component {
    render() {
      return (
        <div >
              <WrappedComponent
                {...this.props}
                ref={(ref) => {
                  this.instance = ref
                }}
              />
        </div>
      )
    }
  }
  const lifeCircles = [
    'displayName',
    'propTypes',
    'contextTypes',
    'childContextTypes',
    'mixins',
    'statics',
    'defaultProps',
    'constructor',
    'getDefaultProps',
    'state',
    'getInitialState',
    'getChildContext',
    'getDerivedStateFromProps',
    'componentWillMount',
    'UNSAFE_componentWillMount',
    'componentDidMount',
    'componentWillReceiveProps',
    'UNSAFE_componentWillReceiveProps',
    'shouldComponentUpdate',
    'componentWillUpdate',
    'UNSAFE_componentWillUpdate',
    'getSnapshotBeforeUpdate',
    'componentDidUpdate',
    'componentDidCatch',
    'componentWillUnmount',
    'render'
  ]

  Object.getOwnPropertyNames(WrappedComponent.prototype).forEach((memberName) => {
    if (lifeCircles.indexOf(memberName) >= 0) {
      return
    }
    HOC.prototype[memberName] = function (...args) {
      this.instance[memberName](...args)
    }
  })
  return HOC
}
```
