### ISSUE TITLE
Add disabled prop to form itself

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/formsy-react#31]
Sometimes it is nice to disable the form itself. By adding a prop and a form element method to check for that prop we can achieve this.

**Comment by vladejs** [comment]
Is this implemented yet? I set `disabled={false}` prop to form but it doesn't work. I ask because this issue is closed

**Comment by aesopwolf** [comment]
`disabled={false}` doesn't make any sense, try `disabled={true}`
