### ISSUE TITLE
"webpack-dev-server --content-base build" is failing.

### ISSUE THREAD

**Issue by hevar** [christianalfoni/formsy-react#312]
Hi,

I've cloned the repo. installed the npm packages but when i try to run "npm start" i get error.

**Here is the error message:**
`

> formsy-react@0.17.0 start /Users/hevmag/Projects/test/formsy-react-master
> webpack-dev-server --content-base build

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at net.js:1382:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE
npm ERR! formsy-react@0.17.0 start: `webpack-dev-server --content-base build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formsy-react@0.17.0 start script 'webpack-dev-server --content-base build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the formsy-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --content-base build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs formsy-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls formsy-react
npm ERR! There is likely additional logging output above.`

**And the NPM debug log:**

[Pastebin](http://pastebin.com/TyC44MBZ)

**Comment by mikedizon** [comment]
+1

**Comment by davidpelayo** [comment]
+1 same here!

**Comment by hevar** [comment]
Well, I guess no one cares....

**Comment by tal952** [comment]
+1

**Comment by hiro1107** [comment]
I got the same error.

**Comment by hevar** [comment]
**I solved it by:**

1. Remove the `/tmp ` folder (suggested by @hiro1107 ), or you can simply reboot your computer.
2. `rm -rf node_modules` (deleten all npm packags)
3. `npm cache clean` (clearing the cache)
4. `npm run start`. You can replace `start` with one of the other scripts (`deploy`, `test`, `examples` and `prepublish`) depending on what you want to do.

**Comment by dsaket** [comment]
I removed the `/tmp` folder and my chrome crashed and then it refused to restart. Then when I tried rebooting, my system got stuck in a login loop.

I think simply rebooting could have done the work.
