### ISSUE TITLE
Why the the getModel function didn't exist in the npm package of formsy-react 

### ISSUE THREAD

**Issue by liuyutao** [christianalfoni/formsy-react#316]

**Comment by megapctr** [comment]
:+1: I had the same problem.

Turns out this feature hasn't been released yet, but documentation already mentions it.
@christianalfoni any plans for a new release?
Also, linking to documentation from latest release in the readme file (instead of master) would be very useful IMO

**Comment by megapctr** [comment]
@liuyutao for now you can reproduce the behavior of `getModel` manually:

```
getModel: function () {
  var currentValues = this.getCurrentValues();
  return this.mapModel(currentValues);
},
```
Though I'm not sure why calling `getCurrentValues` is not enough? what does `mapModel` do?

**Comment by naoyeye** [comment]
same problem.

thanks @megapctr

**Comment by liuyutao** [comment]
@megapctr thanks your help.

**Comment by Semigradsky** [comment]
Sorry for the long pause. Formsy-react updated, check new version.
