### ISSUE TITLE
Dynamic validationError messages

### ISSUE THREAD

**Issue by sdemjanenko** [christianalfoni/formsy-react#32]
It would be really cool if I could show different validationError messages depending on which validation(s) failed.

**Comment by christianalfoni** [comment]
Yeah, that would be awesome. Starting to work on next release tomorrow:

```javascript
<MyInput validationError={{email: 'whatup', foo: 'bar'}}/>
```

Just makes sense :-) You think so too?

**Comment by sdemjanenko** [comment]
I was thinking about supporting keys based on the validation rule name:
`validationError={ {isAlpha: "Must be letters."} }`

**Comment by christianalfoni** [comment]
Jup, thats what I wrote too? :-)

**Comment by sdemjanenko** [comment]
Cool.  I wasn't sure since I wasn't clear what `email` and `foo` were.

**Comment by christianalfoni** [comment]
Ah, yeah, hehe, sorry. Will implement this for next version. Thanks for a great input!

**Comment by christianalfoni** [comment]
Is included in next version

**Comment by sdemjanenko** [comment]
This doesn't seem to be working.  When I do `validationError ={ {isLength: "Maximum length of 64 characters", isNodeName: "Only letters, numbers, spaces, and common punctuation"} }`

and I put "5 D3 Carnage&" in the field, I see "Maximum length of 64 charactersOnly letters, numbers, spaces, and common punctuation" rendered as an error message.  It should not render the message about maximum length.

**Comment by christianalfoni** [comment]
Ah, sorry, I confused this with a different issue. Will implement very soon :-)

**Comment by jhampton** [comment]
Quick question - would it be possible to allow validate.js, validator, verify.js, or another third-party validation library in place of the default validator?  That might alleviate a lot of the burden of handling validation (and you get server-side/client-side validation parity for free with the above).

Cheers, and thanks for the great work!

**Comment by christianalfoni** [comment]
Hi!

Yeah, it was a usability decision there. Please give me a comment on how it went converting the rules. Maybe we can find a solution here :-)

**Comment by christianalfoni** [comment]
@jhampton You know, the next release has a `validationsError` prop on the form which can be used for external validation tools. Will give an example in next release which is right around the corner :-)
