### ISSUE TITLE
Upgrade to react ^15.0.1

### ISSUE THREAD

**Issue by r-tock** [christianalfoni/formsy-react#324]

**Comment by copas2** [comment]
This definitely needs to be changed in /src/Mixin.js since undefined values of input components result in uncontrolled components in v15.
```
  getValue: function () {
    return this.state._value || "";
  },
```

**Comment by SachaG** [comment]
Is this package still maintained? Or is there a more active fork somewhere?

**Comment by mikeerickson** [comment]
Seems to be not actively maintained, but still works as intended.

**Comment by stupidisum** [comment]
Somebody is doing this?

**Comment by Semigradsky** [comment]
Sorry for the long pause. Formsy-react updated, check new version.

**Comment by SachaG** [comment]
Awesome work!
