### ISSUE TITLE
Please upgrade to material-ui 15.0.0.beta1

### ISSUE THREAD

**Issue by dlivas** [christianalfoni/formsy-react#325]
Please upgrade to material-ui 15.0.0.beta1,
Many thanks

**Comment by mbrookes** [comment]
@dlivas - wrong repo, material-ui support is over here: https://github.com/mbrookes/formsy-material-ui, and the material-ui 0.15.0 branch is here: https://github.com/mbrookes/formsy-material-ui/tree/mui-0150
(but broken ATM)

**Comment by dlivas** [comment]
@mbrookes - many thanks! is there a tag for material-ui 0.15.0 that I could use in my package.json? for material-ui 0.15.0? 
I need to do something like 
npm --save install formsy-material-ui@x
what x can I use?

many thanks!

**Comment by mbrookes** [comment]
@dlivas material-ui:0.15.0-beta.1@next IIRC, but please close this issue - it's unfair on the maintainers of this unrelated repo.

**Comment by Semigradsky** [comment]
Formsy-react dependencies updated. Now there should be no error messages during installation.
