### ISSUE TITLE
Missing a way to limit values passed to onSubmit

### ISSUE THREAD

**Issue by keul** [christianalfoni/formsy-react#329]
When using `onSubmit` API (https://github.com/christianalfoni/formsy-react/blob/master/API.md#onsubmitdata-resetform-invalidateform) the first `data` arguments are all of the fields in the form.

Sometimes on complex forms you don't want to manage/send all of the field you receive (a simple example: a password confirmation field is not useful on submit but checked on validation).

So maybe a way to define a field as "not submittable" can be useful, for example:

    <Input ... 
              submit={false}

In that way the `values` object will only contains fields where submit is true (the default BTW).

**Comment by Semigradsky** [comment]
@keul you can use [`mapping`](https://github.com/christianalfoni/formsy-react/blob/master/API.md#mapping) for define only fields you want.

**Comment by keul** [comment]
@Semigradsky I missed this feature!
Thanks
