### ISSUE TITLE
Issue with react v15 - uncontrollable/controllable components

### ISSUE THREAD

**Issue by larstadema** [christianalfoni/formsy-react#332]
When rendering a custom component, the component gets rendered without a value. When you start typing, it gets a value, thus changing to a controllable input. I think the source of the problem is with the getValue() function. Which might need to be changed to: 

`getValue: function () {
    return this.state._value || "";
  }
`

Not sure if this alone will fix it though. Haven't had this issue in v0.17.

This is the error message I receive:
_warning.js:44 Warning: TextField is changing a uncontrolled input of type email to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components_

**Comment by zimt28** [comment]
Same issue

**Comment by twisty** [comment]
Also see: https://github.com/erikras/redux-form/issues/735

**Comment by twisty** [comment]
I think something like @zimt28's defensive fix is the way to go; changing `getValue` to return an empty string wouldn't be useful for components that don't expect a "texty" type of value.

If you're passing the `getValue()` value directly to your form control element, you could set a `defaultProp` of `''` (empty string) for `value` in your component?

**Comment by andreechristian** [comment]
+1

**Comment by uzarubin** [comment]
Just wanted to point out that it's `this.getValue()` instead of `props.getValue()`

**Comment by JosephClay** [comment]
@uzarubin The HOC will attach the methods to `props`, the mixin to `this`.

**Comment by track0x1** [comment]
+1
Why is this not part of formsy-react's default return for `getValue()`?

**Comment by aesopwolf** [comment]
When using your component you should provide a `value` attribute to suppress the React warning about "elements should not switch from uncontrolled to controlled ". For example:

```jsx
<MyInput value="" name="password" title="Password" type="password" required />
```
