### ISSUE TITLE
onValidationComplete not called when form has no inputs

### ISSUE THREAD

**Issue by dave-clover** [christianalfoni/formsy-react#343]
We're having an issue with a specific form.  We have a single field on this form, which is a required field.  If you leave it empty, the form is correctly marked as invalid.  We then dynamically remove the field, leaving the form empty but still invalid.  The seems like a bug.  It happens because `onValidationComplete` is never called in `detachFromForm` when there are no more inputs in the form.

See line: https://github.com/christianalfoni/formsy-react/blob/master/src/main.js#L380

It seems like `onValidationComplete` should be manually called during the detach when there are no fields on the form.

I can submit a PR if we decide this needs to be fixed.  Thoughts?

Edit: We are using version 0.17.0.

**Comment by Semigradsky** [comment]
Yes, it should be fixed
