### ISSUE TITLE
Value not updated when flux store changes

### ISSUE THREAD

**Issue by jonaswindey** [christianalfoni/formsy-react#35]
I have an object on my flux store (user) that is initially an empty object but gets filled with an async call.

When I just print the _id, it gets rendered correctly and updates as the state changes. However, when I set it as value of my form component, it doesn't get updated and stays an empty value.

```
<span>Id: {this.state.user._id}</span>
<Formsy.Form className="form-horizontal" 
    onSubmit={this.submit} 
    onSuccess={this.changeUrl} 
    onValid={this.enableButton} 
    onInvalid={this.disableButton}>
    <ElementInput type="text" label="Exhibitor name" 
      name="exhibitorName" value={this.state.user._id}/>
</Formsy.Form>
```

When I use a regular <input> without Formsy, the value is also correctly updated when my state changes. (My ElementInput is the same as in the example)

Any ideas how I can make the Formsy form 'listen' to the change of my state? I'm using Fluxxor as flux implementation.

Thanks

**Comment by jonaswindey** [comment]
Did some further investigation (especially #11), and when I set 
```value={this.state.user._id || ''}```
it works correctly. Is there a way to avoid having to set a default value?

**Comment by christianalfoni** [comment]
Checking this out for the next release :-)

**Comment by christianalfoni** [comment]
This should work with version 0.8.0
