### ISSUE TITLE
error in form-data object 

### ISSUE THREAD

**Issue by fthamura** [christianalfoni/formsy-react#351]
is the form object data has been deleted?

mervo@Mervium:~/electron/formsy-react$ npm install
npm ERR! fetch failed https://registry.npmjs.org/form-data-to-object/-/form-data-to-object-0.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/form-data-to-object/-/form-data-to-object-0.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/form-data-to-object/-/form-data-to-object-0.2.0.tgz
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6

**Comment by Semigradsky** [comment]
nope https://www.npmjs.com/package/form-data-to-object

Looks like npm problem. Try again.
