### ISSUE TITLE
validation onSubmit

### ISSUE THREAD

**Issue by keown** [christianalfoni/formsy-react#358]
question: is there an easy way (without writing custom components for every form field) to validate the form onSubmit? i can't figure out how to do it! :-(

**Comment by donaldparker** [comment]
I could use this, fields that are auto-completed are not marked as valid. I've reported the issue here #356

**Comment by ivanoats** [comment]
Any tips on where to start on a P.R. for this?

**Comment by aesopwolf** [comment]
@keown Sorry, formsy requires you to write custom components. Have you looked through the examples or read the README? I'm going to close this since this isn't an issue with formsy itself. This type of question would be better suited for stackoverflow.
