### ISSUE TITLE
input value getting this.getValue() displays a React warning on console

### ISSUE THREAD

**Issue by matmarsiglio** [christianalfoni/formsy-react#359]
Following this guy [here](https://github.com/christianalfoni/formsy-react/blob/master/examples/components/Input.js), the `input` receives a `value` like the example: `value={this.getValue()}`, but my console prints this React ~error~ warning:

`Warning: InputAutocomplete is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components` 

Is this a React update that made it be a bug on Formsy or there is any secret magic for fix it?

**Comment by chmanie** [comment]
I was confronted with this error message after upgrading to react 15.

**Comment by matmarsiglio** [comment]
They solved this for now on this [issue](https://github.com/christianalfoni/formsy-react/issues/332). 👍
