### ISSUE TITLE
Add "FieldSet" mixin

### ISSUE THREAD

**Issue by sdemjanenko** [christianalfoni/formsy-react#36]
It would be cool if a component could represent a "field set".  An example of what I mean:

```javascript
var ScopedInput = React.createClass({
  mixins: [Formsy.FieldSetMixin],
  render: function() {
    return <div>
      <MyInput name="foo" value={...} />
      <MyInput name="bar" value={...} />
    </div>;
  }
});

var ConfigureForm = React.createClass({
  render: function() {
    return <Formsy.Form ...>
      <ScopedInput name="one" />
      <ScopedInput name="two" />
    </Formsy.Form>
  }
});
```

The `ConfigureForm`'s value would look like:
```javascript
{
  one: {foo: ..., bar: ...},
  two: {foo: ..., bar: ...}
}
```

The basic idea would be any `Formsy` mixed inputs in a `Formsy.FieldSet` mixed component would be namespaced within the parent form.  This would also support namespacing within the namespace (nesting).

**Comment by christianalfoni** [comment]
Hi @sdemjanenko , you have lots of ideas, great! :-)

So what you are suggesting here is the need for having a reusable set of inputs that would namespace their names? So in your example the inputs would be:

- one.foo and on.bar
- two.foo and two.bar

?

You should be able to solve this with just plain React and Formsy though?

```js
var ScopedInput = React.createClass({
  mixins: [Formsy.FieldSetMixin],
  render: function() {
    return <div>
      <MyInput name={this.props.name + 'foo'} value={...} />
      <MyInput name={this.props.name + 'bar'}  value={...} />
    </div>;
  }
});

var ConfigureForm = React.createClass({
  render: function() {
    return <Formsy.Form ...>
      <ScopedInput name="one" />
      <ScopedInput name="two" />
    </Formsy.Form>
  }
});
```

I think a mixin hides too much implementation details, unless I am misunderstanding something here of course :-)

**Comment by sebas5384** [comment]
@christianalfoni, I have the same need.
My ScopedInput is a reusable component input that haves to work with Formsy, for example a dependent dropdown/selects widget.

**Comment by christianalfoni** [comment]
Hi guys,

Sorry that I do not quite understand why you need this ;-) You have a couple of more examples?

To namespace inputs I would suggest as the example above:

```js
var ScopedInput = React.createClass({
  mixins: [Formsy.Mixin],
  render: function() {
    return <div>
      <MyInput name={this.props.name + 'foo'} value={...} />
      <MyInput name={this.props.name + 'bar'}  value={...} />
    </div>;
  }
});

var ConfigureForm = React.createClass({
  render: function() {
    return <Formsy.Form ...>
      <ScopedInput name="one" />
      <ScopedInput name="two" />
    </Formsy.Form>
  }
});
```

But I think there is something I do not quite get here maybe? Would be great with some more code examples :-)

**Comment by sebas5384** [comment]
@christianalfoni thanks for response :)
In my case, the <MyInput> component, is a Formsy input too, that we use in all forms.

**Comment by christianalfoni** [comment]
Hm hm, do you have some example code @sebas5384? I have a feeling I am misunderstanding? Or does my example above solve the issue? :-)

**Comment by christianalfoni** [comment]
Nested inputs are implemented in last version. name="foo.bar" = {foo: {bar: VALUE}}
