### ISSUE TITLE
Way to disable the submit event triggered by pressing the enter key while focusing an input field

### ISSUE THREAD

**Issue by TylerYang** [christianalfoni/formsy-react#360]
Hi folks, let's say I have a `Formsy-React Form` and  **when the use typing down the characters, the `submit` event can be triggered by pressing the <kbd>Enter</kbd> button.**

Is there a way to disable this functionality?

 I understand this is a feature for `form` element(Trigger by pressing the <kbd>Enter</kbd> button). And I don't want to bind events to each input fields, that doesn't make sense, especially when you have lots of inputs and other elements.

**Comment by Semigradsky** [comment]
```js
...
onKeyPress(event) {
    if (event.which === 13 /* Enter */) {
      event.preventDefault();
    }
},
render() {
  return (
      <Form onKeyPress={this.onKeyPress} ...
...
```

**Comment by TylerYang** [comment]
That's cool. Thx.

**Comment by shahrajat** [comment]
@Semigradsky Won't be a good solution when you have text-area element in the form.

**Comment by valentecaio** [comment]
Thanks @Semigradsky ! it worked for me!

**Comment by martinlex** [comment]
I have tried several different approaches for this specific problem, this is the only thing that works. Tip: make sure to apply `type="button"` for buttons in the form. Thank you!

**Comment by anup88born** [comment]
@martinlex@  
I work on ReactJs and Javascript.
Earlier on pressing "Enter" forgot password dialog was opening before logging into next page.
I saw the Button type="submit" . I changed it to  type="button" and the enter key stopped popping up the forgot password each time. Issue resolved. Thanks!
