### ISSUE TITLE
React 15.2 seriously breaks formsy

### ISSUE THREAD

**Issue by martinhbramwell** [christianalfoni/formsy-react#363]
[06:19:50.068] "Warning: Unknown props `layout`, `validatePristine`, `validations`, `validationError`, `validationErrors`, `addonBefore`, `addonAfter`, `buttonBefore`, `buttonAfter` on <input> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
        in input (created by Input)
        in div (created by Row)
        in Row (created by Input)
        in Input (created by _form)
        in fieldset (created by _form)
        in form (created by Formsy)
        in Formsy (created by _form)
        in _form (created by Container(_form))
        in Container(_form) (created by UseDeps(Container(_form)))
        in UseDeps(Container(_form)) (created by _class)
        in div (created by _class)
        in div (created by _class)
        in div (created by _class)
        in div (created by _class)
        in _class (created by _class)
        in div (created by _class)
        in div (created by _class)
        in _class (created by WithDeps(_class))
        in WithDeps(_class)"

Please have a look at : 

 [ React 15.2 Unkown Prop Warning #517 ](https://github.com/Hacker0x01/react-datepicker/issues/517)

**Comment by Semigradsky** [comment]
Looks like problem in `formsy-react-components`. Please open issue in [that repo](https://github.com/twisty/formsy-react-components)

**Comment by twisty** [comment]
Is this is a warning in both production and development mode? Does it still work on production mode? I'll look into this, of course, but apart from the warning is anything actually "seriously broken" in production mode?

**Comment by martinhbramwell** [comment]
I have no prior experience with `formsy` and only a little bit of experience with the app that uses it.  The bug is certainly a complete show stopper, but that may simply be due to poor exception handling, I do not know.  

Facebook has changed the rules about passing properties to React components.  When I saw that, and saw `formsy's` dependence on passing non-React properties into form components, I did not investigate further. 

The failure is in the v0.2.1 branch of [this repo](https://github.com/warehouseman/meteor-mantra-kickstarter) if you want to see it "in-the-wild".  (Installation instructions are at the bottom of the README)

**Comment by twisty** [comment]
Hi @martinhbramwell, thanks for the detail. It's pretty easy to reproduce. I've added an issue [over here](https://github.com/twisty/formsy-react-components/issues/80). This should be okay to close here, I think.

**Comment by martinhbramwell** [comment]
Ok.  As far as I'm concerned I am trapped at React 15.1.  If I try to upgrade to 15.2 then `formsy` **seems** to kill my app.  Possibly Facebook's changes are killing some other thing that fails to throw a visible exception.
I don't know, I haven't been able to determine what's really going on.

**Comment by albertotorresfoltyn** [comment]
Why is that closed if is not fixed yet? (I stilll have the issue by the way, but i've settled for 15.1 for now)

**Comment by Semigradsky** [comment]
@albertotorresfoltyn just update `formsy-react-components`
