### ISSUE TITLE
Example of using onSubmit's resetForm(); (i.e. "second argument will reset the form")

### ISSUE THREAD

**Issue by acomito** [christianalfoni/formsy-react#368]
There is an example of resetting the form, but uses an onClick instead of the onSubmit. 

https://github.com/christianalfoni/formsy-react/blob/master/API.md#onsubmitdata-resetform-invalidateform

and some more talk-- but not example of the `resetForm();` -- here

https://github.com/christianalfoni/formsy-react/issues/15

I've tried a few different ways, but can't seem to get it. I've passed the reset function as a parameter and have access to it, but I'm not clear on what I pass the reset. Should I be passing the `data` parameter to `resetForm();` ? or a `ref` of the field name? When I log it I see some data gets passed:

```
function resetModel(data) {      
    this.inputs.forEach(function (component) {  ...
```

**Comment by Semigradsky** [comment]
Did you look `reset-values` example in [examples](https://github.com/christianalfoni/formsy-react/tree/master/examples)?

**Comment by acomito** [comment]
I couldn't get it working. I'm using the material-ui version, so maybe it is related to that. I forget the work around I used but will post it when I have the project open again... I'll close this for now.

**Comment by acomito** [comment]
I can't seem to get reset to work. I'm trying it like in the examples, and this.refs.form.reset() is running, but nothing is resetting and it doesn't throw any errors.

**Comment by acomito** [comment]
aaaaaand I forgot to pass it an initial value like `value=''`
