### ISSUE TITLE
Uncaught TypeError: Cannot read property 'React' of undefined

### ISSUE THREAD

**Issue by giovannicode** [christianalfoni/formsy-react#370]
I am getting this error when I try to import formsy-react
`Uncaught TypeError: Cannot read property 'React' of undefined`

I am using react, with babel and webpack. Everything works fine, but when I add this
import line, i get the error above

`import Formsy from 'formsy-react';`

The babel compilation works fine, I only get the above error in the browser, and everything just comes up blank.

Here is a sample of my webpack.config.js file:

```
var path = require("path");

module.exports = {
  resolve: {
    extensions: ['', '.js', '.jsx'],
    root: [
      path.resolve('./company/company/jsx'),
      path.resolve('./company/company/static/css/mockup-css/src'),
    ],
  },
  entry: {
    'signup_page': './company/company/jsx/signup_page.jsx',
  },
  output: {
    path: __dirname + '/company/company/static/js',
    filename: "[name].js"
  },
  module: {
    loaders: [
      {
        test: /\.jsx$/,
        include: __dirname + '/company/company/jsx',
        loader: "babel-loader"
      },
      {
        test: /\.scss$/,
        include: __dirname + '/company/company/static/css',
        loaders: ["style", "css", "sass"]
      }
    ]
  }
}

```

React and the rest of my app works fine, I only get the error once I try to import formsy.

Im new to the webpack/module-bundler workflow, so I might be missing something obvious

**Comment by Semigradsky** [comment]
Did you have imported  `React` before `formsy-react`?

**Comment by giovannicode** [comment]
Yea I did,
I simplified the example and created a git repo to replicate the issue.
https://github.com/giovannicode/formy-import-test

The app breaks when I try to import formsy-react, but if I comment it out, the app will work fine

**Comment by Semigradsky** [comment]
@giovannicode hi! I have checked your example. Fix for it: https://github.com/giovannicode/formsy-import-test/pull/1
