### ISSUE TITLE
Unknown props `validationError`, `validationErrors`, with React 15.2.0

### ISSUE THREAD

**Issue by CrazyDeveloper** [christianalfoni/formsy-react#371]
After updating to React 15.2.0 we encountered warning like this:
" Warning: Unknown props `validationError`, `validationErrors` on <select> tag"

For input field I get even more errors: 
Unknown props "`layout`, `validations`, `validatePristine`, `addonBefore`, `addonAfter`, `buttonBefore`, `buttonAfter`" on <input> tag
React has removed DOM whitelist checking upon render as part of optimization. 

Maybe the least painful would be to mark them as data-validationError...

**Comment by Semigradsky** [comment]
@CrazyDeveloper see https://github.com/twisty/formsy-react-components/issues/80

**Comment by CrazyDeveloper** [comment]
It works like a charm. Npm didn't pulled latest formsy-react-components
