### ISSUE TITLE
Validation for numbers fail because of string conversion 

### ISSUE THREAD

**Issue by timothyallan** [christianalfoni/formsy-react#373]
Hey gang, 

I've copied the sample under validations at [https://github.com/christianalfoni/formsy-react/blob/master/API.md](url) :

```
<MyInputComponent name="number" validations={{
  myCustomIsFiveValidation: function (values, value) {
    return 5 === value ? true : 'No five'; // You can return an error
  }
}}/>
```

and I've found that it always fails because the value always comes back as a string, "5", not an integer, 5. Am I missing a trick, other than a parseInt, or is the example incorrect?

**Comment by Semigradsky** [comment]
There are no any conversions. If you want validate numbers you should set numbers. https://github.com/christianalfoni/formsy-react/blob/master/API.md#setvalue

Something like this:
```js
    changeValue(event) {
		var value = event.currentTarget.value;
        value = parseInt(value, 10);
        this.setValue(value);
    },
```
