### ISSUE TITLE
A few questions on validation rules

### ISSUE THREAD

**Issue by wlingke** [christianalfoni/formsy-react#376]
1) What is the difference between `required` and using `validations:"isExisty"`?
2) What is passed into "values" parameter when writing a validation rule?

Thanks!

**Comment by Semigradsky** [comment]
1) `isExisty` returns true if the value is not undefined or null
`required` failed when values is `undefined` or empty string
2) Others form inputs values. See cross input validation example here: https://github.com/christianalfoni/formsy-react/blob/master/API.md#formsyaddvalidationrule
