### ISSUE TITLE
How can I jump to a invalid field ?

### ISSUE THREAD

**Issue by im-fortech** [christianalfoni/formsy-react#385]
Hello,

I have a very long form and I want to jump to a field that is invalid.

Any ideas?

Thank you

**Comment by Semigradsky** [comment]
1. Check validation and requirements on inputs. Get first failed.
2. Get top position of failed input. `el.getBoundingClientRect().top + window.scrollY`
3. Scroll to it. `window.scrollTo(0, topPosition)`

**Comment by im-fortech** [comment]
Thank you.
