### ISSUE TITLE
Formsy React Components Input focus

### ISSUE THREAD

**Issue by MHerszak** [christianalfoni/formsy-react#387]
This is not really an issue it is more of a question but I didn't know where to ask so I thought I would open an issue. I want to add the focus on:

```
componentDidMount(){
   ReactDOM.findDOMNode(this.refs.nameInput).focus();
}
```

and the form looks like this:

```
<Formsy.Form onChange={this.handler}
                     ref="nameForm">
    <Input
              ref="nameInput"
              name="name"
              value={this.state.name}
              placeholder="Please type your name.."
              type="text"
              layout="elementOnly"
              addonBefore={<Icon name="person"/>}
          />
</Formsy.Form>
```

How can I set the focus for nameInput?

**Comment by plitex** [comment]
I'm facing the same problem...

**Comment by twisty** [comment]
This isn't an issue for `formsy-react`. Opened new issue at https://github.com/twisty/formsy-react-components/issues/92.

Should be okay to close this here.

**Comment by MHerszak** [comment]
@twisty thanks. Can you please leave a comment here when this issue has been resolved?

**Comment by twisty** [comment]
This should do it:

```jsx
componentDidMount(){
   this.refs.nameInput.element.focus();
}
```

See: https://github.com/twisty/formsy-react-components/releases/tag/v0.8.0
