### ISSUE TITLE
Rewrite readme mixin example to use Higher Order Component

### ISSUE THREAD

**Issue by morenoh149** [christianalfoni/formsy-react#395]
Hello, I see the readme demonstrates how to [build a form element](https://github.com/christianalfoni/formsy-react/#building-a-form-element-required). However it utilizes the `mixins` field.

Now that [mixins are considered harmful](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html#solution-revisited) would a rewrite of the example in the readme be welcome?

**Comment by aesopwolf** [comment]
Ah, yes! This has been on my todo list for a long time.

**Comment by Jareechang** [comment]
@aesopwolf and @morenoh149 any progressive with this ? If not, I could help with this!

**Comment by morenoh149** [comment]
@Jareechang I'd submit a quick PR and link here a gist. I'm sure 20 other folks would appreciate it even if the maintainers choose never to change the readme. Sadly I've lost the context I had when I opened this issue :p

**Comment by Jareechang** [comment]
@morenoh149, ok. I'll go ahead and do that. 

up to date documentation / examples = ❤️  for developers!

**Comment by aesopwolf** [comment]
@Jareechang I haven't made an progress with this. I'll gladly accept a PR though!

**Comment by morenoh149** [comment]
With the announced changes in v16 this will become a more pressing topic https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by Jareechang** [comment]
Sorry for being late on this one. I am currently updating the DOCS and examples with new syntax which hopefully would help! PR coming soon, stay tuned peeps!

**Comment by Jareechang** [comment]
if anyone is interested is still stuck on how to convert away from using mixins, see my PR at #449. It provides an example of this. Feel free to reach out to me if you are stuck.

**Comment by rkuykendall** [comment]
This issue has been **SOLVED** in the new `formsy` organization with Formsy `1.0.1`: https://github.com/formsy/formsy-react/issues/2
