### ISSUE TITLE
Exception during instantiation

### ISSUE THREAD

**Issue by mschipperheyn** [christianalfoni/formsy-react#4]
Uncaught TypeError: Cannot read property '_mockedReactClassConstructor' of undefined

    var LoginForm = React.createClass({
	mixins: [ReactIntl.Mixin],
	render: function() {
	
		var passwordHint = <a href="{config.baseUrl}/registration/forgotpassword/">{this.getIntlMessage('ui.forgotpassword')}</a>;

		return (
			<div className="panel panel-default">
				<div className="panel-heading panel-title text-center">{this.getIntlMessage('ui.login')}</div>
				<div className="panel-body">
					<Formsy.form action="{config.baseUrl}/j_spring_security_check/" method="post" submitButtonClass="btn btn-default">
						<fieldset>
							<MSAInput type="email" name="j_username" label="E-mail" placeholder="E-mail" required/>
							<MSAInput type="password" name="j_password" label={this.getIntlMessage('ui.password')} hint={passwordHint} placeholder={this.getIntlMessage('ui.password')} required/>
							<input type="hidden" name="rememberMe" value="true"/>
						</fieldset>
					</Formsy.form>
				</div>
				<div className="panel-footer">
				<a href="/brasil/BR_pt/registration/register/" className="footer-link btn-info label-center">
					<span>{this.getIntlMessage('ui.button.register')}</span><span class="btn-label"><span class="icon icon-right-open"></span></span>
				</a>
				</div>
			</div>
		)
	}
    });

**Comment by mschipperheyn** [comment]
Sorry. Not an issue. Typo. I used Formsy.form and got a cryptic exception from React

**Comment by christianalfoni** [comment]
@mschipperheyn No worries, thanks for checking out the lib :-)
