### ISSUE TITLE
Validations running automatically

### ISSUE THREAD

**Issue by alexhawkins** [christianalfoni/formsy-react#418]
All forms are showing errors on initial load now. Can you please rollback as we are using this in production? Thanks.

**Comment by aesopwolf** [comment]
@alexhawkins thanks opening the issue. Would you mind taking a look at the discussion [here](https://github.com/christianalfoni/formsy-react/commit/57f97cb0459a539c0533e305dbd1bfd85ad1a02f)

Even if we rollback we're still contemplating re-releasing the breaking change in the next `0.20.x` release. So, it would be best practice for you to version lock your dependencies in production (especially for pre 1.0 releases).

Anyways, we will probably roll back before the end of the day. But it would be nice if you added your input at the above link just to help move forward.

Thanks, and sorry for pushing the breaking change.
