### ISSUE TITLE
onSubmit method doesn't know if the form is valid

### ISSUE THREAD

**Issue by sdemjanenko** [christianalfoni/formsy-react#42]
I feel that either onSubmit should not fire if the form is not valid or an argument should be passed to onSubmit which indicates the validity of the form.

**Comment by christianalfoni** [comment]
Yeah, you make a good point here. Though I think we get more flexibility by introducing: `onValidSubmit`and `onInvalidSubmit`. So `onSubmit` always fires. What do you think?

**Comment by sdemjanenko** [comment]
That seems reasonable.

**Comment by christianalfoni** [comment]
Allrighty, this is part of next release :-)
