### ISSUE TITLE
Password and confirmation password

### ISSUE THREAD

**Issue by IronTony** [christianalfoni/formsy-react#422]
Hi,
is there a way to check if the password and confirmation password are the same?

Thank you in advance

**Comment by twisty** [comment]
From the [API docs](https://github.com/christianalfoni/formsy-react/blob/master/API.md#validators):
```jsx
<MyInputComponent name="password"/>
<MyInputComponent name="repeated_password" validations="equalsField:password"/>
```

**Comment by IronTony** [comment]
Thank you very much, my bad!
