### ISSUE TITLE
Password validations to contain at least a number, uppercase, and minlength?

### ISSUE THREAD

**Issue by jackywhlee** [christianalfoni/formsy-react#425]
Is there a way to include 3 validation checks for the password field?

minLength serves its purpose, but isNumeric only allows the entire field to only be numerical, and there isn't an uppercase API method.

Uppercase seems overkill, but is there a hacky way to get the validations with at least 1 numerical character?

**Comment by lennardschutter** [comment]
You can create a custom validation rule with a regular expression.

**Comment by jackywhlee** [comment]
@lennardschutter Thanks, that would work. I assume there can only be 1 validationError text for 1 custom regex rule?

I.e., the user enters the required minimal characters, but doesn't have a number - and since this is a regex rule covering multiple validations, I'm assuming I'd have to create a generic error message for them.

**Comment by lennardschutter** [comment]
You can either create a single validation rule with a single error message
or you could create multiple custom validation rules, e.g. one to check
wether it contains an uppercase character, one for a number, etc.

**Comment by jackywhlee** [comment]
Interesting, thanks! Consider this closed!
