### ISSUE TITLE
Group of inputs depends in a checkbox

### ISSUE THREAD

**Issue by simiographics** [christianalfoni/formsy-react#44]
Any suggestion in how to implement this behavior? I have two checkboxes, and two groups of inputs/select, each group depends on each of the checkboxex, I'm trying to hide those groups if the checkbox is not selected.

Thanks

**Comment by christianalfoni** [comment]
Hi @simiographics ,

Formsy does support dynamic inputs. It should be possible in your form wrapper component to have custom logic for your checkboxes. When clicking them you render the different input groups. Formsy should notice this and change its internal model. 

did that make sense? I could give you an example if it seems a bit fuzzy :-)

**Comment by tnrich** [comment]
Hey @christianalfoni, can you or someone else give an example of this. I saw : https://github.com/christianalfoni/formsy-react/blob/master/examples/dynamic-form-fields/app.js

but it seemed a little complicated and I was wondering if there was perhaps a better way of doing it. Thanks!
