### ISSUE TITLE
Submitting form programatically

### ISSUE THREAD

**Issue by eriklharper** [christianalfoni/formsy-react#45]
I have a Form called `question1` that looks like this:

```
<Formsy.Form ref="question1" onSubmit={this.onSubmit} onSuccess={this.onSuccess} onValid={this.onValid} onInvalid={this.onInvalid}>
    <RadioButtonGroup name='user_type' options={options} class={classes} validationError="This is a required field." required />
</Formsy.Form>
```

Notice that I don't have a submit button.  This is intentional because I have an `app.jsx` parent component that includes a footer navigation bar that contains previous and next buttons for navigating through a questionnaire.  Each question is a separate form, starting with question1 above.

I'm using RefluxJS for communicating actions between `question1.jsx` and `app.jsx` so that when `app.jsx` calls the `submitQuestion1` action (as a result of the user clicking the *Next* button), `question1.jsx` listens on that action and calls its own custom `submit` method, which actually does the form submission as shown here:

```
/**
 * Question 1
 * Renders Question 1
 *
 * @prop null
 */
'use strict';

var $ = require('jquery');
var is = require('is_js');
var React = require('react');
var Reflux = require('reflux');
var Utilities = require('utilities');
var Actions = require('actions');
var Store = require('store');
var Formsy = require('formsy-react');

// Components
var RadioButtonGroup = require('../../components/radio-button-group/radio-button-group');

var Question1 = React.createClass({

  mixins: [
    Reflux.listenTo(Actions.submitQuestion1, "submit"),
  ],

  onSubmit: function (data) {
    console.log("This is not called... why?");
  },

  onSuccess: function (e) {

  },

  onValid: function (e) {
    this.setState({
      canSubmit: true
    });

    // Validate the Next Button
    Actions.enableNextButton();
  },

  onInvalid: function (e) {

  },

  submit: function () {
    if (this.state.canSubmit) {

      // Submit the Form
      $(this.refs.question1.getDOMNode()).submit();
    }
  },

  render: function () {

    var options = [
      {
        title: 'Mine',
        value: 'A'
      },
      {
        title: 'Child',
        value: 'P'
      }
    ];

    return (
      <div className='question1'>
        <Formsy.Form ref="question1" onSubmit={this.onSubmit} onSuccess={this.onSuccess} onValid={this.onValid} onInvalid={this.onInvalid}>
          <RadioButtonGroup name='user_type' options={options} class={classes} validationError="This is a required field." required />
        </Formsy.Form>
      </div>
    );
  }

});
```
This line `$(this.refs.question1.getDOMNode()).submit();` technically works, it submits the form, but my `onSubmit` function is not called even though it is specified here: `<Formsy.Form ref="question1" onSubmit={this.onSubmit} onSuccess={this.onSuccess} onValid={this.onValid} onInvalid={this.onInvalid}>`.  

Does Formsy support programmatic submission of forms?

**Comment by eriklharper** [comment]
Seems silly, but I got this to work by adding an invisible submit button and then triggering a click on it in my `submit` function:

Form:
```
<Formsy.Form id="question1" ref="question1" onSubmit={this.onSubmit} onSuccess={this.onSuccess} onValid={this.onValid} onInvalid={this.onInvalid}>
    <RadioButtonGroup name='user_type' options={options} class={classes} validationError="This is a required field." required />
    <button style={{display:'none'}} ref="question1button" type="submit" disabled={!this.state.canSubmit}>Submit</button>
</Formsy.Form>
```

Submit Function:
```
submit: function () {
    if (this.state.canSubmit) {

        // Submit the Form
        $(this.refs.question1button.getDOMNode()).click();
    }
}
```

**Comment by christianalfoni** [comment]
Hi @eriklharper ,

Aha, I see. Yeah, onSubmit should trigger when the form itself is programmatically triggered. Will check this out, keeping it open as a BUG. thanks and glad you worked it out :-)

**Comment by eriklharper** [comment]
Thanks @christianalfoni for looking into that, will be interested to see the solution!  I'll look into things on my end here as well.

**Comment by christianalfoni** [comment]
Hi @eriklharper,

Have you tried not wrapping in jQuery? This seems to work on my end. Just do:

```js
this.refs.question1.getDOMNode().submit();
```
Use native behavior. jQuery probably does some crazy wrapping messing things up :-)

**Comment by eriklharper** [comment]
Thanks @christianalfoni that does work for me, except that I can't stop the form from performing its default action for some reason.  It submits the form and refreshes the page, which is not what I want to happen since my form is submitting data to a local store instead of a server.  I've since changed the implementation to not actually call the native form submit function, and instead I've relied on a custom action that I can call from elsewhere to trigger saving the form data using `getCurrentValues()` which, by the way is a handy feature that isn't well documented in the Readme.  

I found that to get around cross-browser form implementation issues, I've come to rely more on handling the submit action of my forms manually and not relying on the browser's native form behavior.

Also, for some reason when I wrap it in the jquery selector, it prevents the page reload on submit, and that's probably because by default jQuery prevents the default action?

**Comment by christianalfoni** [comment]
Hi again @eriklharper ,

Hm, yeah. You would have to register a native event listener preventing that behavior. What a pickle this is :-D

Yeah, `getCurrentValues()` is actually an internal method, but glad I exposed it now. Let me add this as an enhancement and document it. Glad it worked out for you. Sounds like a very reasonable implementation.

Yeah, jQuery registers a listener and wraps "event.preventDefault" by default I believe :-)

**Comment by mull** [comment]
Am I the only one having trouble intercepting the submit event for a form created with Formsy.Form? I cannot get either `onsubmit` or `onSubmit` callbacks to be called at all.

**Comment by christianalfoni** [comment]
Hi @mull,

Could you explain a bit more what you are trying to achieve? Formsy handles the native form submition and prevents default behaviour. What do you need the form event for?

**Comment by mull** [comment]
That's the thing, it doesn't seem to! Perhaps it does on master, I did only try with the latest version through npm. The code below is basically my setup. Calling the `testSubmit` method would submit the form and reload the page. Trying to add an event listener to the <form> node in the DOM and using `preventDefault` wouldn't work either.

```jsx
testSubmit() {
  this.refs.form.getDOMNode().submit();
},

render() {
  return (
    <Formsy.Form ref="form">
      {/* some inputs */}
    </Formsy.Form
  );
}
```

**Comment by christianalfoni** [comment]
Hi @mull,

This is probably the wiring of React I believe, since you trigger a native event doing that. Put you can do this:

```js
testSubmit() {
  this.refs.form.submit(); // Point directly to the form component
},

render() {
  return (
    <Formsy.Form ref="form">
      {/* some inputs */}
    </Formsy.Form
  );
}
```

Does that solve your challenge?

**Comment by mull** [comment]
Well crap! That looks easy enough... dang. :) I'll get back to you within 24hrs on that!

**Comment by christianalfoni** [comment]
Hehe, great ;-)

**Comment by eriklharper** [comment]
Yeah, this is one thing about React that takes some time to sink in.  A lot of times you are re-implementing features of a native DOM element (in this case the submit action of a `<form>`).  This is the beauty of React and Formsy: you rely on the Formsy API to handle the submit, not the DOM api, which brings the benefit of allowing custom behavior and removes the complexities that occur with the native DOM implementations, which tend to vary across browsers as we all know.

**Comment by mull** [comment]
I kind of confused myself here. We're actually wrapping Formsy.Form with our own component, which of course didn't have the submit() function. Gotta remember that next time. :grin:

**Comment by christianalfoni** [comment]
@mull ,

But things work as you want now? If so, I will close the issue :-)

**Comment by mull** [comment]
Oh yeah it works for sure. :) thanks!

**Comment by christianalfoni** [comment]
Sweet!

**Comment by arshdkhn1** [comment]
@christianalfoni submit via ref will also trigger native event because I believe ref stores underlying dom elements. Hidden input technique will work.

I know this is an old issue, just sharing my two cents :)

**Comment by arshdkhn1** [comment]
@christianalfoni calling submit via ref will make a native event. Programatically clicking submit button will make a synthetic event - http://codepen.io/arshdkhn1/pen/WpQwxX?editors=0110
