### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by Extra-lightwill** [christianalfoni/formsy-react#453]
When using the code from the example (below) to print the form data I get the following error when I submit the form:

`Uncaught TypeError: Converting circular structure to JSON`

```
  handleSubmit(data) {
    alert(JSON.stringify(data, null, 4));
  }

```
Unsure how to fix this?

**Comment by KazeSenoue** [comment]
`data` isn't a JSON object.
