### ISSUE TITLE
Add reset method to Formsy.Form

### ISSUE THREAD

**Issue by sdemjanenko** [christianalfoni/formsy-react#46]
I have a case where after submitting a form I would like to reset it to the pristine state.

**Comment by christianalfoni** [comment]
Second argument should be a reset function. Does it not set pristine state
maybe?

**Comment by sdemjanenko** [comment]
Actually i think `resetModel` does what I want.

**Comment by sdemjanenko** [comment]
It would be nice if documentation was added for this.
