### ISSUE TITLE
Support boolean value

### ISSUE THREAD

**Issue by sdemjanenko** [christianalfoni/formsy-react#47]
The code in `getInitialState` in the Mixin: `_value: this.props.value ? this.props.value : ''` does not support `this.props.value === false`.  I think the correct fix would be to check against `undefined`.

**Comment by christianalfoni** [comment]
Yes, you are right! There was an initial uncertainty on "what is a none value". But since Formsy ended up allowing any kind of value really this should be given an other look.

**Comment by christianalfoni** [comment]
This is fixed in next version

**Comment by kristian-puccio** [comment]
is this also working for getValue() ?

For radioboxes with a value of {true} I get a string 'true'.

**Comment by kristian-puccio** [comment]
Sorry ignore it, browsers render boolean radio values as strings.

**Comment by christianalfoni** [comment]
Cool :-)
