### ISSUE TITLE
Allow for more project owners

### ISSUE THREAD

**Issue by th3fallen** [christianalfoni/formsy-react#475]
Since it's clear @christianalfoni doesnt have the time needed for the maintenance of this library would you consider allowing some of your top contributors to have merge powers so the community could assist in keeping this amazing form lib alive.

And again thank you so much for this library i've yet to find another that is as easy to use

**Comment by aesopwolf** [comment]
I've been debating forking this repo to it's own organization so that I can easily add more owners.

@track0x1 would you be interested in being added as an owner?

**Comment by th3fallen** [comment]
@aesopwolf honestly i'd fork this one if you were going to go that route https://github.com/maccuaa/formsy-react-2

**Comment by track0x1** [comment]
@aesopwolf Sure, I'm interested in keeping this thing alive.

**Comment by th3fallen** [comment]
i'd also love to lend a hand

**Comment by tijs** [comment]
i'm currently investigating some of the form handling options for react and this seems like a pretty solid choice if it weren't for the commit situation. it looked to me like the mixin issues were mostly settled in the beta branch but from this i gather that that branch is not about to be merged into master anytime soon... if you guys fork this will you fork form the beta branch or more likely forms-react-2 (or something else). guess that's hard to say right now, just looking for hints :)

**Comment by maccuaa** [comment]
I'd be fine with forking this repo to it's own organization.  This way I could drop formsy-react-2.  I can also lend a hand if needed.

**Comment by track0x1** [comment]
FWIW... https://github.com/track0x1/formsy-react (published to npm as `formsy-react-es6`)
and https://github.com/track0x1/formsy-react-native (published to npm as `formsy-react-native`) a port of Formsy to React Native :)

**Comment by rkuykendall** [comment]
@aesopwolf Any update on this? The beta PR you opened ( https://github.com/christianalfoni/formsy-react/pull/477 ) sounds hopeful that this project is no longer dead?

We are trying to evaluate if we need to move `formsy-react-2` to ever get react 16 support.

**Comment by th3fallen** [comment]
@rkuykendall formsy-react-2 works with 16 atm not sure about this version but i can confirm im using version 2 with react 16 with no issues

**Comment by rkuykendall** [comment]
@th3fallen Thanks, but if this project has figured out how to un-stick itself that would be a much better solution, as the fork would need to gain a lot of momentum.

**Comment by th3fallen** [comment]
@rkuykendall totally agree was just letting you know

**Comment by tijs** [comment]
👍

**Comment by th3fallen** [comment]
Closing since this is resolved.
