### ISSUE TITLE
Support Node 15 with NPM 7 with React v17.0

### ISSUE THREAD

**Issue by vitaliyhayda** [christianalfoni/formsy-react#500]
On Node 15 with NPM 7 with React v17.0 there is the following error:

    npm ERR! code ERESOLVE
    npm ERR! ERESOLVE unable to resolve dependency tree
    npm ERR! 
    npm ERR! While resolving: ifexo-front@v0.5.8
    npm ERR! Found: react@17.0.1
    npm ERR! node_modules/react
    npm ERR!   react@"17.0.1" from the root project
    npm ERR! 
    npm ERR! Could not resolve dependency:
    npm ERR! peer react@"^16.0.0" from formsy-react@2.2.1
    npm ERR! node_modules/formsy-react
    npm ERR!   formsy-react@"2.2.1" from the root project
    npm ERR! 
    npm ERR! Fix the upstream dependency conflict, or retry

**Comment by rkuykendall** [comment]
# This project has moved to [formsy/formsy-react](https://github.com/formsy/formsy-react/).
