### ISSUE TITLE
Add travis-ci

### ISSUE THREAD

**Issue by sdemjanenko** [christianalfoni/formsy-react#54]
It would be nice to have an automated builder hooked up to this repo.

**Comment by christianalfoni** [comment]
Good point, hm... I just want to get this next release out and will look into this when its out. Thanks for the input!

**Comment by christianalfoni** [comment]
Just wanted to let you know that this will be part of release 0.13

**Comment by sdemjanenko** [comment]
Cool. Looking forward to it. Thanks for all the hard work!

**Comment by christianalfoni** [comment]
This is now added! :-)

**Comment by rblakeley** [comment]
Seems like there is an issue with this feature, first noted in [#195](https://github.com/christianalfoni/formsy-react/pull/195#issuecomment-137144577).
Also noticed in #197.

Possibly related to this [update](https://github.com/travis-ci/travis-ci/issues/4718) in the travis-ci project.

**Comment by christianalfoni** [comment]
I am having a full review of testing before next release. With Node 0.4 release I have to change the way testing is done. It will be better :-)
