### ISSUE TITLE
IE support (xhr)

### ISSUE THREAD

**Issue by Semigradsky** [christianalfoni/formsy-react#57]
Maybe use https://github.com/Raynos/xhr for better IE support?

**Comment by christianalfoni** [comment]
Hi @Semigradsky ,

Thanks for the input, this looks like a good idea!

**Comment by christianalfoni** [comment]
Decided that XHR will be removed in 1.0 release as it is very easy to hook that manually to the form. Formsy is a form lib, not xhr lib. Covered too much initially ;-)
