### ISSUE TITLE
Ignore server error after input has changed

### ISSUE THREAD

**Issue by frost555** [christianalfoni/formsy-react#58]
After the server returned validation error, is there a way to ignore it after input was changed?
Because we no longer know that input is invalid.

**Comment by christianalfoni** [comment]
Hi @frost555 ,

Sorry for late response, I have been suck with the flue.

As I understand it when an error from the server occurs you want that error message to be ignored when the input is changed? The error should be reset every time `setValue()` is called. Does that not happen?

**Comment by frost555** [comment]
No, it does't happen. I invalidate input in handle submit function and check for error message in my input component with 'this.showError()'. I also do call this.setValue(val) when value changes. Can anyone confirm the issue?

**Comment by christianalfoni** [comment]
hi again @frost555,

I will check this ASAP

**Comment by christianalfoni** [comment]
Hi @frost555 ,

Very sorry about the delay here. I can confirm the error and will try to make a fix right now. Thanks for reporting!

**Comment by christianalfoni** [comment]
Okay, fixed, there was indeed a bug here. Thanks for reporting @frost555 !
