### ISSUE TITLE
Allow a component to decide whether it is valid

### ISSUE THREAD

**Issue by philippotto** [christianalfoni/formsy-react#60]
I have a rather complex form field (a typeahead) which should only be valid if certain conditions hold.
Since this form field only appears once in the form, it seems more natural to encapsulate the validity check within the component class rather than defining an "external" rule.

As a workaround, I make the `Formsy.addValidationRule` call currently before the complex component is defined and specify the validity rule as a prop when embedding the component.
Despite the fact that this isn't really pretty, it also leads to problems since the validator needs access to internal state.

That is why I think, the best solution for this would be to allow components to provide some sort of `checkValidity` function which will be called by Formsy.

What do you think?

**Comment by christianalfoni** [comment]
Hi @philippotto ,

Thanks for the input!

Do you have a code example of how you would like this to work? Just so I am completely sure that I understand what you are asking for :-)

**Comment by philippotto** [comment]
Even better: I opened a PR :)

**Comment by christianalfoni** [comment]
Cool, I will check it out :-)
