### ISSUE TITLE
Formsy 1.0.0

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/formsy-react#66]
Hi there!

After the next release I will be focusing on creating Formsy 1.0. Those of you who have upgraded to React 0.13.1 surely have noticed that you get warnings about props being dynamically set. The reason this is happening is because Formsy form elements needs to communicate with their children, and the children needs to communicate back. In React JS this is done by passing callbacks as props. The problem with that is the dynamic nature of Formsy. It would not be a very good API if you manually had to pass all props on every single form element you added.

But there is an alternative and that is using events. Sadly React JS does not support custom synthetic events, which means that we either have to rely on native DOM events or add an event hub to Formsy. 

### Native events
The benefit of using native events is syntax:

```js
var Form = React.createClass({
  mixins: [Formsy.FormMixin],
  render: function () {
    return (
      <Formsy.Form>
        <MyFormElement name="foo"/>
      </Formsy.Form>
    );
  }
});
```
But it reduces testability because we are using DOM event listeners to communicate between the form and its form elements. It is a good tradeoff I think because you really only need this communication in the browser, but it does have some risks, if even doable.

### Event hub
The benefit of using an event hub is that we now do not depend on the DOM at all. The downside though is that we have to name our forms. The reason is that we need to namespace each form so that events going back and forth are going back and forth between the correct forms and form elements:

```js
var Form = React.createClass({
  mixins: [Formsy.FormMixin('myForm')],
  render: function () {
    return (
      <Formsy.Form>
        <MyFormElement name="foo"/>
      </Formsy.Form>
    );
  }
});

var MyFormElement = React.createClass({
  mixins: [Formsy.ElementMixin('myForm')],
  render: function () {
    return <input/>
  }
});
```
I think this is a safer bet because we are not depending on the DOM for communication. It is also safe in regards of naming because it is possible to give warnings when forms try to override each other or elements registers to a form that does not exist. 

The big problem though is that you probably want to reuse form elements in different forms. That would not work with this strategy.

### Summary
Okay, these are just some initial thoughts. Please let me know if you have any thoughts on this!

@sdemjanenko, @Semigradsky, @mistakster, @michaelcontento

**Comment by gaearon** [comment]
You can try using `context` for “hidden” props, like React Router and a few other libraries. It's going to be parent-based in React 0.14, so with `<Parent> ... <Child /> ... </Parent>` Child will receive Paren't context (this is your use case isn't?). Before React 0.14, context is owner-based, so this doesn't quite work nicely.

Overall `context` is an undocumented feature and it's better not to rely on it too much, but forms seem like a valid use case, and we know it's not going away anywhere.

**Comment by christianalfoni** [comment]
@gaeron , thanks for that input! This definitely seems like a valid way to go. I have been using it to solve other scenarios, so I will play around with it a bit :-)

**Comment by gaearon** [comment]
Btw I remember reading that parent context can already be accessed in React 0.13 via `this._reactInternalInstance._context`. In React 0.14, `this.context` will switch to it.

**Comment by jmartin84** [comment]
Does the new cloneElement in 0.13 function solve the use case of dynamic props?

https://facebook.github.io/react/blog/2015/03/03/react-v0.13-rc2.html

**Comment by christianalfoni** [comment]
Hm,

Seems we have to wait for React 0.14. Tried getting this new parent-child context temporary patch working, https://gist.github.com/jamesknelson/1481521444e1529d59aa#file-react-parent-context-patch-js, but can not get it to work.

**Comment by christianalfoni** [comment]
@jmartin84 Will look into it, might work :-) Thanks!

**Comment by christianalfoni** [comment]
@jmartin84 I checked it out, but it only works with immediate children, need something a bit more flexible. Got the new parent-child context thing running now so I think we will end with that solution .It is also confirmed for next React release, so I think we are in the clear on this challenge :-) Thanks for the suggestion though!

**Comment by christianalfoni** [comment]
@jmartin84 Actually, this is exactly what we can do. I just did not see clearly how to handle nested children, but I do now :-) Will create a fix for this. Will still change to context on React 0.14, @gaearon , as it is more optimized. But now we are in the clear, awesome, thanks!
