### ISSUE TITLE
release/formsy-react.js doesn't work?

### ISSUE THREAD

**Issue by Semigradsky** [christianalfoni/formsy-react#67]
I create this code in plugin directory:

file: a.js
```
var a = require('./release/formsy-react.js');
console.log(a);
```
When I run `node a.js`, I got:
```
{}
```

**Comment by christianalfoni** [comment]
Hi @Semigradsky,

That is the bundled release. To use formsy in Node environments you require it like a normal NPM module:

```js
var a = require('formsy-react');
```
Hope that answers your quesiton :-)

**Comment by Semigradsky** [comment]
> That is the bundled release.

How to use it? Why do it?

**Comment by christianalfoni** [comment]
Hi again,

It is for people using bower or just use a normal script tag and use it globally :-) Or requirejs.

**Comment by Semigradsky** [comment]
Oh, I see, thank you!
