### ISSUE TITLE
Promise in browsers

### ISSUE THREAD

**Issue by Semigradsky** [christianalfoni/formsy-react#70]
https://github.com/christianalfoni/formsy-react/blob/master/src/utils.js#L19
Promise has [bad support in IE](http://caniuse.com/#feat=promises). Maybe remove it or use [polyfill](https://github.com/jakearchibald/es6-promise)?

It seems not necessary to use Promise.
https://github.com/christianalfoni/formsy-react/blob/master/src/main.js#L110-L115

**Comment by christianalfoni** [comment]
@Semigradsky ,

Yeah, I agree on that. I will remove it for next version. Thanks for the input!

**Comment by Semigradsky** [comment]
Now this issue is not actual =)
