### ISSUE TITLE
Mixin: False value being converted to empty string

### ISSUE THREAD

**Issue by gpbmike** [christianalfoni/formsy-react#71]
I see here https://github.com/christianalfoni/formsy-react/blob/47dd80b67f9104ab98567fd5d9f5387f6c4b8722/src/Mixin.js#L3 that falsy values are being converted to `''` when setting the value of a component using the mixin.

``` javascript
  getInitialState: function () {
    var value = 'value' in this.props ? this.props.value : '';
    return {
      _value: value,
      _isValid: true,
      _isPristine: true,
      _pristineValue: value
    };
  },
```

In my case I have a radio button with boolean values (true/false). False is being converted to `''` and the API is rejecting it. I've worked around it by coercing in `onSubmit` but I was just curious if there was a reason why this is being done.

**Comment by christianalfoni** [comment]
Hi @gpbmike ,

Do you set the initial value to false? 

```js
<MyCheckBox value={false}/>
```

If so it should work. The `'value' in this.props` only checks if the key "value" exists in props, not if the value is "truthy".

The reason behind '' is that you can really create any element. If a checkbox has its value by default false, there is no way for Formsy to understand that. You kinda have to tell it by passing a default "false" value. What you get back though is lots of flexibility in what kind of form elements you want to build :-) 

Example of checkbox:

```js
var MyCheckbox = React.createClass({
  mixins: [Formsy.Mixin],
  changeValue: function (event) {
    this.setValue(!this.getValue());
  },
  render: function () {
    return (
      <div>
        <input type="checkbox" checked={this.getValue()} onChange={this.changeValue}/>
      </div>
    )
  }
});

<MyCheckBox name="foo" value={false}/>
```

**Comment by gpbmike** [comment]
My bad, I'm using an older version. My problem was fixed with these commits:

https://github.com/christianalfoni/formsy-react/commit/bade05b9cd2e3845ecc7814fe5d1516b05c82133
https://github.com/christianalfoni/formsy-react/commit/dca9f785248346431a32e0121d970b6a0a4a55b8

I thought I was linking to the erroneous line I found in my local version. I didn't look close enough. :)

Cheers.

**Comment by christianalfoni** [comment]
Ah, cool, great :-)
