### ISSUE TITLE
Support empty values in validationRules

### ISSUE THREAD

**Issue by paddyinpdx** [christianalfoni/formsy-react#73]
In validationRules.js it would be nice if you used `(value || '')`, or something like that, to allow functions like `isNumeric` to work even on a field with no value set. As it is currently, a "Cannot read property 'match' of undefined" error is thrown if I have isNumeric set yet no input value (e.g., when there's a new form).

**Comment by christianalfoni** [comment]
Thanks @paddyinpdx, will fix this on next release :-)

**Comment by christianalfoni** [comment]
This one should work on release 0.12
