### ISSUE TITLE
Parameters not being nested in Rails

### ISSUE THREAD

**Issue by arunthampi** [christianalfoni/formsy-react#76]
I'm using Formsy with a Rails API and when I submit the form, the parameters come in as `{"member[email]"=>"asdasd@gmail.com", "member[first_name]"=>"1234", "member[last_name]"=>"123123123", "team"=>{}}` instead of `{"member"=> { "email" => "asdasd@gmail.com", "first_name"=>"1234", "last_name"=>"123123123"}}`

This is the form I'm using:

```html
<Formsy.Form method="POST" url="/teams/members" mapping={this.mapInputs} onSuccess={this.addMember} onValid={this.enableSendInviteButton} onInvalid={this.disableSendInviteButton}>
  <div id="invite-form" ref="invite_form">
    <TextInput labelValue="Email" placeholder="e.g. awesomesauce@gmail.com" labelFor="email" name="email" validations="isEmail" validationError="This is not a valid email" required/>
    <TextInput labelValue="First Name" placeholder="e.g. Awesome" labelFor="first_name" name="first_name" required/>
    <TextInput labelValue="Last Name" placeholder="e.g. Sauce" labelFor="last_name" name="last_name" required/>
    <button type="submit" className="btn btn-outline btn-success" disabled={!this.state.canSubmit}>
      <i className="fa fa-paper-plane"/>&nbsp;
      Send Invitation
    </button>
    <a onClick={self.onCancelClick} className="cancel-button text-danger">Cancel</a>
  </div>
</Formsy.Form>
```

and this is is `mapInputs` function (in Coffeescript):

```coffeescript
mapInputs: (inputs) ->
  'member[email]': inputs.email
  'member[first_name]': inputs.first_name
  'member[last_name]': inputs.last_name
```

What am I doing wrong?

(P.S. It works as expected, (i.e. the params are nested) when using a vanilla form)

**Comment by Semigradsky** [comment]
Try this `mapInputs` function:
```coffee
mapInputs: (inputs) ->
  member:
    email: inputs.email
    first_name: inputs.first_name
    last_name: inputs.last_name
```

**Comment by arunthampi** [comment]
That worked, thanks @Semigradsky!

Closing for now, @christianalfoni shall I open a pull request to add @Semigradsky's solution as documentation in the `mapInputs` section?

**Comment by christianalfoni** [comment]
Hi @arunthampi, yeah, that would be great! Thanks a lot, and thanks @Semigradsky for helping out with support! :+1:
