### ISSUE TITLE
Resetting individual inputs?

### ISSUE THREAD

**Issue by frost555** [christianalfoni/formsy-react#81]
Maybe we should allow to pass array of input names to reset function?

    handleSubmit: function(data, reset, invalidate) {
      reset(['foo', 'boo']);
    }

I think it is easy to implement and would add flexability.

**Comment by frost555** [comment]
Though i think it is not very useful. Finding hard to find a good use case. Therefore closed.

**Comment by christianalfoni** [comment]
HI @frost555 ,

Yeah, I think you are right, I can not see a scenario where it would be useful. But if it appears, we know what to implement :-)
