### ISSUE TITLE
showError() doesn't work right when using a 'number' input type

### ISSUE THREAD

**Issue by eriklharper** [christianalfoni/formsy-react#82]
This might have to do with how the native `<input type="number">` input works, but it looks like the `showError()` function returns the opposite of what is expected:

```
...
changeValue: function (event) {
    this.setValue(event.currentTarget.value);
},

render: function () {

    // Required State
    var required = '',
        requiredMessage = '';

    if (this.state.required && this.showRequired()) {
      required = ' required error ';
      requiredMessage = (
        <p>{this.props.placeholder + ' is required.'}</p>
      );
    }

    // Error State
    var error = '',
        errorMessage = '';

    if (this.showError()) { // This does not return what is expected, resulting in no error message displayed when the input is invalid.
      error = ' error ';
      errorMessage = (
        <p>{this.getErrorMessage()}</p>
      );
    }

    console.log("Value: " + this.getValue());
    console.log("isValid(): " + this.isValid());
    console.log("showError(): " + this.showError());

    return (
      <div className={'formsy-number-input' + required + error}>

        <input
          type='number'
          name={this.props.name}
          onChange={this.changeValue}
          onFocus={this.props.onFocus}
          placeholder={this.props.placeholder}
          defaultValue={this.props.defaultValue}
          value={this.getValue()} />

        {requiredMessage}
        {errorMessage}

      </div>
    );
}
```

![image](https://cloud.githubusercontent.com/assets/821864/7098937/deb3a06e-df9d-11e4-840b-4dff6985e38b.png)

On my console, I see this when I enter some alpha characters into my `number` field:

```
Value: 
isValid(): false
showError(): false
```

First of all, looks like the value isn't getting set at all (in this example, the letter `a`), but despite that, I would expect `showError()` to return true if the result of `isValid()` is false.

**Comment by christianalfoni** [comment]
HI @eriklharper ,

I think you have to fix a couple of things first:

event.target.value, not currentTarget. currentTarget would be the body I think, as that is where the event is captured. target is the element that triggered the event, the input :-)

And I also see you referencing `this.state.required`,should be `this.props.required`?

Hope this helps!

**Comment by eriklharper** [comment]
Thanks for the tips @christianalfoni !  I got this working now with the number input.  I'm using `event.target.value` now, which is pulling in the proper typed value.  Also, to clear up confusion, I've renamed `this.state.required` to be `this.state.displayRequired` instead.  

The meaning behind that state object is that my parent form component is wired up to control when the `required` css class is present on the text input or not based on its validation status.  I have a requirement to show required fields when the submit button is clicked, so I created a `displayRequired` prop that holds a boolean to do just that.  I take the `displayRequired` prop, store it in `this.state.displayRequired` in the text input component so that I can toggle it off from within once the user starts typing a value.  It works pretty well!

Thanks again for your help!  Looking very forward to 1.0!   Let me know if there is anything you need help with, would love to contribute!

**Comment by christianalfoni** [comment]
Hi @eriklharper,

Great you got it working :-)

I would love getting started with the wiki. The repo has a technical description, but the wiki could be a more practical description. Showing how you build different types of form elements and explaining strategies to validations etc.

https://github.com/christianalfoni/formsy-react/wiki

Feel free to do whatever you want there, or nothing if its boring ;-)
