### ISSUE TITLE
Default validation rules return false value when input value is empty

### ISSUE THREAD

**Issue by dprentis** [christianalfoni/formsy-react#90]
Current default validation rules such as isEmail, isAlpha, isWord, etc. return false, when the input value is empty (ie. value parameter is undefined or empty string). In this scenario, how do you define, for example, a non-required email input?

I guess we just have to define our own validation rules, or is there some other way this should work?

For example, Angular forms pattern validation computes empty inputs as valid, to allow to easily optionally combine with 'required' validation - wouldn't that be the way to go?

**Comment by christianalfoni** [comment]
I absolutely agree. This was changed due to Formsy allowing any kind of form element with any kind of value, but these validations specifically point to "inputs", where a "none-value" should be valid.

This is fixed in next version! Thanks :-)

**Comment by dprentis** [comment]
Again, thanks for addressing this so fast! :) will take a look at the latest version..

**Comment by dprentis** [comment]
I can't get required validation to work with version 0.12.2 eg.
```
<Input name="myInput" required />
```

The form is valid even though the input (a textbox) is empty.

Current work-around is just to implement an isRequired validation rule and use that instead.
```
Formsy.addValidationRule('isRequired', function(values, value) {
  return typeof value !== 'undefined' && value !== '' && value !== false;
});
```

**Comment by christianalfoni** [comment]
Hi @dprentis,

There seems to be a bug here, working on it now. Thanks for reporting!

**Comment by christianalfoni** [comment]
Okay, fixed it... releasing new version now. Sorry about that, but written test for it too. Will not happen again :-)
