### ISSUE TITLE
'Object.keys called on non-object' in submit() because Form does not have 'headers' prop

### ISSUE THREAD

**Issue by jcapogna** [christianalfoni/formsy-react#91]
I'm getting the following error when I submit the form.

```
Uncaught TypeError: Object.keys called on non-object
```

coming from main.js:107

```
var headers = (Object.keys(this.props.headers).length && this.props.headers) || options.headers || {};
```

The Form component does not contain the 'headers' prop. 

Using:
formsy-react 0.11.2
react 0.13.1

**Comment by christianalfoni** [comment]
Thanks for reporting, this is fixed in next release which arrives today :-)
