### ISSUE TITLE
v0.12.0: Warning: Unknown DOM property novalidate. Did you mean noValidate?

### ISSUE THREAD

**Issue by adamellsworth** [christianalfoni/formsy-react#92]
For custom inputs that lack validations the following warning is thrown:

    Warning: Unknown DOM property novalidate. Did you mean noValidate?

Markup looks like so:

    <Formsy.Form>
        <Input name="title" required/>
    </Formsy.Form>

But as this is a validation lib, this may be a non-issue.

**Comment by christianalfoni** [comment]
Thanks for reporting @adamellsworth !

Released 0.12.1 now. The implementation was misunderstood. Sorry about that.
