### ISSUE TITLE
All server errors cleared when one of the inputs is changed

### ISSUE THREAD

**Issue by pkmiec** [christianalfoni/formsy-react#93]
I noticed that when I have server errors returned (and set via invalidateForm callback), the form correctly shows all the errors next to their fields. However, as soon as I type into one of the inputs all the errors disappear. 

For example (just a test form I'm using),
![form with server errors](https://cloud.githubusercontent.com/assets/7186/7150155/b4129f6e-e2cb-11e4-95bc-f272d95975c0.png)
and typing into the username would immediate make both errors disappear.

This ends up being not so nice as the user may not even have read all the errors before starting to fix some of the fields.

I suppose this happens because from the client-side's perspective all the fields are valid. So typing into one of the inputs causes all of them to validate and the errors go away.

Any recommendations?

btw, using the latest formsy-react on master.

**Comment by ordinathorreur** [comment]
I was having some difficulty displaying server error messages in a Flux app with an older version of Formsy and upgraded to the latest version to see if anything had changed to make this easier, perhaps by allowing you to set a serverErrors prop on the form itself, much the same way as the current implementation allows you to pass a validationErrors prop.

Taking a look at the latest code I think the behaviour you're describing here is related to some recent changes. I haven't looked at the recent commits in detail, but I'm guessing this probably happened when the ajax stuff was pulled out.

Looking through the latest code there are two methods that look to have changed a bit recently: setInputValidationErrors and updateInputsWithError. In fact the comment above the updateInputsWithError no longer seems correct.

setInputValidationErrors sets a _serverError object, but this is not used by the getErrorMessage method anymore. This means that the easiest way to display a server error message is to pretend it's a custom local validation error and set the validationErrors prop on the form component. This of course gets blown away as soon as the form gets revalidated.

I think the old version of Formsy I had used to look at the _serverErrors as well as the _validationErrors hashes in the getErrorMessage method, but it looks like it doesn't do that anymore. I would love to be able to set a serverErrors prop on the form in much the same way as you can now set validationErrors props.

**Comment by pkmiec** [comment]
Thanks. That confirms my suspicions. 

I actually have a work around much like what you are describing. I made my own method to set server errors,

```js
  setServerErrors: function(errors) {
    var form = this.refs.formsy;
    
    Object.keys(form.inputs).forEach(function (name, index) {
      var component = form.inputs[name];
      var args = [{
        _isPristine: true,
        serverError: errors[name]
      }];
      component.setState.apply(component, args);
    });
  },
```

And then I can explicitly check for `isPristine() && this.state.serverError` in the input.

Notice I don't set `_isValid` to false like setInputValidationErrors since I thought the user should be able to submit the form again in this case.

**Comment by christianalfoni** [comment]
Hi guys!

I am releasing a new version now where this is fixed :-) let you know!

**Comment by christianalfoni** [comment]
Okay, released 0.12.5, https://github.com/christianalfoni/formsy-react/releases/tag/v0.12.5, would be great if you could verify that it works :-)

**Comment by pkmiec** [comment]
Yes, it works! The external errors for an input do not disappear until that input is touched by the user.

I still prefer to be able to submit the form when they are only external errors. I can continue to do that with a custom method.

**Comment by christianalfoni** [comment]
Hi @pkmiec ,

Great, thanks!

Yeah, this is a very specific implementation detail. The `onSubmit` you can register on a Formsy.Form  could get more information than just the value. Could even pass the component itself. So you would:

```js
var MyForm = React.createClass({
  mySubmit: function (inputs, reset, invalidate) {
    inputs.foo.getValue();
    inputs.foo.isPristine();
    inputs.foo.isValid();
    inputs.foo.hasExternalError(); // new method
  },
  render: function () {
    return (
      <Formsy.Form onSubmit={this.submit}>
        <MyInput name="foo" validations="isEmail"/>
      </Formsy.Form>
    );
  }
});
``` 

Do you think something like that would be valuable?

**Comment by ordinathorreur** [comment]
Looks good, thanks for this @christianalfoni 

I too think it would be quite useful to be able to set errors that don't actually affect the form's valid/invalid state. The external errors applied to the form are really just async errors; errors you can't check on each local validation cycle. The presence of an external error shouldn't necessarily affect the form's valid state; having an external error that says "username already taken" in a signup form shouldn't make the whole form invalid. 
I don't think this functionality is an edge case and writing the code in my own app to implement this looks like it may add a lot of additional overhead/maintenance, something I was hoping a form abstraction library would take away.
Could it be an idea to pass a prop that lets the form know that the external errors should/shouldn't affect it's validity?

**Comment by pkmiec** [comment]
@christianalfoni, I don't think your suggestion works for me. The reason is that in order to submit the form, I'd need have to loop over all the inputs checking whether each one is valid or is invalid with an external error. And I would have to apply similar logic if I wanted to disable / enable the form submit button.

I view it like @ordinathorreur does. Where the external errors do not affect the client side form validity.

**Comment by christianalfoni** [comment]
Hi again guys and thanks for the discussion! This is a tough one and its difficult for me to decide on a good solution as I have not really been in this specific situation before. So I will just give some more suggestions on solving it with focus on keeping the API clean and simple :-)

```js
onSubmit: function (model, reset, setErrors) {
  invalidate(serverErrors, false); // Passing false will not invalidate the inputs, only set errors
}
```

You think that would cover the need? The way you can decide by scenario if you want external errors to actually invalidate the inputs, or just give an error? Again, any change to the input would clear the error of that specific input.

**Comment by pkmiec** [comment]
Yeah, I can see how different people may want different behaviors. Let me play with your suggestion locally and see if it works.

**Comment by pkmiec** [comment]
Hmm .. just not setting isValid in updateInputsWithError is not enough. You run into this,

```js
if (validation.isValid && component.state._externalError) {
  validation.isValid = false;
}
```

It seems to me we're discussing whether server errors / external errors make a field invalid and therefore make the form invalid. Perhaps best is to delegate that to the Mixin (as it is already required that it is used to implement an Input). We'd replace _isValid on the input with isValid(). That way, it is very easy to choose which way it should work. Here is some rough code, 

```js
// rename updateInputsWithError to setExternalErrors
  setExternalErrors: function (errors) {
    Object.keys(this.inputs).forEach(function (name, index) {
      this.inputs[name].setExternalError(errors[name]);
    }.bind(this));
  }
```

and in the Mixin would be implemented like this,

```js
setExternalError(error) {
  this.setState({
    _externalError: error
  });
},

setValidationError(error) {
  this.setState({
    _validationError: error
  });
},

isValid: function() {
  !!this.state._validationError || !!this.state._externalError
},

getErrorMessage() {
  this.state._externalError || this.state.validationError
},
```

then I could override isValid to not consider external errors, 

```js
isValid: function() {
  !!this.state._validationError
}
```

**Comment by christianalfoni** [comment]
Hi @pkmiec ,

Thanks for the suggestion! I think we are getting somewhere here, though I am not quite sure about delegating it to the mixin. I do see the advantage of overriding, I think it looks quite nice, but the validation of an input is not determined by the mixin, but the form. Because the valid state affects both the form and possibly other inputs.

So if I understand your suggestion correctly the form would not be able to invalidate on external errors, only a particular input would. 

The way I see it is that we have two very specific behaviours we want to achieve. "Should external errors invalidate the input and form, or should it not?". Translating this to an API change that question is most simply answered with a boolean. My initial suggestion was on the callback of invalidating with external errors, but what about a form prop instead?

```js
<Formsy.Form preventExternalErrorValidation/>
```

Or did I miss an important point here? ;-)

**Comment by christianalfoni** [comment]
Okay, adding `preventExternalInvalidation` in new release
