### ISSUE TITLE
Server side validations not shown when client side validation exist

### ISSUE THREAD

**Issue by pkmiec** [christianalfoni/formsy-react#94]
This is a follow up to https://github.com/christianalfoni/formsy-react/issues/93. In the original issue, neither username nor password has any client side validations set and the server always returns an error for username and password. 

When I add validations={{isEmail: true}} to the username, the server side validations for username are no longer displayed. They are still displayed for password.

My understanding is that both client side validations and server side validations are meant to be supported. Am I doing something wrong?

**Comment by pkmiec** [comment]
Actually, I just noticed I had `required` on username / password. So it works when it is like this,

```jsx
<Formsy.Form onSubmit={this.onSubmit}>
  <Input type="text" name="username" label="Username" validations={{isEmail: true}} /> // work when no required here
  <Input type="password" name="password" label="Password" required/>
  <Button type="submit" bsStyle="primary" disabled={this.state.isSubmitting}>Login</Button>
</Formsy.Form>
```

**Comment by christianalfoni** [comment]
Hi @pkmiec ,

Could you check again with latest version? There was a bug with the required validation

**Comment by pkmiec** [comment]
Yes, fixed. Thanks.
