### ISSUE TITLE
onValidSubmit and onInvalidSubmit are no longer passed updateInputsWithError

### ISSUE THREAD

**Issue by pkmiec** [christianalfoni/formsy-react#95]
It looks like https://github.com/christianalfoni/formsy-react/commit/5e00ea281feb8d53ed42685019e8a7751a40349b#diff-1c90ff38a08209f9ebd4d05d1e43358e started passing updateInputsWithError as the third parameter to onValidSubmit and onInvalidSubmit.

And it looks like the very next commit (https://github.com/christianalfoni/formsy-react/commit/5e00ea281feb8d53ed42685019e8a7751a40349b#diff-1c90ff38a08209f9ebd4d05d1e43358e) reverted it.

**Comment by christianalfoni** [comment]
Hmf, git is doing something weird with this code. Fixed with new version and added tests for it. Thanks for reporting!
