### ISSUE TITLE
Can i show error message for pristine inputs only when error is server side?

### ISSUE THREAD

**Issue by frost555** [christianalfoni/formsy-react#98]
The problem arises when i combine form reset with form invalidation, caused by invalid password for example. I can't determine correctly when i need to display error message.
I use the following code to determine className and errorMessage. This code fails for error message when form was reset and invalidated.

    render: function() {
      var errorMessage = null;
      if (!this.isPristine() && this.showError()) {
        errorMessage = this.getErrorMessage();
      };
      var className = null;
      if (!this.isPristine() && (this.showError() || this.showRequired()) ) {
        className = 'has-error';
      } 

      return (
        <div className={className}>
          <input ... />
          {errorMessage}
        </div>
      );
    }

I need to show error message for pristine inputs *only* when error is server side. Can i achieve this behaviour right now, or the library need some changes?
If i just simply change condition to 

    if (this.showError()) {
      errorMessage = this.getErrorMessage();
    };

Then error message will be displayed for pristine inputs with client side validation error. Which is not desirable.

**Comment by pkmiec** [comment]
I believe you're getting at the same thing as I was in https://github.com/christianalfoni/formsy-react/issues/93.

You want to continue to show the server side error message on a field until the user modified that field.

**Comment by christianalfoni** [comment]
Hi guys,

Released 0.12.5 which should fix this error. https://github.com/christianalfoni/formsy-react/releases/tag/v0.12.5
