### ISSUE TITLE
Initial state of form validity and valid/invalid broadcasting

### ISSUE THREAD

**Issue by bryannaegele** [christianalfoni/formsy-react#99]
I removed my pull request until I ran this past you @christianalfoni and put this out to anyone else that wants to add input.

The first issue we have been grappling with is the triggering of callbacks on every call to validateForm. This is caused by invoking the callbacks for onValid or onInvalid for every keystroke for the current state of the form. The user is then forced to process and track state of the form elsewhere to determine in their callbacks whether or not to execute their code if they only need to do so on a change of state. Our proposed solution is to only set the state and trigger the callback when the state is actually changing.

The second issue builds on the solution to the first. Currently, the form is always set to valid during initialization. If you pre-populate the form and it is valid, the onValid handler would not be invoked because the state would change. Is there any argument against setting the isValid to false in getInitialState?

We've already done both of these internally but wanted to get feedback before I put the PR back up.

So the proposed changes:
1. only call setState and invoke onValid or onInvalid handlers if the state is changing.
2. set the initial state of the form to invalid.

Any thoughts?

Here's the diff link https://github.com/christianalfoni/formsy-react/compare/master...bryannaegele:master

**Comment by christianalfoni** [comment]
Hi Bryan,

1. This absolutely makes sense

2. If I understand you correctly you would get the opposite problem if pre populating and expect it to trigger onInvalid? :-) Maybe a better solution is to ensure that the onValid/onInvalid always triggers after initialising?

**Comment by christianalfoni** [comment]
Just cleaning up issues. Though you pointed out some good stuff here I will close the issue, as I have not gotten feedback on this by anyone else and I require some more discussions to make a solution. Please keep on commenting to make this part of formsy.

**Comment by th3fallen** [comment]
super late on this but i totally agree onValid should be false if the fields are populated by value when the form boots
